# SPDX-License-Identifier: GPL-2.0
# All platforms listed in alphabetic order

platforms += cavium-octeon
platforms += generic

# include the platform specific files
include $(patsubst %, $(srctree)/arch/mips/%/Platform, $(platforms))
