# -*- Kbuild -*-
#
# Linux Generic Netlink module.
#
# Copyright 2018-2025 Broadcom. All rights reserved.
# The term 'Broadcom' refers to Broadcom Inc. and/or its subsidiaries.
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License 
# version 2 as published by the Free Software Foundation.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# A copy of the GNU General Public License version 2 (GPLv2) can
# be found in the LICENSES folder.
#
# Enable Kernel PMD
KNETCB_CPPFLAGS += -DKPMD

obj-m := linux_bcmgenl.o

ccflags-y := $(SDK_PMD_KFLAGS) $(LKM_CFLAGS) $(LKM_CPPFLAGS) \
	     -I$(SDK)/shr/include \
	     -I$(SDK)/bcmdrd/include \
	     -I$(SDK)/bcmltd/include \
	     -I$(SDK)/bcmlrd/include \
	     -I$(SDK)/linux/include \
	     -I$(SDK)/linux/include/kernel \
	     -I$(SDK)/linux/knet/include \
	     -I$(SDK)/linux/knet \
	     -I$(SDK)/linux/bcmgenl

linux_bcmgenl-y := $(SDK_PMD_KOBJS) \
                   bcmgenl_packet.o \
                   bcmgenl_psample.o \
                   bcmgenl.o
