#ifndef LINUX_4_10_COMPAT_H
#define LINUX_4_10_COMPAT_H

#include <linux/version.h>

#ifndef PCI_VENDOR_ID_MELLANOX
#define PCI_VENDOR_ID_MELLANOX		0x15b3
#endif

#ifndef PCI_DEVICE_ID_MELLANOX_CONNECTX3
#define PCI_DEVICE_ID_MELLANOX_CONNECTX3	0x1003
#endif

#ifndef PCI_DEVICE_ID_MELLANOX_CONNECTX3_PRO
#define PCI_DEVICE_ID_MELLANOX_CONNECTX3_PRO	0x1007
#endif

#ifndef PCI_DEVICE_ID_MELLANOX_CONNECTIB
#define PCI_DEVICE_ID_MELLANOX_CONNECTIB	0x1011
#endif

#ifndef PCI_DEVICE_ID_MELLANOX_CONNECTX4
#define PCI_DEVICE_ID_MELLANOX_CONNECTX4	0x1013
#endif

#ifndef PCI_DEVICE_ID_MELLANOX_CONNECTX4_LX
#define PCI_DEVICE_ID_MELLANOX_CONNECTX4_LX	0x1015
#endif

#ifndef PCI_DEVICE_ID_MELLANOX_TAVOR
#define PCI_DEVICE_ID_MELLANOX_TAVOR		0x5a44
#endif

#ifndef PCI_DEVICE_ID_MELLANOX_TAVOR_BRIDGE
#define PCI_DEVICE_ID_MELLANOX_TAVOR_BRIDGE	0x5a46
#endif

#ifndef PCI_DEVICE_ID_MELLANOX_SINAI_OLD
#define PCI_DEVICE_ID_MELLANOX_SINAI_OLD	0x5e8c
#endif

#ifndef PCI_DEVICE_ID_MELLANOX_SINAI
#define PCI_DEVICE_ID_MELLANOX_SINAI		0x6274
#endif

#ifndef PCI_DEVICE_ID_MELLANOX_ARBEL_COMPAT
#define PCI_DEVICE_ID_MELLANOX_ARBEL_COMPAT	0x6278
#endif

#ifndef PCI_DEVICE_ID_MELLANOX_ARBEL
#define PCI_DEVICE_ID_MELLANOX_ARBEL		0x6282
#endif

#ifndef PCI_DEVICE_ID_MELLANOX_HERMON_SDR
#define PCI_DEVICE_ID_MELLANOX_HERMON_SDR	0x6340
#endif

#ifndef PCI_DEVICE_ID_MELLANOX_HERMON_DDR
#define PCI_DEVICE_ID_MELLANOX_HERMON_DDR	0x634a
#endif

#ifndef PCI_DEVICE_ID_MELLANOX_HERMON_QDR
#define PCI_DEVICE_ID_MELLANOX_HERMON_QDR	0x6354
#endif

#ifndef PCI_DEVICE_ID_MELLANOX_HERMON_EN
#define PCI_DEVICE_ID_MELLANOX_HERMON_EN	0x6368
#endif

#ifndef PCI_DEVICE_ID_MELLANOX_CONNECTX_EN
#define PCI_DEVICE_ID_MELLANOX_CONNECTX_EN	0x6372
#endif

#ifndef PCI_DEVICE_ID_MELLANOX_HERMON_DDR_GEN2
#define PCI_DEVICE_ID_MELLANOX_HERMON_DDR_GEN2	0x6732
#endif

#ifndef PCI_DEVICE_ID_MELLANOX_HERMON_QDR_GEN2
#define PCI_DEVICE_ID_MELLANOX_HERMON_QDR_GEN2	0x673c
#endif

#ifndef PCI_DEVICE_ID_MELLANOX_CONNECTX_EN_5_GEN2
#define PCI_DEVICE_ID_MELLANOX_CONNECTX_EN_5_GEN2 0x6746
#endif

#ifndef PCI_DEVICE_ID_MELLANOX_HERMON_EN_GEN2
#define PCI_DEVICE_ID_MELLANOX_HERMON_EN_GEN2	0x6750
#endif

#ifndef PCI_DEVICE_ID_MELLANOX_CONNECTX_EN_T_GEN2
#define PCI_DEVICE_ID_MELLANOX_CONNECTX_EN_T_GEN2 0x675a
#endif

#ifndef PCI_DEVICE_ID_MELLANOX_CONNECTX_EN_GEN2
#define PCI_DEVICE_ID_MELLANOX_CONNECTX_EN_GEN2	0x6764
#endif

#ifndef PCI_DEVICE_ID_MELLANOX_CONNECTX2
#define PCI_DEVICE_ID_MELLANOX_CONNECTX2	0x676e
#endif

#define ROCE_V2_UDP_DPORT      4791

#endif /* LINUX_4_10_COMPAT_H */
