# SPDX-License-Identifier: GPL-2.0
#
# Makefile for Marvell's OcteonTX2 SDP PF driver
#

obj-$(CONFIG_OCTEONTX2_SDP_PF) += octeontx2_sdp.o

octeontx2_sdp-y := sdp.o
ccflags-y += -I$(srctree)/drivers/net/ethernet/marvell/octeontx2/af

