/* SPDX-License-Identifier: GPL-2.0 */

#ifndef BOOT_COMPRESSED_KERNEL_INFO_H
#define BOOT_COMPRESSED_KERNEL_INFO_H

#ifdef CONFIG_X86_64
#define KERNEL_INFO_OFFSET 0x500
#else /* 32-bit */
#define KERNEL_INFO_OFFSET 0x100
#endif

#endif /* BOOT_COMPRESSED_KERNEL_INFO_H */
