#ifndef _BNX2X_COMPAT_UEK3_H_
#define _BNX2X_COMPAT_UEK3_H_

#define _DEFINE_PCI_VFS_ASSIGNED_
#define _DEFINE_PCIE_GET_MIN_LINK_
#define _DEFINE_PHYS_PORT_ID
#define _DEFINE_IFLA_VF_RATE
#define _HAS_HW_TSTAMP
#define _DEFINE_SMP_MB_BEFORE_ATOMIC
#define _DEFINE_LL_RX_POLL
#define _DEFINE_SKB_SET_HASH
#define _HAS_ETHTOOL_TS_INFO
#define _HAS_CLAMP
#define _GETNUMTCS_RETURNS_INT
#define HAS_NDO_FIX_FEATURES
#define _DEFINE_EPROBE_DEFER

#endif /* _BNX2X_COMPAT_UEK3_H_ */
