# SPDX-License-Identifier: GPL-2.0
#
# Makefile for Marvell's OcteonTX2 SDEI/GHES device driver
#

otx2_sdei_ghes-$(CONFIG_OCTEONTX2_GHES_BERT) += otx2-ghes-bert.o
obj-$(CONFIG_OCTEONTX2_EINJ) += otx2-einj.o
