# SPDX-License-Identifier: GPL-2.0
#
# Makefile for Marvell's OcteonTX2 SDEI/GHES device driver
#

obj-$(CONFIG_OCTEONTX2_SDEI_GHES) += otx2_sdei_ghes.o
otx2_sdei_ghes-$(CONFIG_OCTEONTX2_GHES_BERT) += otx2-ghes-bert.o
otx2_sdei_ghes-y += otx2-sdei-ghes.o
