obj-$(CONFIG_PDDF_MULTIFPGAPCI_GPIO) += driver/

TARGET = pddf_multifpgapci_gpio_module
obj-$(CONFIG_PDDF_MULTIFPGAPCI_GPIO) += $(TARGET).o

ccflags-y := -I$(srctree)/drivers/platform/pddf-sonic/include
