# Make rules for configuration files.
#
# $Id$

CFG		= kernel-$(VERSION)

CONFIGFILES	= \
	$(CFG)-i686.config $(CFG)-i686-debug.config \
	$(CFG)-x86_64.config $(CFG)-x86_64-debug.config \
	$(CFG)-i686-paravirt.config $(CFG)-x86_64-paravirt.config \
	$(CFG)-i686-paravirt_debug.config $(CFG)-x86_64-paravirt_debug.config 
	

PLATFORMS	= x86 x86_64 
TEMPFILES	= $(addprefix temp-, $(addsuffix -generic, $(PLATFORMS)))

configs: $(CONFIGFILES)
	@rm -f kernel-*-config
	@rm -f $(TEMPFILES)
	@rm -f temp-generic temp-*-generic temp-*-generic-tmp

# Augment the clean target to clean up our own cruft
clean ::
	@rm -fv $(CONFIGFILES) $(TEMPFILES) temp-generic kernel-$(VERSION)*config

temp-generic: config-generic
	cat config-generic config-nodebug > temp-generic

temp-debug-generic: config-generic
	cat config-generic config-debug > temp-debug-generic

temp-x86-generic: config-x86-generic temp-generic
	perl merge.pl $^  > $@

temp-x86-debug-generic: config-x86-generic temp-debug-generic
	perl merge.pl $^  > $@

temp-x86_64-generic: config-x86_64-generic temp-generic
	perl merge.pl $^  > $@

temp-x86_64-debug-generic: config-x86_64-generic temp-debug-generic
	perl merge.pl $^  > $@

kernel-$(VERSION)-i686.config: config-i686 temp-x86-generic
	perl merge.pl $^ i386 > $@

kernel-$(VERSION)-i686-debug.config: config-i686 temp-x86-debug-generic
	perl merge.pl $^ i386 > $@

kernel-$(VERSION)-x86_64.config: /dev/null temp-x86_64-generic
	perl merge.pl $^ x86_64 > $@

kernel-$(VERSION)-x86_64-debug.config: /dev/null temp-x86_64-debug-generic
	perl merge.pl $^ x86_64 > $@

kernel-$(VERSION)-i686-paravirt.config: config-generic-paravirt kernel-$(VERSION)-i686.config 
	perl merge.pl $^ i386 > $@

kernel-$(VERSION)-i686-paravirt_debug.config: kernel-$(VERSION)-i686-paravirt.config kernel-$(VERSION)-i686-debug.config
	perl merge.pl $^ i386 > $@

kernel-$(VERSION)-x86_64-paravirt.config: config-generic-paravirt kernel-$(VERSION)-x86_64.config 
	perl merge.pl $^ x86_64 > $@

kernel-$(VERSION)-x86_64-paravirt_debug.config: kernel-$(VERSION)-x86_64-paravirt.config kernel-$(VERSION)-x86_64-debug.config
	perl merge.pl $^ x86_64 > $@

