/*****************************************************************
 *
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated by xfc_map_parser
 * from the NPL output file(s) bcm56780_a0_hna_6_5_34_2_0_sf_match_id_info.yml
 * for device bcm56780_a0 and variant hna_6_5_34_2_0.
 * Edits to this file will be lost when it is regenerated.
 *
 *
 * Copyright 2018-2025 Broadcom. All rights reserved.
 * The term 'Broadcom' refers to Broadcom Inc. and/or its subsidiaries.
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License 
 * version 2 as published by the Free Software Foundation.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * A copy of the GNU General Public License version 2 (GPLv2) can
 * be found in the LICENSES folder.
 *
 * Tool Path: $SDK/INTERNAL/fltg/xfc_map_parser
 *
 ****************************************************************/


#include <bcmpkt/bcmpkt_rxpmd_match_id.h>
#include <bcmpkt/xfcr/bcm56780_a0/hna_6_5_34_2_0/bcm56780_a0_hna_6_5_34_2_0_bcmpkt_rxpmd_match_id_defs.h>


static bcmpkt_rxpmd_match_id_db_t
bcm56780_a0_hna_6_5_34_2_0_rxpmd_match_id_db[BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_COUNT] = {
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L2_HDR_ETAG */
        .name         = "EGRESS_PKT_FWD_L2_HDR_ETAG",
        .match        = 0x40,
        .match_mask   = 0x60,
        .match_maxbit = 29,
        .match_minbit = 23,
        .maxbit       = 6,
        .minbit       = 5,
        .value        = 0x2,
        .pmaxbit      = 41,
        .pminbit      = 35,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L2_HDR_ITAG */
        .name         = "EGRESS_PKT_FWD_L2_HDR_ITAG",
        .match        = 0x10,
        .match_mask   = 0x10,
        .match_maxbit = 29,
        .match_minbit = 23,
        .maxbit       = 4,
        .minbit       = 4,
        .value        = 0x1,
        .pmaxbit      = 41,
        .pminbit      = 35,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L2_HDR_L2 */
        .name         = "EGRESS_PKT_FWD_L2_HDR_L2",
        .match        = 0x1,
        .match_mask   = 0x1,
        .match_maxbit = 29,
        .match_minbit = 23,
        .maxbit       = 0,
        .minbit       = 0,
        .value        = 0x1,
        .pmaxbit      = 41,
        .pminbit      = 35,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L2_HDR_NONE */
        .name         = "EGRESS_PKT_FWD_L2_HDR_NONE",
        .match        = 0x0,
        .match_mask   = 0x7f,
        .match_maxbit = 29,
        .match_minbit = 23,
        .maxbit       = 6,
        .minbit       = 0,
        .value        = 0x0,
        .pmaxbit      = 41,
        .pminbit      = 35,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L2_HDR_OTAG */
        .name         = "EGRESS_PKT_FWD_L2_HDR_OTAG",
        .match        = 0x8,
        .match_mask   = 0x8,
        .match_maxbit = 29,
        .match_minbit = 23,
        .maxbit       = 3,
        .minbit       = 3,
        .value        = 0x1,
        .pmaxbit      = 41,
        .pminbit      = 35,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L2_HDR_SNAP_OR_LLC */
        .name         = "EGRESS_PKT_FWD_L2_HDR_SNAP_OR_LLC",
        .match        = 0x2,
        .match_mask   = 0x2,
        .match_maxbit = 29,
        .match_minbit = 23,
        .maxbit       = 1,
        .minbit       = 1,
        .value        = 0x1,
        .pmaxbit      = 41,
        .pminbit      = 35,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L2_HDR_SVTAG */
        .name         = "EGRESS_PKT_FWD_L2_HDR_SVTAG",
        .match        = 0x4,
        .match_mask   = 0x4,
        .match_maxbit = 29,
        .match_minbit = 23,
        .maxbit       = 2,
        .minbit       = 2,
        .value        = 0x1,
        .pmaxbit      = 41,
        .pminbit      = 35,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L2_HDR_VNTAG */
        .name         = "EGRESS_PKT_FWD_L2_HDR_VNTAG",
        .match        = 0x20,
        .match_mask   = 0x60,
        .match_maxbit = 29,
        .match_minbit = 23,
        .maxbit       = 6,
        .minbit       = 5,
        .value        = 0x1,
        .pmaxbit      = 41,
        .pminbit      = 35,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L3_L4_HDR_ARP */
        .name         = "EGRESS_PKT_FWD_L3_L4_HDR_ARP",
        .match        = 0x100,
        .match_mask   = 0x7b0,
        .match_maxbit = 43,
        .match_minbit = 30,
        .maxbit       = 10,
        .minbit       = 8,
        .value        = 0x1,
        .pmaxbit      = 62,
        .pminbit      = 49,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L3_L4_HDR_BFD */
        .name         = "EGRESS_PKT_FWD_L3_L4_HDR_BFD",
        .match        = 0x3800,
        .match_mask   = 0x3800,
        .match_maxbit = 43,
        .match_minbit = 30,
        .maxbit       = 13,
        .minbit       = 11,
        .value        = 0x7,
        .pmaxbit      = 62,
        .pminbit      = 49,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L3_L4_HDR_ESP_EXT */
        .name         = "EGRESS_PKT_FWD_L3_L4_HDR_ESP_EXT",
        .match        = 0x800,
        .match_mask   = 0x380c,
        .match_maxbit = 43,
        .match_minbit = 30,
        .maxbit       = 13,
        .minbit       = 11,
        .value        = 0x1,
        .pmaxbit      = 62,
        .pminbit      = 49,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L3_L4_HDR_ETHERTYPE */
        .name         = "EGRESS_PKT_FWD_L3_L4_HDR_ETHERTYPE",
        .match        = 0x1,
        .match_mask   = 0x1,
        .match_maxbit = 43,
        .match_minbit = 30,
        .maxbit       = 0,
        .minbit       = 0,
        .value        = 0x1,
        .pmaxbit      = 62,
        .pminbit      = 49,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L3_L4_HDR_FRAG_EXT_1 */
        .name         = "EGRESS_PKT_FWD_L3_L4_HDR_FRAG_EXT_1",
        .match        = 0x120,
        .match_mask   = 0x7b0,
        .match_maxbit = 43,
        .match_minbit = 30,
        .maxbit       = 10,
        .minbit       = 8,
        .value        = 0x1,
        .pmaxbit      = 62,
        .pminbit      = 49,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L3_L4_HDR_FRAG_EXT_2 */
        .name         = "EGRESS_PKT_FWD_L3_L4_HDR_FRAG_EXT_2",
        .match        = 0x420,
        .match_mask   = 0x7b0,
        .match_maxbit = 43,
        .match_minbit = 30,
        .maxbit       = 10,
        .minbit       = 8,
        .value        = 0x4,
        .pmaxbit      = 62,
        .pminbit      = 49,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L3_L4_HDR_GPE */
        .name         = "EGRESS_PKT_FWD_L3_L4_HDR_GPE",
        .match        = 0x200c,
        .match_mask   = 0x388c,
        .match_maxbit = 43,
        .match_minbit = 30,
        .maxbit       = 13,
        .minbit       = 11,
        .value        = 0x4,
        .pmaxbit      = 62,
        .pminbit      = 49,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L3_L4_HDR_GRE */
        .name         = "EGRESS_PKT_FWD_L3_L4_HDR_GRE",
        .match        = 0x2,
        .match_mask   = 0x82,
        .match_maxbit = 43,
        .match_minbit = 30,
        .maxbit       = 1,
        .minbit       = 1,
        .value        = 0x1,
        .pmaxbit      = 62,
        .pminbit      = 49,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L3_L4_HDR_GRE_CHKSUM */
        .name         = "EGRESS_PKT_FWD_L3_L4_HDR_GRE_CHKSUM",
        .match        = 0x1800,
        .match_mask   = 0x3800,
        .match_maxbit = 43,
        .match_minbit = 30,
        .maxbit       = 13,
        .minbit       = 11,
        .value        = 0x3,
        .pmaxbit      = 62,
        .pminbit      = 49,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L3_L4_HDR_GRE_KEY */
        .name         = "EGRESS_PKT_FWD_L3_L4_HDR_GRE_KEY",
        .match        = 0x8,
        .match_mask   = 0x8c,
        .match_maxbit = 43,
        .match_minbit = 30,
        .maxbit       = 3,
        .minbit       = 2,
        .value        = 0x2,
        .pmaxbit      = 62,
        .pminbit      = 49,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L3_L4_HDR_GRE_ROUT */
        .name         = "EGRESS_PKT_FWD_L3_L4_HDR_GRE_ROUT",
        .match        = 0x300,
        .match_mask   = 0x780,
        .match_maxbit = 43,
        .match_minbit = 30,
        .maxbit       = 10,
        .minbit       = 8,
        .value        = 0x3,
        .pmaxbit      = 62,
        .pminbit      = 49,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L3_L4_HDR_GRE_SEQ */
        .name         = "EGRESS_PKT_FWD_L3_L4_HDR_GRE_SEQ",
        .match        = 0x40,
        .match_mask   = 0xc0,
        .match_maxbit = 43,
        .match_minbit = 30,
        .maxbit       = 6,
        .minbit       = 6,
        .value        = 0x1,
        .pmaxbit      = 62,
        .pminbit      = 49,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L3_L4_HDR_ICMP */
        .name         = "EGRESS_PKT_FWD_L3_L4_HDR_ICMP",
        .match        = 0x2000,
        .match_mask   = 0x380c,
        .match_maxbit = 43,
        .match_minbit = 30,
        .maxbit       = 13,
        .minbit       = 11,
        .value        = 0x4,
        .pmaxbit      = 62,
        .pminbit      = 49,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L3_L4_HDR_IFA_METADATA */
        .name         = "EGRESS_PKT_FWD_L3_L4_HDR_IFA_METADATA",
        .match        = 0x700,
        .match_mask   = 0x780,
        .match_maxbit = 43,
        .match_minbit = 30,
        .maxbit       = 10,
        .minbit       = 8,
        .value        = 0x7,
        .pmaxbit      = 62,
        .pminbit      = 49,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L3_L4_HDR_IGMP */
        .name         = "EGRESS_PKT_FWD_L3_L4_HDR_IGMP",
        .match        = 0x200,
        .match_mask   = 0x780,
        .match_maxbit = 43,
        .match_minbit = 30,
        .maxbit       = 10,
        .minbit       = 8,
        .value        = 0x2,
        .pmaxbit      = 62,
        .pminbit      = 49,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L3_L4_HDR_IPV4 */
        .name         = "EGRESS_PKT_FWD_L3_L4_HDR_IPV4",
        .match        = 0x10,
        .match_mask   = 0xb0,
        .match_maxbit = 43,
        .match_minbit = 30,
        .maxbit       = 5,
        .minbit       = 4,
        .value        = 0x1,
        .pmaxbit      = 62,
        .pminbit      = 49,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L3_L4_HDR_IPV6 */
        .name         = "EGRESS_PKT_FWD_L3_L4_HDR_IPV6",
        .match        = 0x20,
        .match_mask   = 0xb0,
        .match_maxbit = 43,
        .match_minbit = 30,
        .maxbit       = 5,
        .minbit       = 4,
        .value        = 0x2,
        .pmaxbit      = 62,
        .pminbit      = 49,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L3_L4_HDR_MPLS0 */
        .name         = "EGRESS_PKT_FWD_L3_L4_HDR_MPLS0",
        .match        = 0x80,
        .match_mask   = 0x80,
        .match_maxbit = 43,
        .match_minbit = 30,
        .maxbit       = 7,
        .minbit       = 7,
        .value        = 0x1,
        .pmaxbit      = 62,
        .pminbit      = 49,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L3_L4_HDR_MPLS1 */
        .name         = "EGRESS_PKT_FWD_L3_L4_HDR_MPLS1",
        .match        = 0x82,
        .match_mask   = 0x82,
        .match_maxbit = 43,
        .match_minbit = 30,
        .maxbit       = 1,
        .minbit       = 1,
        .value        = 0x1,
        .pmaxbit      = 62,
        .pminbit      = 49,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L3_L4_HDR_MPLS2 */
        .name         = "EGRESS_PKT_FWD_L3_L4_HDR_MPLS2",
        .match        = 0x84,
        .match_mask   = 0x84,
        .match_maxbit = 43,
        .match_minbit = 30,
        .maxbit       = 2,
        .minbit       = 2,
        .value        = 0x1,
        .pmaxbit      = 62,
        .pminbit      = 49,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L3_L4_HDR_MPLS3 */
        .name         = "EGRESS_PKT_FWD_L3_L4_HDR_MPLS3",
        .match        = 0x88,
        .match_mask   = 0x88,
        .match_maxbit = 43,
        .match_minbit = 30,
        .maxbit       = 3,
        .minbit       = 3,
        .value        = 0x1,
        .pmaxbit      = 62,
        .pminbit      = 49,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L3_L4_HDR_MPLS4 */
        .name         = "EGRESS_PKT_FWD_L3_L4_HDR_MPLS4",
        .match        = 0x90,
        .match_mask   = 0x90,
        .match_maxbit = 43,
        .match_minbit = 30,
        .maxbit       = 4,
        .minbit       = 4,
        .value        = 0x1,
        .pmaxbit      = 62,
        .pminbit      = 49,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L3_L4_HDR_MPLS5 */
        .name         = "EGRESS_PKT_FWD_L3_L4_HDR_MPLS5",
        .match        = 0xa0,
        .match_mask   = 0xa0,
        .match_maxbit = 43,
        .match_minbit = 30,
        .maxbit       = 5,
        .minbit       = 5,
        .value        = 0x1,
        .pmaxbit      = 62,
        .pminbit      = 49,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L3_L4_HDR_MPLS6 */
        .name         = "EGRESS_PKT_FWD_L3_L4_HDR_MPLS6",
        .match        = 0xc0,
        .match_mask   = 0xc0,
        .match_maxbit = 43,
        .match_minbit = 30,
        .maxbit       = 6,
        .minbit       = 6,
        .value        = 0x1,
        .pmaxbit      = 62,
        .pminbit      = 49,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L3_L4_HDR_MPLS_ACH */
        .name         = "EGRESS_PKT_FWD_L3_L4_HDR_MPLS_ACH",
        .match        = 0x180,
        .match_mask   = 0x180,
        .match_maxbit = 43,
        .match_minbit = 30,
        .maxbit       = 8,
        .minbit       = 8,
        .value        = 0x1,
        .pmaxbit      = 62,
        .pminbit      = 49,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L3_L4_HDR_MPLS_CW */
        .name         = "EGRESS_PKT_FWD_L3_L4_HDR_MPLS_CW",
        .match        = 0x280,
        .match_mask   = 0x280,
        .match_maxbit = 43,
        .match_minbit = 30,
        .maxbit       = 9,
        .minbit       = 9,
        .value        = 0x1,
        .pmaxbit      = 62,
        .pminbit      = 49,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L3_L4_HDR_NONE */
        .name         = "EGRESS_PKT_FWD_L3_L4_HDR_NONE",
        .match        = 0x0,
        .match_mask   = 0x3fff,
        .match_maxbit = 43,
        .match_minbit = 30,
        .maxbit       = 13,
        .minbit       = 0,
        .value        = 0x0,
        .pmaxbit      = 62,
        .pminbit      = 49,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L3_L4_HDR_P_1588 */
        .name         = "EGRESS_PKT_FWD_L3_L4_HDR_P_1588",
        .match        = 0x3000,
        .match_mask   = 0x3800,
        .match_maxbit = 43,
        .match_minbit = 30,
        .maxbit       = 13,
        .minbit       = 11,
        .value        = 0x6,
        .pmaxbit      = 62,
        .pminbit      = 49,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L3_L4_HDR_RARP */
        .name         = "EGRESS_PKT_FWD_L3_L4_HDR_RARP",
        .match        = 0x400,
        .match_mask   = 0x7b0,
        .match_maxbit = 43,
        .match_minbit = 30,
        .maxbit       = 10,
        .minbit       = 8,
        .value        = 0x4,
        .pmaxbit      = 62,
        .pminbit      = 49,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L3_L4_HDR_TCP_FIRST_4BYTES */
        .name         = "EGRESS_PKT_FWD_L3_L4_HDR_TCP_FIRST_4BYTES",
        .match        = 0x4,
        .match_mask   = 0x8c,
        .match_maxbit = 43,
        .match_minbit = 30,
        .maxbit       = 3,
        .minbit       = 2,
        .value        = 0x1,
        .pmaxbit      = 62,
        .pminbit      = 49,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L3_L4_HDR_TCP_LAST_16BYTES */
        .name         = "EGRESS_PKT_FWD_L3_L4_HDR_TCP_LAST_16BYTES",
        .match        = 0x804,
        .match_mask   = 0x388c,
        .match_maxbit = 43,
        .match_minbit = 30,
        .maxbit       = 13,
        .minbit       = 11,
        .value        = 0x1,
        .pmaxbit      = 62,
        .pminbit      = 49,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L3_L4_HDR_UDP */
        .name         = "EGRESS_PKT_FWD_L3_L4_HDR_UDP",
        .match        = 0xc,
        .match_mask   = 0x8c,
        .match_maxbit = 43,
        .match_minbit = 30,
        .maxbit       = 3,
        .minbit       = 2,
        .value        = 0x3,
        .pmaxbit      = 62,
        .pminbit      = 49,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L3_L4_HDR_UDPIPSEC */
        .name         = "EGRESS_PKT_FWD_L3_L4_HDR_UDPIPSEC",
        .match        = 0x600,
        .match_mask   = 0x780,
        .match_maxbit = 43,
        .match_minbit = 30,
        .maxbit       = 10,
        .minbit       = 8,
        .value        = 0x6,
        .pmaxbit      = 62,
        .pminbit      = 49,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L3_L4_HDR_UNKNOWN_L3 */
        .name         = "EGRESS_PKT_FWD_L3_L4_HDR_UNKNOWN_L3",
        .match        = 0x500,
        .match_mask   = 0x780,
        .match_maxbit = 43,
        .match_minbit = 30,
        .maxbit       = 10,
        .minbit       = 8,
        .value        = 0x5,
        .pmaxbit      = 62,
        .pminbit      = 49,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L3_L4_HDR_UNKNOWN_L4 */
        .name         = "EGRESS_PKT_FWD_L3_L4_HDR_UNKNOWN_L4",
        .match        = 0x2800,
        .match_mask   = 0x380c,
        .match_maxbit = 43,
        .match_minbit = 30,
        .maxbit       = 13,
        .minbit       = 11,
        .value        = 0x5,
        .pmaxbit      = 62,
        .pminbit      = 49,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L3_L4_HDR_UNKNOWN_L5 */
        .name         = "EGRESS_PKT_FWD_L3_L4_HDR_UNKNOWN_L5",
        .match        = 0x280c,
        .match_mask   = 0x388c,
        .match_maxbit = 43,
        .match_minbit = 30,
        .maxbit       = 13,
        .minbit       = 11,
        .value        = 0x5,
        .pmaxbit      = 62,
        .pminbit      = 49,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L3_L4_HDR_VXLAN */
        .name         = "EGRESS_PKT_FWD_L3_L4_HDR_VXLAN",
        .match        = 0x1000,
        .match_mask   = 0x3800,
        .match_maxbit = 43,
        .match_minbit = 30,
        .maxbit       = 13,
        .minbit       = 11,
        .value        = 0x2,
        .pmaxbit      = 62,
        .pminbit      = 49,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_SYS_HDR_EP_NIH */
        .name         = "EGRESS_PKT_SYS_HDR_EP_NIH",
        .match        = 0x2,
        .match_mask   = 0x3,
        .match_maxbit = 1,
        .match_minbit = 0,
        .maxbit       = 1,
        .minbit       = 0,
        .value        = 0x2,
        .pmaxbit      = 1,
        .pminbit      = 0,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_SYS_HDR_LOOPBACK */
        .name         = "EGRESS_PKT_SYS_HDR_LOOPBACK",
        .match        = 0x1,
        .match_mask   = 0x3,
        .match_maxbit = 1,
        .match_minbit = 0,
        .maxbit       = 1,
        .minbit       = 0,
        .value        = 0x1,
        .pmaxbit      = 1,
        .pminbit      = 0,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_SYS_HDR_NONE */
        .name         = "EGRESS_PKT_SYS_HDR_NONE",
        .match        = 0x0,
        .match_mask   = 0x3,
        .match_maxbit = 1,
        .match_minbit = 0,
        .maxbit       = 1,
        .minbit       = 0,
        .value        = 0x0,
        .pmaxbit      = 1,
        .pminbit      = 0,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L2_HDR_ETAG */
        .name         = "EGRESS_PKT_TUNNEL_L2_HDR_ETAG",
        .match        = 0x40,
        .match_mask   = 0x60,
        .match_maxbit = 8,
        .match_minbit = 2,
        .maxbit       = 6,
        .minbit       = 5,
        .value        = 0x2,
        .pmaxbit      = 13,
        .pminbit      = 7,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L2_HDR_ITAG */
        .name         = "EGRESS_PKT_TUNNEL_L2_HDR_ITAG",
        .match        = 0x10,
        .match_mask   = 0x10,
        .match_maxbit = 8,
        .match_minbit = 2,
        .maxbit       = 4,
        .minbit       = 4,
        .value        = 0x1,
        .pmaxbit      = 13,
        .pminbit      = 7,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L2_HDR_L2 */
        .name         = "EGRESS_PKT_TUNNEL_L2_HDR_L2",
        .match        = 0x1,
        .match_mask   = 0x1,
        .match_maxbit = 8,
        .match_minbit = 2,
        .maxbit       = 0,
        .minbit       = 0,
        .value        = 0x1,
        .pmaxbit      = 13,
        .pminbit      = 7,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L2_HDR_NONE */
        .name         = "EGRESS_PKT_TUNNEL_L2_HDR_NONE",
        .match        = 0x0,
        .match_mask   = 0x7f,
        .match_maxbit = 8,
        .match_minbit = 2,
        .maxbit       = 6,
        .minbit       = 0,
        .value        = 0x0,
        .pmaxbit      = 13,
        .pminbit      = 7,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L2_HDR_OTAG */
        .name         = "EGRESS_PKT_TUNNEL_L2_HDR_OTAG",
        .match        = 0x8,
        .match_mask   = 0x8,
        .match_maxbit = 8,
        .match_minbit = 2,
        .maxbit       = 3,
        .minbit       = 3,
        .value        = 0x1,
        .pmaxbit      = 13,
        .pminbit      = 7,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L2_HDR_SNAP_OR_LLC */
        .name         = "EGRESS_PKT_TUNNEL_L2_HDR_SNAP_OR_LLC",
        .match        = 0x2,
        .match_mask   = 0x2,
        .match_maxbit = 8,
        .match_minbit = 2,
        .maxbit       = 1,
        .minbit       = 1,
        .value        = 0x1,
        .pmaxbit      = 13,
        .pminbit      = 7,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L2_HDR_SVTAG */
        .name         = "EGRESS_PKT_TUNNEL_L2_HDR_SVTAG",
        .match        = 0x4,
        .match_mask   = 0x4,
        .match_maxbit = 8,
        .match_minbit = 2,
        .maxbit       = 2,
        .minbit       = 2,
        .value        = 0x1,
        .pmaxbit      = 13,
        .pminbit      = 7,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L2_HDR_VNTAG */
        .name         = "EGRESS_PKT_TUNNEL_L2_HDR_VNTAG",
        .match        = 0x20,
        .match_mask   = 0x60,
        .match_maxbit = 8,
        .match_minbit = 2,
        .maxbit       = 6,
        .minbit       = 5,
        .value        = 0x1,
        .pmaxbit      = 13,
        .pminbit      = 7,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L3_L4_HDR_ARP */
        .name         = "EGRESS_PKT_TUNNEL_L3_L4_HDR_ARP",
        .match        = 0x100,
        .match_mask   = 0x7b0,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 10,
        .minbit       = 8,
        .value        = 0x1,
        .pmaxbit      = 34,
        .pminbit      = 21,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L3_L4_HDR_BFD */
        .name         = "EGRESS_PKT_TUNNEL_L3_L4_HDR_BFD",
        .match        = 0x3800,
        .match_mask   = 0x3800,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 13,
        .minbit       = 11,
        .value        = 0x7,
        .pmaxbit      = 34,
        .pminbit      = 21,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L3_L4_HDR_ESP_EXT */
        .name         = "EGRESS_PKT_TUNNEL_L3_L4_HDR_ESP_EXT",
        .match        = 0x800,
        .match_mask   = 0x380c,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 13,
        .minbit       = 11,
        .value        = 0x1,
        .pmaxbit      = 34,
        .pminbit      = 21,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L3_L4_HDR_ETHERTYPE */
        .name         = "EGRESS_PKT_TUNNEL_L3_L4_HDR_ETHERTYPE",
        .match        = 0x1,
        .match_mask   = 0x1,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 0,
        .minbit       = 0,
        .value        = 0x1,
        .pmaxbit      = 34,
        .pminbit      = 21,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L3_L4_HDR_FRAG_EXT_1 */
        .name         = "EGRESS_PKT_TUNNEL_L3_L4_HDR_FRAG_EXT_1",
        .match        = 0x120,
        .match_mask   = 0x7b0,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 10,
        .minbit       = 8,
        .value        = 0x1,
        .pmaxbit      = 34,
        .pminbit      = 21,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L3_L4_HDR_FRAG_EXT_2 */
        .name         = "EGRESS_PKT_TUNNEL_L3_L4_HDR_FRAG_EXT_2",
        .match        = 0x420,
        .match_mask   = 0x7b0,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 10,
        .minbit       = 8,
        .value        = 0x4,
        .pmaxbit      = 34,
        .pminbit      = 21,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L3_L4_HDR_GPE */
        .name         = "EGRESS_PKT_TUNNEL_L3_L4_HDR_GPE",
        .match        = 0x200c,
        .match_mask   = 0x388c,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 13,
        .minbit       = 11,
        .value        = 0x4,
        .pmaxbit      = 34,
        .pminbit      = 21,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L3_L4_HDR_GRE */
        .name         = "EGRESS_PKT_TUNNEL_L3_L4_HDR_GRE",
        .match        = 0x2,
        .match_mask   = 0x82,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 1,
        .minbit       = 1,
        .value        = 0x1,
        .pmaxbit      = 34,
        .pminbit      = 21,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L3_L4_HDR_GRE_CHKSUM */
        .name         = "EGRESS_PKT_TUNNEL_L3_L4_HDR_GRE_CHKSUM",
        .match        = 0x1800,
        .match_mask   = 0x3800,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 13,
        .minbit       = 11,
        .value        = 0x3,
        .pmaxbit      = 34,
        .pminbit      = 21,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L3_L4_HDR_GRE_KEY */
        .name         = "EGRESS_PKT_TUNNEL_L3_L4_HDR_GRE_KEY",
        .match        = 0x8,
        .match_mask   = 0x8c,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 3,
        .minbit       = 2,
        .value        = 0x2,
        .pmaxbit      = 34,
        .pminbit      = 21,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L3_L4_HDR_GRE_ROUT */
        .name         = "EGRESS_PKT_TUNNEL_L3_L4_HDR_GRE_ROUT",
        .match        = 0x300,
        .match_mask   = 0x780,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 10,
        .minbit       = 8,
        .value        = 0x3,
        .pmaxbit      = 34,
        .pminbit      = 21,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L3_L4_HDR_GRE_SEQ */
        .name         = "EGRESS_PKT_TUNNEL_L3_L4_HDR_GRE_SEQ",
        .match        = 0x40,
        .match_mask   = 0xc0,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 6,
        .minbit       = 6,
        .value        = 0x1,
        .pmaxbit      = 34,
        .pminbit      = 21,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L3_L4_HDR_ICMP */
        .name         = "EGRESS_PKT_TUNNEL_L3_L4_HDR_ICMP",
        .match        = 0x2000,
        .match_mask   = 0x380c,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 13,
        .minbit       = 11,
        .value        = 0x4,
        .pmaxbit      = 34,
        .pminbit      = 21,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L3_L4_HDR_IFA_METADATA */
        .name         = "EGRESS_PKT_TUNNEL_L3_L4_HDR_IFA_METADATA",
        .match        = 0x700,
        .match_mask   = 0x780,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 10,
        .minbit       = 8,
        .value        = 0x7,
        .pmaxbit      = 34,
        .pminbit      = 21,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L3_L4_HDR_IGMP */
        .name         = "EGRESS_PKT_TUNNEL_L3_L4_HDR_IGMP",
        .match        = 0x200,
        .match_mask   = 0x780,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 10,
        .minbit       = 8,
        .value        = 0x2,
        .pmaxbit      = 34,
        .pminbit      = 21,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L3_L4_HDR_IPV4 */
        .name         = "EGRESS_PKT_TUNNEL_L3_L4_HDR_IPV4",
        .match        = 0x10,
        .match_mask   = 0xb0,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 5,
        .minbit       = 4,
        .value        = 0x1,
        .pmaxbit      = 34,
        .pminbit      = 21,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L3_L4_HDR_IPV6 */
        .name         = "EGRESS_PKT_TUNNEL_L3_L4_HDR_IPV6",
        .match        = 0x20,
        .match_mask   = 0xb0,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 5,
        .minbit       = 4,
        .value        = 0x2,
        .pmaxbit      = 34,
        .pminbit      = 21,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L3_L4_HDR_MPLS0 */
        .name         = "EGRESS_PKT_TUNNEL_L3_L4_HDR_MPLS0",
        .match        = 0x80,
        .match_mask   = 0x80,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 7,
        .minbit       = 7,
        .value        = 0x1,
        .pmaxbit      = 34,
        .pminbit      = 21,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L3_L4_HDR_MPLS1 */
        .name         = "EGRESS_PKT_TUNNEL_L3_L4_HDR_MPLS1",
        .match        = 0x82,
        .match_mask   = 0x82,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 1,
        .minbit       = 1,
        .value        = 0x1,
        .pmaxbit      = 34,
        .pminbit      = 21,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L3_L4_HDR_MPLS2 */
        .name         = "EGRESS_PKT_TUNNEL_L3_L4_HDR_MPLS2",
        .match        = 0x84,
        .match_mask   = 0x84,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 2,
        .minbit       = 2,
        .value        = 0x1,
        .pmaxbit      = 34,
        .pminbit      = 21,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L3_L4_HDR_MPLS3 */
        .name         = "EGRESS_PKT_TUNNEL_L3_L4_HDR_MPLS3",
        .match        = 0x88,
        .match_mask   = 0x88,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 3,
        .minbit       = 3,
        .value        = 0x1,
        .pmaxbit      = 34,
        .pminbit      = 21,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L3_L4_HDR_MPLS4 */
        .name         = "EGRESS_PKT_TUNNEL_L3_L4_HDR_MPLS4",
        .match        = 0x90,
        .match_mask   = 0x90,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 4,
        .minbit       = 4,
        .value        = 0x1,
        .pmaxbit      = 34,
        .pminbit      = 21,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L3_L4_HDR_MPLS5 */
        .name         = "EGRESS_PKT_TUNNEL_L3_L4_HDR_MPLS5",
        .match        = 0xa0,
        .match_mask   = 0xa0,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 5,
        .minbit       = 5,
        .value        = 0x1,
        .pmaxbit      = 34,
        .pminbit      = 21,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L3_L4_HDR_MPLS6 */
        .name         = "EGRESS_PKT_TUNNEL_L3_L4_HDR_MPLS6",
        .match        = 0xc0,
        .match_mask   = 0xc0,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 6,
        .minbit       = 6,
        .value        = 0x1,
        .pmaxbit      = 34,
        .pminbit      = 21,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L3_L4_HDR_MPLS_ACH */
        .name         = "EGRESS_PKT_TUNNEL_L3_L4_HDR_MPLS_ACH",
        .match        = 0x180,
        .match_mask   = 0x180,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 8,
        .minbit       = 8,
        .value        = 0x1,
        .pmaxbit      = 34,
        .pminbit      = 21,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L3_L4_HDR_MPLS_CW */
        .name         = "EGRESS_PKT_TUNNEL_L3_L4_HDR_MPLS_CW",
        .match        = 0x280,
        .match_mask   = 0x280,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 9,
        .minbit       = 9,
        .value        = 0x1,
        .pmaxbit      = 34,
        .pminbit      = 21,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L3_L4_HDR_NONE */
        .name         = "EGRESS_PKT_TUNNEL_L3_L4_HDR_NONE",
        .match        = 0x0,
        .match_mask   = 0x3fff,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 13,
        .minbit       = 0,
        .value        = 0x0,
        .pmaxbit      = 34,
        .pminbit      = 21,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L3_L4_HDR_P_1588 */
        .name         = "EGRESS_PKT_TUNNEL_L3_L4_HDR_P_1588",
        .match        = 0x3000,
        .match_mask   = 0x3800,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 13,
        .minbit       = 11,
        .value        = 0x6,
        .pmaxbit      = 34,
        .pminbit      = 21,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L3_L4_HDR_RARP */
        .name         = "EGRESS_PKT_TUNNEL_L3_L4_HDR_RARP",
        .match        = 0x400,
        .match_mask   = 0x7b0,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 10,
        .minbit       = 8,
        .value        = 0x4,
        .pmaxbit      = 34,
        .pminbit      = 21,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L3_L4_HDR_TCP_FIRST_4BYTES */
        .name         = "EGRESS_PKT_TUNNEL_L3_L4_HDR_TCP_FIRST_4BYTES",
        .match        = 0x4,
        .match_mask   = 0x8c,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 3,
        .minbit       = 2,
        .value        = 0x1,
        .pmaxbit      = 34,
        .pminbit      = 21,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L3_L4_HDR_TCP_LAST_16BYTES */
        .name         = "EGRESS_PKT_TUNNEL_L3_L4_HDR_TCP_LAST_16BYTES",
        .match        = 0x804,
        .match_mask   = 0x388c,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 13,
        .minbit       = 11,
        .value        = 0x1,
        .pmaxbit      = 34,
        .pminbit      = 21,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L3_L4_HDR_UDP */
        .name         = "EGRESS_PKT_TUNNEL_L3_L4_HDR_UDP",
        .match        = 0xc,
        .match_mask   = 0x8c,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 3,
        .minbit       = 2,
        .value        = 0x3,
        .pmaxbit      = 34,
        .pminbit      = 21,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L3_L4_HDR_UDPIPSEC */
        .name         = "EGRESS_PKT_TUNNEL_L3_L4_HDR_UDPIPSEC",
        .match        = 0x600,
        .match_mask   = 0x780,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 10,
        .minbit       = 8,
        .value        = 0x6,
        .pmaxbit      = 34,
        .pminbit      = 21,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L3_L4_HDR_UNKNOWN_L3 */
        .name         = "EGRESS_PKT_TUNNEL_L3_L4_HDR_UNKNOWN_L3",
        .match        = 0x500,
        .match_mask   = 0x780,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 10,
        .minbit       = 8,
        .value        = 0x5,
        .pmaxbit      = 34,
        .pminbit      = 21,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L3_L4_HDR_UNKNOWN_L4 */
        .name         = "EGRESS_PKT_TUNNEL_L3_L4_HDR_UNKNOWN_L4",
        .match        = 0x2800,
        .match_mask   = 0x380c,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 13,
        .minbit       = 11,
        .value        = 0x5,
        .pmaxbit      = 34,
        .pminbit      = 21,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L3_L4_HDR_UNKNOWN_L5 */
        .name         = "EGRESS_PKT_TUNNEL_L3_L4_HDR_UNKNOWN_L5",
        .match        = 0x280c,
        .match_mask   = 0x388c,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 13,
        .minbit       = 11,
        .value        = 0x5,
        .pmaxbit      = 34,
        .pminbit      = 21,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L3_L4_HDR_VXLAN */
        .name         = "EGRESS_PKT_TUNNEL_L3_L4_HDR_VXLAN",
        .match        = 0x1000,
        .match_mask   = 0x3800,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 13,
        .minbit       = 11,
        .value        = 0x2,
        .pmaxbit      = 34,
        .pminbit      = 21,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_INNER_L2_HDR_ETAG */
        .name         = "INGRESS_PKT_INNER_L2_HDR_ETAG",
        .match        = 0x40,
        .match_mask   = 0x60,
        .match_maxbit = 29,
        .match_minbit = 23,
        .maxbit       = 6,
        .minbit       = 5,
        .value        = 0x2,
        .pmaxbit      = 29,
        .pminbit      = 23,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_INNER_L2_HDR_ITAG */
        .name         = "INGRESS_PKT_INNER_L2_HDR_ITAG",
        .match        = 0x10,
        .match_mask   = 0x10,
        .match_maxbit = 29,
        .match_minbit = 23,
        .maxbit       = 4,
        .minbit       = 4,
        .value        = 0x1,
        .pmaxbit      = 29,
        .pminbit      = 23,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_INNER_L2_HDR_L2 */
        .name         = "INGRESS_PKT_INNER_L2_HDR_L2",
        .match        = 0x1,
        .match_mask   = 0x1,
        .match_maxbit = 29,
        .match_minbit = 23,
        .maxbit       = 0,
        .minbit       = 0,
        .value        = 0x1,
        .pmaxbit      = 29,
        .pminbit      = 23,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_INNER_L2_HDR_NONE */
        .name         = "INGRESS_PKT_INNER_L2_HDR_NONE",
        .match        = 0x0,
        .match_mask   = 0x7f,
        .match_maxbit = 29,
        .match_minbit = 23,
        .maxbit       = 6,
        .minbit       = 0,
        .value        = 0x0,
        .pmaxbit      = 29,
        .pminbit      = 23,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_INNER_L2_HDR_OTAG */
        .name         = "INGRESS_PKT_INNER_L2_HDR_OTAG",
        .match        = 0x8,
        .match_mask   = 0x8,
        .match_maxbit = 29,
        .match_minbit = 23,
        .maxbit       = 3,
        .minbit       = 3,
        .value        = 0x1,
        .pmaxbit      = 29,
        .pminbit      = 23,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_INNER_L2_HDR_SNAP_OR_LLC */
        .name         = "INGRESS_PKT_INNER_L2_HDR_SNAP_OR_LLC",
        .match        = 0x2,
        .match_mask   = 0x2,
        .match_maxbit = 29,
        .match_minbit = 23,
        .maxbit       = 1,
        .minbit       = 1,
        .value        = 0x1,
        .pmaxbit      = 29,
        .pminbit      = 23,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_INNER_L2_HDR_VNTAG */
        .name         = "INGRESS_PKT_INNER_L2_HDR_VNTAG",
        .match        = 0x20,
        .match_mask   = 0x60,
        .match_maxbit = 29,
        .match_minbit = 23,
        .maxbit       = 6,
        .minbit       = 5,
        .value        = 0x1,
        .pmaxbit      = 29,
        .pminbit      = 23,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_INNER_L3_L4_HDR_ARP */
        .name         = "INGRESS_PKT_INNER_L3_L4_HDR_ARP",
        .match        = 0x100,
        .match_mask   = 0x7b0,
        .match_maxbit = 43,
        .match_minbit = 30,
        .maxbit       = 10,
        .minbit       = 8,
        .value        = 0x1,
        .pmaxbit      = 43,
        .pminbit      = 30,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_INNER_L3_L4_HDR_BFD */
        .name         = "INGRESS_PKT_INNER_L3_L4_HDR_BFD",
        .match        = 0x3800,
        .match_mask   = 0x3800,
        .match_maxbit = 43,
        .match_minbit = 30,
        .maxbit       = 13,
        .minbit       = 11,
        .value        = 0x7,
        .pmaxbit      = 43,
        .pminbit      = 30,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_INNER_L3_L4_HDR_ESP_EXT */
        .name         = "INGRESS_PKT_INNER_L3_L4_HDR_ESP_EXT",
        .match        = 0x800,
        .match_mask   = 0x380c,
        .match_maxbit = 43,
        .match_minbit = 30,
        .maxbit       = 13,
        .minbit       = 11,
        .value        = 0x1,
        .pmaxbit      = 43,
        .pminbit      = 30,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_INNER_L3_L4_HDR_ETHERTYPE */
        .name         = "INGRESS_PKT_INNER_L3_L4_HDR_ETHERTYPE",
        .match        = 0x1,
        .match_mask   = 0x1,
        .match_maxbit = 43,
        .match_minbit = 30,
        .maxbit       = 0,
        .minbit       = 0,
        .value        = 0x1,
        .pmaxbit      = 43,
        .pminbit      = 30,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_INNER_L3_L4_HDR_FRAG_EXT_1 */
        .name         = "INGRESS_PKT_INNER_L3_L4_HDR_FRAG_EXT_1",
        .match        = 0x120,
        .match_mask   = 0x7b0,
        .match_maxbit = 43,
        .match_minbit = 30,
        .maxbit       = 10,
        .minbit       = 8,
        .value        = 0x1,
        .pmaxbit      = 43,
        .pminbit      = 30,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_INNER_L3_L4_HDR_FRAG_EXT_2 */
        .name         = "INGRESS_PKT_INNER_L3_L4_HDR_FRAG_EXT_2",
        .match        = 0x420,
        .match_mask   = 0x7b0,
        .match_maxbit = 43,
        .match_minbit = 30,
        .maxbit       = 10,
        .minbit       = 8,
        .value        = 0x4,
        .pmaxbit      = 43,
        .pminbit      = 30,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_INNER_L3_L4_HDR_ICMP */
        .name         = "INGRESS_PKT_INNER_L3_L4_HDR_ICMP",
        .match        = 0x2000,
        .match_mask   = 0x380c,
        .match_maxbit = 43,
        .match_minbit = 30,
        .maxbit       = 13,
        .minbit       = 11,
        .value        = 0x4,
        .pmaxbit      = 43,
        .pminbit      = 30,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_INNER_L3_L4_HDR_IFA_METADATA */
        .name         = "INGRESS_PKT_INNER_L3_L4_HDR_IFA_METADATA",
        .match        = 0x700,
        .match_mask   = 0x780,
        .match_maxbit = 43,
        .match_minbit = 30,
        .maxbit       = 10,
        .minbit       = 8,
        .value        = 0x7,
        .pmaxbit      = 43,
        .pminbit      = 30,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_INNER_L3_L4_HDR_IGMP */
        .name         = "INGRESS_PKT_INNER_L3_L4_HDR_IGMP",
        .match        = 0x200,
        .match_mask   = 0x780,
        .match_maxbit = 43,
        .match_minbit = 30,
        .maxbit       = 10,
        .minbit       = 8,
        .value        = 0x2,
        .pmaxbit      = 43,
        .pminbit      = 30,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_INNER_L3_L4_HDR_IPV4 */
        .name         = "INGRESS_PKT_INNER_L3_L4_HDR_IPV4",
        .match        = 0x10,
        .match_mask   = 0xb0,
        .match_maxbit = 43,
        .match_minbit = 30,
        .maxbit       = 5,
        .minbit       = 4,
        .value        = 0x1,
        .pmaxbit      = 43,
        .pminbit      = 30,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_INNER_L3_L4_HDR_IPV6 */
        .name         = "INGRESS_PKT_INNER_L3_L4_HDR_IPV6",
        .match        = 0x20,
        .match_mask   = 0xb0,
        .match_maxbit = 43,
        .match_minbit = 30,
        .maxbit       = 5,
        .minbit       = 4,
        .value        = 0x2,
        .pmaxbit      = 43,
        .pminbit      = 30,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_INNER_L3_L4_HDR_NONE */
        .name         = "INGRESS_PKT_INNER_L3_L4_HDR_NONE",
        .match        = 0x0,
        .match_mask   = 0x3fff,
        .match_maxbit = 43,
        .match_minbit = 30,
        .maxbit       = 13,
        .minbit       = 0,
        .value        = 0x0,
        .pmaxbit      = 43,
        .pminbit      = 30,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_INNER_L3_L4_HDR_P_1588 */
        .name         = "INGRESS_PKT_INNER_L3_L4_HDR_P_1588",
        .match        = 0x3000,
        .match_mask   = 0x3800,
        .match_maxbit = 43,
        .match_minbit = 30,
        .maxbit       = 13,
        .minbit       = 11,
        .value        = 0x6,
        .pmaxbit      = 43,
        .pminbit      = 30,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_INNER_L3_L4_HDR_RARP */
        .name         = "INGRESS_PKT_INNER_L3_L4_HDR_RARP",
        .match        = 0x400,
        .match_mask   = 0x7b0,
        .match_maxbit = 43,
        .match_minbit = 30,
        .maxbit       = 10,
        .minbit       = 8,
        .value        = 0x4,
        .pmaxbit      = 43,
        .pminbit      = 30,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_INNER_L3_L4_HDR_TCP_FIRST_4BYTES */
        .name         = "INGRESS_PKT_INNER_L3_L4_HDR_TCP_FIRST_4BYTES",
        .match        = 0x4,
        .match_mask   = 0x8c,
        .match_maxbit = 43,
        .match_minbit = 30,
        .maxbit       = 3,
        .minbit       = 2,
        .value        = 0x1,
        .pmaxbit      = 43,
        .pminbit      = 30,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_INNER_L3_L4_HDR_TCP_LAST_16BYTES */
        .name         = "INGRESS_PKT_INNER_L3_L4_HDR_TCP_LAST_16BYTES",
        .match        = 0x804,
        .match_mask   = 0x388c,
        .match_maxbit = 43,
        .match_minbit = 30,
        .maxbit       = 13,
        .minbit       = 11,
        .value        = 0x1,
        .pmaxbit      = 43,
        .pminbit      = 30,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_INNER_L3_L4_HDR_UDP */
        .name         = "INGRESS_PKT_INNER_L3_L4_HDR_UDP",
        .match        = 0xc,
        .match_mask   = 0x8c,
        .match_maxbit = 43,
        .match_minbit = 30,
        .maxbit       = 3,
        .minbit       = 2,
        .value        = 0x3,
        .pmaxbit      = 43,
        .pminbit      = 30,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_INNER_L3_L4_HDR_UNKNOWN_L3 */
        .name         = "INGRESS_PKT_INNER_L3_L4_HDR_UNKNOWN_L3",
        .match        = 0x500,
        .match_mask   = 0x780,
        .match_maxbit = 43,
        .match_minbit = 30,
        .maxbit       = 10,
        .minbit       = 8,
        .value        = 0x5,
        .pmaxbit      = 43,
        .pminbit      = 30,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_INNER_L3_L4_HDR_UNKNOWN_L4 */
        .name         = "INGRESS_PKT_INNER_L3_L4_HDR_UNKNOWN_L4",
        .match        = 0x2800,
        .match_mask   = 0x380c,
        .match_maxbit = 43,
        .match_minbit = 30,
        .maxbit       = 13,
        .minbit       = 11,
        .value        = 0x5,
        .pmaxbit      = 43,
        .pminbit      = 30,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_INNER_L3_L4_HDR_UNKNOWN_L5 */
        .name         = "INGRESS_PKT_INNER_L3_L4_HDR_UNKNOWN_L5",
        .match        = 0x280c,
        .match_mask   = 0x388c,
        .match_maxbit = 43,
        .match_minbit = 30,
        .maxbit       = 13,
        .minbit       = 11,
        .value        = 0x5,
        .pmaxbit      = 43,
        .pminbit      = 30,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L2_HDR_ETAG */
        .name         = "INGRESS_PKT_OUTER_L2_HDR_ETAG",
        .match        = 0x40,
        .match_mask   = 0x60,
        .match_maxbit = 8,
        .match_minbit = 2,
        .maxbit       = 6,
        .minbit       = 5,
        .value        = 0x2,
        .pmaxbit      = 8,
        .pminbit      = 2,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L2_HDR_ITAG */
        .name         = "INGRESS_PKT_OUTER_L2_HDR_ITAG",
        .match        = 0x10,
        .match_mask   = 0x10,
        .match_maxbit = 8,
        .match_minbit = 2,
        .maxbit       = 4,
        .minbit       = 4,
        .value        = 0x1,
        .pmaxbit      = 8,
        .pminbit      = 2,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L2_HDR_L2 */
        .name         = "INGRESS_PKT_OUTER_L2_HDR_L2",
        .match        = 0x1,
        .match_mask   = 0x1,
        .match_maxbit = 8,
        .match_minbit = 2,
        .maxbit       = 0,
        .minbit       = 0,
        .value        = 0x1,
        .pmaxbit      = 8,
        .pminbit      = 2,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L2_HDR_NONE */
        .name         = "INGRESS_PKT_OUTER_L2_HDR_NONE",
        .match        = 0x0,
        .match_mask   = 0x7f,
        .match_maxbit = 8,
        .match_minbit = 2,
        .maxbit       = 6,
        .minbit       = 0,
        .value        = 0x0,
        .pmaxbit      = 8,
        .pminbit      = 2,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L2_HDR_OTAG */
        .name         = "INGRESS_PKT_OUTER_L2_HDR_OTAG",
        .match        = 0x8,
        .match_mask   = 0x8,
        .match_maxbit = 8,
        .match_minbit = 2,
        .maxbit       = 3,
        .minbit       = 3,
        .value        = 0x1,
        .pmaxbit      = 8,
        .pminbit      = 2,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L2_HDR_SNAP_OR_LLC */
        .name         = "INGRESS_PKT_OUTER_L2_HDR_SNAP_OR_LLC",
        .match        = 0x2,
        .match_mask   = 0x2,
        .match_maxbit = 8,
        .match_minbit = 2,
        .maxbit       = 1,
        .minbit       = 1,
        .value        = 0x1,
        .pmaxbit      = 8,
        .pminbit      = 2,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L2_HDR_SVTAG */
        .name         = "INGRESS_PKT_OUTER_L2_HDR_SVTAG",
        .match        = 0x4,
        .match_mask   = 0x4,
        .match_maxbit = 8,
        .match_minbit = 2,
        .maxbit       = 2,
        .minbit       = 2,
        .value        = 0x1,
        .pmaxbit      = 8,
        .pminbit      = 2,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L2_HDR_VNTAG */
        .name         = "INGRESS_PKT_OUTER_L2_HDR_VNTAG",
        .match        = 0x20,
        .match_mask   = 0x60,
        .match_maxbit = 8,
        .match_minbit = 2,
        .maxbit       = 6,
        .minbit       = 5,
        .value        = 0x1,
        .pmaxbit      = 8,
        .pminbit      = 2,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L3_L4_HDR_ARP */
        .name         = "INGRESS_PKT_OUTER_L3_L4_HDR_ARP",
        .match        = 0x100,
        .match_mask   = 0x7b0,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 10,
        .minbit       = 8,
        .value        = 0x1,
        .pmaxbit      = 22,
        .pminbit      = 9,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L3_L4_HDR_BFD */
        .name         = "INGRESS_PKT_OUTER_L3_L4_HDR_BFD",
        .match        = 0x3800,
        .match_mask   = 0x3800,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 13,
        .minbit       = 11,
        .value        = 0x7,
        .pmaxbit      = 22,
        .pminbit      = 9,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L3_L4_HDR_ESP_EXT */
        .name         = "INGRESS_PKT_OUTER_L3_L4_HDR_ESP_EXT",
        .match        = 0x800,
        .match_mask   = 0x380c,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 13,
        .minbit       = 11,
        .value        = 0x1,
        .pmaxbit      = 22,
        .pminbit      = 9,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L3_L4_HDR_ETHERTYPE */
        .name         = "INGRESS_PKT_OUTER_L3_L4_HDR_ETHERTYPE",
        .match        = 0x1,
        .match_mask   = 0x1,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 0,
        .minbit       = 0,
        .value        = 0x1,
        .pmaxbit      = 22,
        .pminbit      = 9,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L3_L4_HDR_FRAG_EXT_1 */
        .name         = "INGRESS_PKT_OUTER_L3_L4_HDR_FRAG_EXT_1",
        .match        = 0x120,
        .match_mask   = 0x7b0,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 10,
        .minbit       = 8,
        .value        = 0x1,
        .pmaxbit      = 22,
        .pminbit      = 9,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L3_L4_HDR_FRAG_EXT_2 */
        .name         = "INGRESS_PKT_OUTER_L3_L4_HDR_FRAG_EXT_2",
        .match        = 0x420,
        .match_mask   = 0x7b0,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 10,
        .minbit       = 8,
        .value        = 0x4,
        .pmaxbit      = 22,
        .pminbit      = 9,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L3_L4_HDR_GPE */
        .name         = "INGRESS_PKT_OUTER_L3_L4_HDR_GPE",
        .match        = 0x200c,
        .match_mask   = 0x388c,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 13,
        .minbit       = 11,
        .value        = 0x4,
        .pmaxbit      = 22,
        .pminbit      = 9,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L3_L4_HDR_GRE */
        .name         = "INGRESS_PKT_OUTER_L3_L4_HDR_GRE",
        .match        = 0x2,
        .match_mask   = 0x82,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 1,
        .minbit       = 1,
        .value        = 0x1,
        .pmaxbit      = 22,
        .pminbit      = 9,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L3_L4_HDR_GRE_CHKSUM */
        .name         = "INGRESS_PKT_OUTER_L3_L4_HDR_GRE_CHKSUM",
        .match        = 0x1800,
        .match_mask   = 0x3800,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 13,
        .minbit       = 11,
        .value        = 0x3,
        .pmaxbit      = 22,
        .pminbit      = 9,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L3_L4_HDR_GRE_KEY */
        .name         = "INGRESS_PKT_OUTER_L3_L4_HDR_GRE_KEY",
        .match        = 0x8,
        .match_mask   = 0x8c,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 3,
        .minbit       = 2,
        .value        = 0x2,
        .pmaxbit      = 22,
        .pminbit      = 9,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L3_L4_HDR_GRE_ROUT */
        .name         = "INGRESS_PKT_OUTER_L3_L4_HDR_GRE_ROUT",
        .match        = 0x300,
        .match_mask   = 0x780,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 10,
        .minbit       = 8,
        .value        = 0x3,
        .pmaxbit      = 22,
        .pminbit      = 9,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L3_L4_HDR_GRE_SEQ */
        .name         = "INGRESS_PKT_OUTER_L3_L4_HDR_GRE_SEQ",
        .match        = 0x40,
        .match_mask   = 0xc0,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 6,
        .minbit       = 6,
        .value        = 0x1,
        .pmaxbit      = 22,
        .pminbit      = 9,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L3_L4_HDR_ICMP */
        .name         = "INGRESS_PKT_OUTER_L3_L4_HDR_ICMP",
        .match        = 0x2000,
        .match_mask   = 0x380c,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 13,
        .minbit       = 11,
        .value        = 0x4,
        .pmaxbit      = 22,
        .pminbit      = 9,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L3_L4_HDR_IFA_METADATA */
        .name         = "INGRESS_PKT_OUTER_L3_L4_HDR_IFA_METADATA",
        .match        = 0x700,
        .match_mask   = 0x780,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 10,
        .minbit       = 8,
        .value        = 0x7,
        .pmaxbit      = 22,
        .pminbit      = 9,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L3_L4_HDR_IGMP */
        .name         = "INGRESS_PKT_OUTER_L3_L4_HDR_IGMP",
        .match        = 0x200,
        .match_mask   = 0x780,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 10,
        .minbit       = 8,
        .value        = 0x2,
        .pmaxbit      = 22,
        .pminbit      = 9,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L3_L4_HDR_IPV4 */
        .name         = "INGRESS_PKT_OUTER_L3_L4_HDR_IPV4",
        .match        = 0x10,
        .match_mask   = 0xb0,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 5,
        .minbit       = 4,
        .value        = 0x1,
        .pmaxbit      = 22,
        .pminbit      = 9,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L3_L4_HDR_IPV6 */
        .name         = "INGRESS_PKT_OUTER_L3_L4_HDR_IPV6",
        .match        = 0x20,
        .match_mask   = 0xb0,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 5,
        .minbit       = 4,
        .value        = 0x2,
        .pmaxbit      = 22,
        .pminbit      = 9,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L3_L4_HDR_MPLS0 */
        .name         = "INGRESS_PKT_OUTER_L3_L4_HDR_MPLS0",
        .match        = 0x80,
        .match_mask   = 0x80,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 7,
        .minbit       = 7,
        .value        = 0x1,
        .pmaxbit      = 22,
        .pminbit      = 9,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L3_L4_HDR_MPLS1 */
        .name         = "INGRESS_PKT_OUTER_L3_L4_HDR_MPLS1",
        .match        = 0x82,
        .match_mask   = 0x82,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 1,
        .minbit       = 1,
        .value        = 0x1,
        .pmaxbit      = 22,
        .pminbit      = 9,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L3_L4_HDR_MPLS2 */
        .name         = "INGRESS_PKT_OUTER_L3_L4_HDR_MPLS2",
        .match        = 0x84,
        .match_mask   = 0x84,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 2,
        .minbit       = 2,
        .value        = 0x1,
        .pmaxbit      = 22,
        .pminbit      = 9,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L3_L4_HDR_MPLS3 */
        .name         = "INGRESS_PKT_OUTER_L3_L4_HDR_MPLS3",
        .match        = 0x88,
        .match_mask   = 0x88,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 3,
        .minbit       = 3,
        .value        = 0x1,
        .pmaxbit      = 22,
        .pminbit      = 9,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L3_L4_HDR_MPLS4 */
        .name         = "INGRESS_PKT_OUTER_L3_L4_HDR_MPLS4",
        .match        = 0x90,
        .match_mask   = 0x90,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 4,
        .minbit       = 4,
        .value        = 0x1,
        .pmaxbit      = 22,
        .pminbit      = 9,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L3_L4_HDR_MPLS5 */
        .name         = "INGRESS_PKT_OUTER_L3_L4_HDR_MPLS5",
        .match        = 0xa0,
        .match_mask   = 0xa0,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 5,
        .minbit       = 5,
        .value        = 0x1,
        .pmaxbit      = 22,
        .pminbit      = 9,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L3_L4_HDR_MPLS6 */
        .name         = "INGRESS_PKT_OUTER_L3_L4_HDR_MPLS6",
        .match        = 0xc0,
        .match_mask   = 0xc0,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 6,
        .minbit       = 6,
        .value        = 0x1,
        .pmaxbit      = 22,
        .pminbit      = 9,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L3_L4_HDR_MPLS_ACH */
        .name         = "INGRESS_PKT_OUTER_L3_L4_HDR_MPLS_ACH",
        .match        = 0x180,
        .match_mask   = 0x180,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 8,
        .minbit       = 8,
        .value        = 0x1,
        .pmaxbit      = 22,
        .pminbit      = 9,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L3_L4_HDR_MPLS_CW */
        .name         = "INGRESS_PKT_OUTER_L3_L4_HDR_MPLS_CW",
        .match        = 0x280,
        .match_mask   = 0x280,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 9,
        .minbit       = 9,
        .value        = 0x1,
        .pmaxbit      = 22,
        .pminbit      = 9,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L3_L4_HDR_NONE */
        .name         = "INGRESS_PKT_OUTER_L3_L4_HDR_NONE",
        .match        = 0x0,
        .match_mask   = 0x3fff,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 13,
        .minbit       = 0,
        .value        = 0x0,
        .pmaxbit      = 22,
        .pminbit      = 9,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L3_L4_HDR_P_1588 */
        .name         = "INGRESS_PKT_OUTER_L3_L4_HDR_P_1588",
        .match        = 0x3000,
        .match_mask   = 0x3800,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 13,
        .minbit       = 11,
        .value        = 0x6,
        .pmaxbit      = 22,
        .pminbit      = 9,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L3_L4_HDR_RARP */
        .name         = "INGRESS_PKT_OUTER_L3_L4_HDR_RARP",
        .match        = 0x400,
        .match_mask   = 0x7b0,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 10,
        .minbit       = 8,
        .value        = 0x4,
        .pmaxbit      = 22,
        .pminbit      = 9,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L3_L4_HDR_TCP_FIRST_4BYTES */
        .name         = "INGRESS_PKT_OUTER_L3_L4_HDR_TCP_FIRST_4BYTES",
        .match        = 0x4,
        .match_mask   = 0x8c,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 3,
        .minbit       = 2,
        .value        = 0x1,
        .pmaxbit      = 22,
        .pminbit      = 9,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L3_L4_HDR_TCP_LAST_16BYTES */
        .name         = "INGRESS_PKT_OUTER_L3_L4_HDR_TCP_LAST_16BYTES",
        .match        = 0x804,
        .match_mask   = 0x388c,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 13,
        .minbit       = 11,
        .value        = 0x1,
        .pmaxbit      = 22,
        .pminbit      = 9,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L3_L4_HDR_UDP */
        .name         = "INGRESS_PKT_OUTER_L3_L4_HDR_UDP",
        .match        = 0xc,
        .match_mask   = 0x8c,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 3,
        .minbit       = 2,
        .value        = 0x3,
        .pmaxbit      = 22,
        .pminbit      = 9,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L3_L4_HDR_UDPIPSEC */
        .name         = "INGRESS_PKT_OUTER_L3_L4_HDR_UDPIPSEC",
        .match        = 0x600,
        .match_mask   = 0x780,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 10,
        .minbit       = 8,
        .value        = 0x6,
        .pmaxbit      = 22,
        .pminbit      = 9,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L3_L4_HDR_UNKNOWN_L3 */
        .name         = "INGRESS_PKT_OUTER_L3_L4_HDR_UNKNOWN_L3",
        .match        = 0x500,
        .match_mask   = 0x780,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 10,
        .minbit       = 8,
        .value        = 0x5,
        .pmaxbit      = 22,
        .pminbit      = 9,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L3_L4_HDR_UNKNOWN_L4 */
        .name         = "INGRESS_PKT_OUTER_L3_L4_HDR_UNKNOWN_L4",
        .match        = 0x2800,
        .match_mask   = 0x380c,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 13,
        .minbit       = 11,
        .value        = 0x5,
        .pmaxbit      = 22,
        .pminbit      = 9,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L3_L4_HDR_UNKNOWN_L5 */
        .name         = "INGRESS_PKT_OUTER_L3_L4_HDR_UNKNOWN_L5",
        .match        = 0x280c,
        .match_mask   = 0x388c,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 13,
        .minbit       = 11,
        .value        = 0x5,
        .pmaxbit      = 22,
        .pminbit      = 9,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L3_L4_HDR_VXLAN */
        .name         = "INGRESS_PKT_OUTER_L3_L4_HDR_VXLAN",
        .match        = 0x1000,
        .match_mask   = 0x3800,
        .match_maxbit = 22,
        .match_minbit = 9,
        .maxbit       = 13,
        .minbit       = 11,
        .value        = 0x2,
        .pmaxbit      = 22,
        .pminbit      = 9,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_SYS_HDR_EP_NIH */
        .name         = "INGRESS_PKT_SYS_HDR_EP_NIH",
        .match        = 0x2,
        .match_mask   = 0x3,
        .match_maxbit = 1,
        .match_minbit = 0,
        .maxbit       = 1,
        .minbit       = 0,
        .value        = 0x2,
        .pmaxbit      = 1,
        .pminbit      = 0,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_SYS_HDR_LOOPBACK */
        .name         = "INGRESS_PKT_SYS_HDR_LOOPBACK",
        .match        = 0x1,
        .match_mask   = 0x3,
        .match_maxbit = 1,
        .match_minbit = 0,
        .maxbit       = 1,
        .minbit       = 0,
        .value        = 0x1,
        .pmaxbit      = 1,
        .pminbit      = 0,

    },
    {
        /* BCM56780_A0_HNA_6_5_34_2_0_RXPMD_MATCH_ID_INGRESS_PKT_SYS_HDR_NONE */
        .name         = "INGRESS_PKT_SYS_HDR_NONE",
        .match        = 0x0,
        .match_mask   = 0x3,
        .match_maxbit = 1,
        .match_minbit = 0,
        .maxbit       = 1,
        .minbit       = 0,
        .value        = 0x0,
        .pmaxbit      = 1,
        .pminbit      = 0,

    },
};

static bcmpkt_rxpmd_match_id_db_info_t bcm56780_a0_hna_6_5_34_2_0_rxpmd_match_id_db_info = {
    .num_entries = 168,
    .db = bcm56780_a0_hna_6_5_34_2_0_rxpmd_match_id_db
};
bcmpkt_rxpmd_match_id_db_info_t * bcm56780_a0_hna_6_5_34_2_0_rxpmd_match_id_db_info_get(void) {
    return &bcm56780_a0_hna_6_5_34_2_0_rxpmd_match_id_db_info;
}

static shr_enum_map_t bcm56780_a0_hna_6_5_34_2_0_rxpmd_match_id_map[] = {
    BCM56780_A0_HNA_6_5_34_2_0_BCMPKT_RXPMD_MATCH_ID_FIELD_NAME_MAP_INIT
};

static bcmpkt_rxpmd_match_id_map_info_t bcm56780_a0_hna_6_5_34_2_0_rxpmd_match_id_map_info = {
    .num_entries = 168,
    .map = bcm56780_a0_hna_6_5_34_2_0_rxpmd_match_id_map
};

bcmpkt_rxpmd_match_id_map_info_t * bcm56780_a0_hna_6_5_34_2_0_rxpmd_match_id_map_info_get(void) {
    return &bcm56780_a0_hna_6_5_34_2_0_rxpmd_match_id_map_info;
}
