# SPDX-License-Identifier: GPL-2.0
#
# Makefile for Marvell OcteonTX2 device drivers.
#

obj-$(CONFIG_OCTEONTX2_MBOX) += af/
obj-$(CONFIG_OCTEONTX2_AF) += af/
obj-$(CONFIG_OCTEONTX2_PF) += nic/
obj-$(CONFIG_OCTEONTX2_BPHY_RFOE_NETDEV) += bphy/
obj-$(CONFIG_OCTEONTX2_BPHY_PF) += bphy/cnf20k/
obj-$(CONFIG_OCTEONTX2_BPHY_CNF20K_CPRI_PF) += bphy/
