#
# Makefile for DTrace
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License, Version 1.0 only
# (the "License").  You may not use this file except in compliance
# with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
# Copyright 2011 Oracle, Inc.  All rights reserved.
# Use is subject to license terms.

GCOV_PROFILE := y

EXTRA_CFLAGS			:= -Ikernel/dtrace

obj-$(CONFIG_DT_CORE)		+= dtrace.o
obj-$(CONFIG_DT_FASTTRAP)	+= fasttrap.o
obj-$(CONFIG_DT_FBT)		+= fbt.o
obj-$(CONFIG_DT_LOCKSTAT)	+= lockstat.o
obj-$(CONFIG_DT_PROFILE)	+= profile.o
obj-$(CONFIG_DT_SDT)		+= sdt.o
obj-$(CONFIG_DT_SYSTRACE)	+= systrace.o
obj-$(CONFIG_DT_DT_TEST)	+= dt_test.o

dtrace-y			:= dtrace_mod.o dtrace_dev.o \
				   dtrace_asm.o dtrace_isa.o \
				   dtrace_actdesc.o dtrace_anon.o \
				   dtrace_buffer.o dtrace_dif.o dtrace_dof.o \
				   dtrace_ecb.o dtrace_enable.o \
				   dtrace_fmt.o dtrace_hash.o dtrace_helper.o \
				   dtrace_match.o dtrace_priv.o \
				   dtrace_probe.o dtrace_probe_ctx.o \
				   dtrace_ptofapi.o dtrace_predicate.o \
				   dtrace_spec.o dtrace_state.o dtrace_util.o
fasttrap-y			:= fasttrap_mod.o fasttrap_dev.o
fbt-y				:= fbt_mod.o fbt_dev.o
lockstat-y			:= lockstat_mod.o lockstat_dev.o
profile-y			:= profile_mod.o profile_dev.o
sdt-y				:= sdt_mod.o sdt_dev.o sdt_subr.o
systrace-y			:= systrace_mod.o systrace_dev.o
dt_test-y			:= dt_test_mod.o dt_test_dev.o
