BL_DENTRY(void *, notifier_call_chain)
BL_SENTRY(typeof(__atomic_notifier_call_chain), __atomic_notifier_call_chain)
BL_SENTRY(typeof(atomic_notifier_call_chain), atomic_notifier_call_chain)
BL_SENTRY(typeof(__raw_notifier_call_chain), __raw_notifier_call_chain)
BL_SENTRY(typeof(raw_notifier_call_chain), raw_notifier_call_chain)
BL_DENTRY(void *, hw_breakpoint_exceptions_notify)
BL_DENTRY(void *, kprobe_exceptions_notify)
BL_SENTRY(void *, notify_die)
BL_DENTRY(void *, pvclock_clocksource_read)
BL_SENTRY(typeof(ktime_get_raw_fast_ns), ktime_get_raw_fast_ns)
BL_DENTRY(void *, fixup_exception)

BL_SENTRY(void *, do_page_fault)
BL_DENTRY(void *, __do_page_fault)
BL_DENTRY(void *, down_read_trylock)
BL_DENTRY(void *, __get_user_pages_fast)
BL_DENTRY(void *, gup_pud_range)
BL_DENTRY(void *, gup_huge_pud)
BL_DENTRY(void *, gup_pmd_range)
BL_DENTRY(void *, gup_huge_pmd)
BL_DENTRY(void *, gup_pte_range)
BL_DENTRY(void *, pte_mfn_to_pfn)
