# SPDX-License-Identifier: GPL-2.0
#
# Makefile for Marvell's OcteonTX2 NPA PF driver
#

obj-$(CONFIG_OCTEONTX2_NPA_PF) += octeontx2_npa.o
ccflags-y += -I$(srctree)/drivers/net/ethernet/marvell/octeontx2/af
octeontx2_npa-y := npa.o
