obj-$(CONFIG_PDDF_MULTIFPGAPCI) += driver/ gpio/ spi/ i2c/ i2c-xiic/ mdio/
obj-$(CONFIG_PDDF_MULTIFPGAPCI) += pddf_multifpgapci_module.o

ccflags-y := -I$(srctree)/drivers/platform/pddf-sonic/include
