# -*- Kbuild -*-
#
# Linux KNET module.
#
# Copyright 2018-2024 Broadcom. All rights reserved.
# The term 'Broadcom' refers to Broadcom Inc. and/or its subsidiaries.
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License 
# version 2 as published by the Free Software Foundation.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# A copy of the GNU General Public License version 2 (GPLv2) can
# be found in the LICENSES folder.
#

obj-m := linux_ngknet.o

ifneq ($(OUTPUT_DIR),)
INCLUDES := -I$(OUTPUT_DIR)/knet/generated/include -I$(OUTPUT_DIR)/knet/generated
endif

ccflags-y := $(KNET_CPPFLAGS) $(LKM_CFLAGS) \
             -I$(SDK)/shr/include \
             -I$(SDK)/bcmdrd/include \
             -I$(SDK)/linux/include \
             -I$(SDK)/linux/knet/generated/include \
             -I$(SDK)/linux/knet/generated \
             $(INCLUDES)

linux_ngknet-y := $(CHIP_OBJS) \
                  bcmcnet_cmicd_pdma_hw.o \
                  bcmcnet_cmicd_pdma_rxtx.o \
                  bcmcnet_cmicx_pdma_hw.o \
                  bcmcnet_cmicx_pdma_rxtx.o \
                  bcmcnet_cmicr_pdma_hw.o \
                  bcmcnet_cmicr_pdma_rxtx.o \
                  bcmcnet_cmicr2_pdma_rxtx.o \
                  bcmcnet_core.o \
                  bcmcnet_dev.o \
                  bcmcnet_rxtx.o \
                  ngknet_buff.o \
                  ngknet_callback.o \
                  ngknet_extra.o \
                  ngknet_linux.o \
                  ngknet_main.o \
                  ngknet_procfs.o \
                  ngknet_ptp.o
