# SPDX-License-Identifier: GPL-2.0
obj-y		+= octeontx2-rm/
obj-y		+= octeontx2-dpi/
obj-y		+= octeontx2-serdes/
obj-y		+= gti/
obj-$(CONFIG_OCTEONTX_INFO) += octeontx_info.o
obj-$(CONFIG_MDIO_DEBUGFS) += mdio_debugfs.o
