# SPDX-License-Identifier: GPL-2.0
obj-y		+= gti/
obj-y		+= octeontx2-rm/
obj-y		+= octeontx2-dpi/
obj-y		+= octeontx2-sdp/
obj-y		+= octeontx2-npa/
obj-y		+= octeontx2-llc/
obj-y 		+= csr-access/

obj-$(CONFIG_OCTEONTX_INFO) += octeontx_info.o
obj-$(CONFIG_MVMDIO_UIO) += mvmdio_uio.o
