# SPDX-License-Identifier: GPL-2.0-only

obj-$(CONFIG_CRYPTO_DEV_MARVELL_CESA) += cesa/
obj-$(CONFIG_CRYPTO_DEV_OCTEONTX_CPT) += octeontx/
obj-$(CONFIG_CRYPTO_DEV_OCTEONTX2_CPT) += octeontx2/
obj-$(CONFIG_CRYPTO_DEV_CN10K_CPT) += cn10k/
