# SPDX-License-Identifier: GPL-2.0
#
# Makefile for Marvell's CPSS drivers
#
#
obj-$(CONFIG_MARVELL_CPSS) := mvDmaDrv.o mvIntDrv.o mvMbusDrv.o mvEthDrv.o

mvDmaDrv-y := dmaDriver.o
mvIntDrv-y := intDriver.o
mvMbusDrv-y := mbusDriver.o mbusResources.o
mvEthDrv-y := ethDriver.o
