# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_CRYPTO_DEV_OCTEONTX_ZIP) += octeontx-zip.o octeontx-zipvf.o

octeontx-zip-objs := zip_pf_main.o
octeontx-zipvf-objs := zip_vf_deflate.o zip_vf_debugfs.o zip_vf_main.o
