# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_PENSANDO_SALINA_SOC) += salina-asic.dtb \
					  salina-a35-asic.dtb \
					  salina-haps-4core.dtb \
					  salina-haps-16core.dtb \
					  salina-a35-haps.dtb
dtb-$(CONFIG_ARCH_SEATTLE) += amd-overdrive.dtb \
			amd-overdrive-rev-b0.dtb amd-overdrive-rev-b1.dtb \
			husky.dtb
