/* Copyright (C) 2011-2014 Oracle, Inc. */

DTRACE_SYSCALL_STUB(CLONE,		clone)
DTRACE_SYSCALL_STUB(FORK,		fork)
DTRACE_SYSCALL_STUB(VFORK,		vfork)
DTRACE_SYSCALL_STUB(IOPL,		iopl)
DTRACE_SYSCALL_STUB(EXECVE,		execve)
DTRACE_SYSCALL_STUB(RT_SIGRETURN,	rt_sigreturn)
