/* This file is automatically generated by /home/komang/build/master/install/bin/gitstatus.sh */

#include "version.h"

struct sif_version sif_version = {
.git_repo = "sifdrv [non public commit]",
.last_commit = "0.0.0.4-770-ga475650 tmp: more bugDB->Orabug",
.git_status = "",
.build_git_time = "Wed, 25 May 2016 08:45:49 +0000",
.build_user = "komang",

.git_psifapi_repo = "psifapi [origin/master]",
.last_psifapi_commit = "epsapp-1.17 API for mailbox for BER report",
.git_psifapi_status = "",
};
