BL_DENTRY(void *, notifier_call_chain)
BL_SENTRY(typeof(__atomic_notifier_call_chain), __atomic_notifier_call_chain)
BL_SENTRY(typeof(atomic_notifier_call_chain), atomic_notifier_call_chain)
BL_SENTRY(typeof(__raw_notifier_call_chain), __raw_notifier_call_chain)
BL_SENTRY(typeof(raw_notifier_call_chain), raw_notifier_call_chain)
BL_DENTRY(void *, notify_die)
BL_SENTRY(void *, rcu_nmi_exit)
BL_SENTRY(void *, rcu_nmi_enter)
BL_SENTRY(typeof(ktime_get_raw_fast_ns), ktime_get_raw_fast_ns)
BL_DENTRY(void *, kprobe_exceptions_notify)
BL_DENTRY(void *, arch_uprobe_exception_notify)
BL_DENTRY(void *, sun4v_data_access_exception)
BL_DENTRY(void *, sun4v_do_mna)
BL_DENTRY(void *, get_fault_insn)
BL_DENTRY(void *, kernel_unaligned_trap)
BL_DENTRY(typeof(save_stack_trace), save_stack_trace)
BL_DENTRY(typeof(__save_stack_trace), __save_stack_trace)
BL_DENTRY(typeof(stack_trace_flush), stack_trace_flush)
BL_DENTRY(typeof(in_sched_functions), in_sched_functions)
BL_DENTRY(typeof(search_exception_tables), search_exception_tables) 
BL_DENTRY(void *, down_read_trylock)
BL_DENTRY(void *, __down_read_trylock)
BL_DENTRY(void *, __get_user_pages_fast)
BL_DENTRY(void *, gup_pud_range)
BL_DENTRY(void *, gup_pmd_range)
BL_DENTRY(void *, gup_huge_pmd)
BL_DENTRY(void *, gup_pte_range)
