BL_DENTRY(void *, read_tsc)
BL_DENTRY(void *, notifier_call_chain)
BL_SENTRY(typeof(__atomic_notifier_call_chain), __atomic_notifier_call_chain)
BL_SENTRY(typeof(atomic_notifier_call_chain), atomic_notifier_call_chain)
BL_SENTRY(typeof(__raw_notifier_call_chain), __raw_notifier_call_chain)
BL_SENTRY(typeof(raw_notifier_call_chain), raw_notifier_call_chain)
BL_SENTRY(typeof(getrawmonotonic64), getrawmonotonic64)
BL_DENTRY(void *, update_fast_timekeeper)
BL_SENTRY(typeof(idr_find_slowpath), idr_find_slowpath)
BL_DENTRY(void *, kprobe_exceptions_notify)
BL_SENTRY(void *, notify_die)
BL_SENTRY(void *, rcu_nmi_exit)
BL_SENTRY(void *, rcu_nmi_enter)
BL_SENTRY(void *, get_kprobe)
