# SPDX-License-Identifier: GPL-2.0

ccflags-y += -I$(src)/../pddf-sonic/include

obj-$(CONFIG_NEXTHOP_SONIC_DRIVERS) += nh_pmbus_core.o
obj-$(CONFIG_NEXTHOP_SONIC_DRIVERS) += nh_adm1266.o
obj-$(CONFIG_NEXTHOP_SONIC_DRIVERS) += nh_isl68137.o
obj-$(CONFIG_NEXTHOP_SONIC_DRIVERS) += nh_tda38740.o
obj-$(CONFIG_NEXTHOP_SONIC_DRIVERS) += nh_tmp464.o
obj-$(CONFIG_NEXTHOP_SONIC_FPGA_ALGO) += pddf_custom_fpga_algo.o
obj-$(CONFIG_NEXTHOP_SONIC_MDIO_ALGO) += pddf_custom_mdio_algo.o
