/*******************************************************************************
 *
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated from the registers file.
 * Edits to this file will be lost when it is regenerated.
 * Tool: INTERNAL/regs/xgs/generate-pmd.pl
 *
 *
 * Copyright 2018-2025 Broadcom. All rights reserved.
 * The term 'Broadcom' refers to Broadcom Inc. and/or its subsidiaries.
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License 
 * version 2 as published by the Free Software Foundation.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * A copy of the GNU General Public License version 2 (GPLv2) can
 * be found in the LICENSES folder.
 *
 * This file provides PMD field info for BCM78914_B0.
 *
 ******************************************************************************/

#include <bcmpkt/bcmpkt_pmd_field_internal.h>
#include <bcmpkt/chip/bcm78914_b0/bcm78914_b0_pmd_field.h>

static bcmpkt_field_info_t
field_fmt_0_0_13_13_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 0;
    info.maxbit = 0;
    return info;
}

static void
field_fmt_0_0_13_13_set(uint32_t *pmd, uint32_t *val)
{
    pmd[13] = (pmd[13] & 0xfffffffe) | (*val & 0x1);
}

static void
field_fmt_0_0_13_13_get(uint32_t *pmd, uint32_t *val)
{
    *val = pmd[13] & 0x1;
}

static bcmpkt_field_info_t
field_fmt_0_16_3_3_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 0;
    info.maxbit = 16;
    return info;
}

static void
field_fmt_0_16_3_3_set(uint32_t *pmd, uint32_t *val)
{
    pmd[3] = (pmd[3] & 0xfffe0000) | (*val & 0x1ffff);
}

static void
field_fmt_0_16_3_3_get(uint32_t *pmd, uint32_t *val)
{
    *val = pmd[3] & 0x1ffff;
}

static bcmpkt_field_info_t
field_fmt_0_63_13_12_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 0;
    info.maxbit = 63;
    return info;
}

static void
field_fmt_0_63_13_12_set(uint32_t *pmd, uint32_t *val)
{
    pmd[13] = val[0];
    pmd[12] = val[1];
}

static void
field_fmt_0_63_13_12_get(uint32_t *pmd, uint32_t *val)
{
    val[0] = pmd[13];
    val[1] = pmd[12];
}

static bcmpkt_field_info_t
field_fmt_0_7_3_3_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 0;
    info.maxbit = 7;
    return info;
}

static void
field_fmt_0_7_3_3_set(uint32_t *pmd, uint32_t *val)
{
    pmd[3] = (pmd[3] & 0xffffff00) | (*val & 0xff);
}

static void
field_fmt_0_7_3_3_get(uint32_t *pmd, uint32_t *val)
{
    *val = pmd[3] & 0xff;
}

static bcmpkt_field_info_t
field_fmt_10_10_13_13_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 10;
    info.maxbit = 10;
    return info;
}

static void
field_fmt_10_10_13_13_set(uint32_t *pmd, uint32_t *val)
{
    pmd[13] = (pmd[13] & 0xfffffbff) | ((*val & 0x1) << 10);
}

static void
field_fmt_10_10_13_13_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[13] >> 10) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_10_11_3_3_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 10;
    info.maxbit = 11;
    return info;
}

static void
field_fmt_10_11_3_3_set(uint32_t *pmd, uint32_t *val)
{
    pmd[3] = (pmd[3] & 0xfffff3ff) | ((*val & 0x3) << 10);
}

static void
field_fmt_10_11_3_3_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[3] >> 10) & 0x3;
}

static bcmpkt_field_info_t
field_fmt_115_127_10_10_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 115;
    info.maxbit = 127;
    return info;
}

static void
field_fmt_115_127_10_10_set(uint32_t *pmd, uint32_t *val)
{
    pmd[10] = (pmd[10] & 0x7ffff) | (*val << 19);
}

static void
field_fmt_115_127_10_10_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[10] >> 19) & 0x1fff;
}

static bcmpkt_field_info_t
field_fmt_116_119_0_0_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 116;
    info.maxbit = 119;
    return info;
}

static void
field_fmt_116_119_0_0_set(uint32_t *pmd, uint32_t *val)
{
    pmd[0] = (pmd[0] & 0xff0fffff) | ((*val & 0xf) << 20);
}

static void
field_fmt_116_119_0_0_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[0] >> 20) & 0xf;
}

static bcmpkt_field_info_t
field_fmt_11_11_13_13_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 11;
    info.maxbit = 11;
    return info;
}

static void
field_fmt_11_11_13_13_set(uint32_t *pmd, uint32_t *val)
{
    pmd[13] = (pmd[13] & 0xfffff7ff) | ((*val & 0x1) << 11);
}

static void
field_fmt_11_11_13_13_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[13] >> 11) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_120_125_0_0_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 120;
    info.maxbit = 125;
    return info;
}

static void
field_fmt_120_125_0_0_set(uint32_t *pmd, uint32_t *val)
{
    pmd[0] = (pmd[0] & 0xc0ffffff) | ((*val & 0x3f) << 24);
}

static void
field_fmt_120_125_0_0_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[0] >> 24) & 0x3f;
}

static bcmpkt_field_info_t
field_fmt_126_127_0_0_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 126;
    info.maxbit = 127;
    return info;
}

static void
field_fmt_126_127_0_0_set(uint32_t *pmd, uint32_t *val)
{
    pmd[0] = (pmd[0] & 0x3fffffff) | (*val << 30);
}

static void
field_fmt_126_127_0_0_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[0] >> 30) & 0x3;
}

static bcmpkt_field_info_t
field_fmt_128_128_9_9_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 128;
    info.maxbit = 128;
    return info;
}

static void
field_fmt_128_128_9_9_set(uint32_t *pmd, uint32_t *val)
{
    pmd[9] = (pmd[9] & 0xfffffffe) | (*val & 0x1);
}

static void
field_fmt_128_128_9_9_get(uint32_t *pmd, uint32_t *val)
{
    *val = pmd[9] & 0x1;
}

static bcmpkt_field_info_t
field_fmt_129_130_9_9_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 129;
    info.maxbit = 130;
    return info;
}

static void
field_fmt_129_130_9_9_set(uint32_t *pmd, uint32_t *val)
{
    pmd[9] = (pmd[9] & 0xfffffff9) | ((*val & 0x3) << 1);
}

static void
field_fmt_129_130_9_9_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[9] >> 1) & 0x3;
}

static bcmpkt_field_info_t
field_fmt_12_12_13_13_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 12;
    info.maxbit = 12;
    return info;
}

static void
field_fmt_12_12_13_13_set(uint32_t *pmd, uint32_t *val)
{
    pmd[13] = (pmd[13] & 0xffffefff) | ((*val & 0x1) << 12);
}

static void
field_fmt_12_12_13_13_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[13] >> 12) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_12_17_3_3_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 12;
    info.maxbit = 17;
    return info;
}

static void
field_fmt_12_17_3_3_set(uint32_t *pmd, uint32_t *val)
{
    pmd[3] = (pmd[3] & 0xfffc0fff) | ((*val & 0x3f) << 12);
}

static void
field_fmt_12_17_3_3_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[3] >> 12) & 0x3f;
}

static bcmpkt_field_info_t
field_fmt_131_144_9_9_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 131;
    info.maxbit = 144;
    return info;
}

static void
field_fmt_131_144_9_9_set(uint32_t *pmd, uint32_t *val)
{
    pmd[9] = (pmd[9] & 0xfffe0007) | ((*val & 0x3fff) << 3);
}

static void
field_fmt_131_144_9_9_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[9] >> 3) & 0x3fff;
}

static bcmpkt_field_info_t
field_fmt_13_13_13_13_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 13;
    info.maxbit = 13;
    return info;
}

static void
field_fmt_13_13_13_13_set(uint32_t *pmd, uint32_t *val)
{
    pmd[13] = (pmd[13] & 0xffffdfff) | ((*val & 0x1) << 13);
}

static void
field_fmt_13_13_13_13_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[13] >> 13) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_145_159_9_9_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 145;
    info.maxbit = 159;
    return info;
}

static void
field_fmt_145_159_9_9_set(uint32_t *pmd, uint32_t *val)
{
    pmd[9] = (pmd[9] & 0x1ffff) | (*val << 17);
}

static void
field_fmt_145_159_9_9_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[9] >> 17) & 0x7fff;
}

static bcmpkt_field_info_t
field_fmt_14_14_13_13_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 14;
    info.maxbit = 14;
    return info;
}

static void
field_fmt_14_14_13_13_set(uint32_t *pmd, uint32_t *val)
{
    pmd[13] = (pmd[13] & 0xffffbfff) | ((*val & 0x1) << 14);
}

static void
field_fmt_14_14_13_13_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[13] >> 14) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_15_15_13_13_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 15;
    info.maxbit = 15;
    return info;
}

static void
field_fmt_15_15_13_13_set(uint32_t *pmd, uint32_t *val)
{
    pmd[13] = (pmd[13] & 0xffff7fff) | ((*val & 0x1) << 15);
}

static void
field_fmt_15_15_13_13_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[13] >> 15) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_160_160_8_8_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 160;
    info.maxbit = 160;
    return info;
}

static void
field_fmt_160_160_8_8_set(uint32_t *pmd, uint32_t *val)
{
    pmd[8] = (pmd[8] & 0xfffffffe) | (*val & 0x1);
}

static void
field_fmt_160_160_8_8_get(uint32_t *pmd, uint32_t *val)
{
    *val = pmd[8] & 0x1;
}

static bcmpkt_field_info_t
field_fmt_161_161_8_8_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 161;
    info.maxbit = 161;
    return info;
}

static void
field_fmt_161_161_8_8_set(uint32_t *pmd, uint32_t *val)
{
    pmd[8] = (pmd[8] & 0xfffffffd) | ((*val & 0x1) << 1);
}

static void
field_fmt_161_161_8_8_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[8] >> 1) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_162_162_8_8_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 162;
    info.maxbit = 162;
    return info;
}

static void
field_fmt_162_162_8_8_set(uint32_t *pmd, uint32_t *val)
{
    pmd[8] = (pmd[8] & 0xfffffffb) | ((*val & 0x1) << 2);
}

static void
field_fmt_162_162_8_8_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[8] >> 2) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_163_163_8_8_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 163;
    info.maxbit = 163;
    return info;
}

static void
field_fmt_163_163_8_8_set(uint32_t *pmd, uint32_t *val)
{
    pmd[8] = (pmd[8] & 0xfffffff7) | ((*val & 0x1) << 3);
}

static void
field_fmt_163_163_8_8_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[8] >> 3) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_164_164_8_8_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 164;
    info.maxbit = 164;
    return info;
}

static void
field_fmt_164_164_8_8_set(uint32_t *pmd, uint32_t *val)
{
    pmd[8] = (pmd[8] & 0xffffffef) | ((*val & 0x1) << 4);
}

static void
field_fmt_164_164_8_8_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[8] >> 4) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_165_165_8_8_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 165;
    info.maxbit = 165;
    return info;
}

static void
field_fmt_165_165_8_8_set(uint32_t *pmd, uint32_t *val)
{
    pmd[8] = (pmd[8] & 0xffffffdf) | ((*val & 0x1) << 5);
}

static void
field_fmt_165_165_8_8_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[8] >> 5) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_166_168_8_8_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 166;
    info.maxbit = 168;
    return info;
}

static void
field_fmt_166_168_8_8_set(uint32_t *pmd, uint32_t *val)
{
    pmd[8] = (pmd[8] & 0xfffffe3f) | ((*val & 0x7) << 6);
}

static void
field_fmt_166_168_8_8_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[8] >> 6) & 0x7;
}

static bcmpkt_field_info_t
field_fmt_166_171_8_8_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 166;
    info.maxbit = 171;
    return info;
}

static void
field_fmt_166_171_8_8_set(uint32_t *pmd, uint32_t *val)
{
    pmd[8] = (pmd[8] & 0xfffff03f) | ((*val & 0x3f) << 6);
}

static void
field_fmt_166_171_8_8_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[8] >> 6) & 0x3f;
}

static bcmpkt_field_info_t
field_fmt_16_16_13_13_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 16;
    info.maxbit = 16;
    return info;
}

static void
field_fmt_16_16_13_13_set(uint32_t *pmd, uint32_t *val)
{
    pmd[13] = (pmd[13] & 0xfffeffff) | ((*val & 0x1) << 16);
}

static void
field_fmt_16_16_13_13_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[13] >> 16) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_16_18_3_3_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 16;
    info.maxbit = 18;
    return info;
}

static void
field_fmt_16_18_3_3_set(uint32_t *pmd, uint32_t *val)
{
    pmd[3] = (pmd[3] & 0xfff8ffff) | ((*val & 0x7) << 16);
}

static void
field_fmt_16_18_3_3_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[3] >> 16) & 0x7;
}

static bcmpkt_field_info_t
field_fmt_172_173_8_8_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 172;
    info.maxbit = 173;
    return info;
}

static void
field_fmt_172_173_8_8_set(uint32_t *pmd, uint32_t *val)
{
    pmd[8] = (pmd[8] & 0xffffcfff) | ((*val & 0x3) << 12);
}

static void
field_fmt_172_173_8_8_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[8] >> 12) & 0x3;
}

static bcmpkt_field_info_t
field_fmt_174_174_8_8_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 174;
    info.maxbit = 174;
    return info;
}

static void
field_fmt_174_174_8_8_set(uint32_t *pmd, uint32_t *val)
{
    pmd[8] = (pmd[8] & 0xffffbfff) | ((*val & 0x1) << 14);
}

static void
field_fmt_174_174_8_8_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[8] >> 14) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_175_175_8_8_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 175;
    info.maxbit = 175;
    return info;
}

static void
field_fmt_175_175_8_8_set(uint32_t *pmd, uint32_t *val)
{
    pmd[8] = (pmd[8] & 0xffff7fff) | ((*val & 0x1) << 15);
}

static void
field_fmt_175_175_8_8_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[8] >> 15) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_176_184_8_8_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 176;
    info.maxbit = 184;
    return info;
}

static void
field_fmt_176_184_8_8_set(uint32_t *pmd, uint32_t *val)
{
    pmd[8] = (pmd[8] & 0xfe00ffff) | ((*val & 0x1ff) << 16);
}

static void
field_fmt_176_184_8_8_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[8] >> 16) & 0x1ff;
}

static bcmpkt_field_info_t
field_fmt_176_187_8_8_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 176;
    info.maxbit = 187;
    return info;
}

static void
field_fmt_176_187_8_8_set(uint32_t *pmd, uint32_t *val)
{
    pmd[8] = (pmd[8] & 0xf000ffff) | ((*val & 0xfff) << 16);
}

static void
field_fmt_176_187_8_8_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[8] >> 16) & 0xfff;
}

static bcmpkt_field_info_t
field_fmt_17_17_13_13_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 17;
    info.maxbit = 17;
    return info;
}

static void
field_fmt_17_17_13_13_set(uint32_t *pmd, uint32_t *val)
{
    pmd[13] = (pmd[13] & 0xfffdffff) | ((*val & 0x1) << 17);
}

static void
field_fmt_17_17_13_13_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[13] >> 17) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_17_25_3_3_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 17;
    info.maxbit = 25;
    return info;
}

static void
field_fmt_17_25_3_3_set(uint32_t *pmd, uint32_t *val)
{
    pmd[3] = (pmd[3] & 0xfc01ffff) | ((*val & 0x1ff) << 17);
}

static void
field_fmt_17_25_3_3_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[3] >> 17) & 0x1ff;
}

static bcmpkt_field_info_t
field_fmt_185_185_8_8_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 185;
    info.maxbit = 185;
    return info;
}

static void
field_fmt_185_185_8_8_set(uint32_t *pmd, uint32_t *val)
{
    pmd[8] = (pmd[8] & 0xfdffffff) | ((*val & 0x1) << 25);
}

static void
field_fmt_185_185_8_8_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[8] >> 25) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_188_190_8_8_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 188;
    info.maxbit = 190;
    return info;
}

static void
field_fmt_188_190_8_8_set(uint32_t *pmd, uint32_t *val)
{
    pmd[8] = (pmd[8] & 0x8fffffff) | ((*val & 0x7) << 28);
}

static void
field_fmt_188_190_8_8_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[8] >> 28) & 0x7;
}

static bcmpkt_field_info_t
field_fmt_18_18_13_13_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 18;
    info.maxbit = 18;
    return info;
}

static void
field_fmt_18_18_13_13_set(uint32_t *pmd, uint32_t *val)
{
    pmd[13] = (pmd[13] & 0xfffbffff) | ((*val & 0x1) << 18);
}

static void
field_fmt_18_18_13_13_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[13] >> 18) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_18_33_3_2_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 18;
    info.maxbit = 33;
    return info;
}

static void
field_fmt_18_33_3_2_set(uint32_t *pmd, uint32_t *val)
{
    pmd[3] = (pmd[3] & 0x3ffff) | (*val << 18);
    pmd[2] = (pmd[2] & 0xfffffffc) | ((*val >> 14) & 0x3);
}

static void
field_fmt_18_33_3_2_get(uint32_t *pmd, uint32_t *val)
{
    *val = ((pmd[3] >> 18) | (pmd[2] << 14)) & 0xffff;
}

static bcmpkt_field_info_t
field_fmt_191_191_8_8_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 191;
    info.maxbit = 191;
    return info;
}

static void
field_fmt_191_191_8_8_set(uint32_t *pmd, uint32_t *val)
{
    pmd[8] = (pmd[8] & 0x7fffffff) | (*val << 31);
}

static void
field_fmt_191_191_8_8_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[8] >> 31) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_192_194_7_7_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 192;
    info.maxbit = 194;
    return info;
}

static void
field_fmt_192_194_7_7_set(uint32_t *pmd, uint32_t *val)
{
    pmd[7] = (pmd[7] & 0xfffffff8) | (*val & 0x7);
}

static void
field_fmt_192_194_7_7_get(uint32_t *pmd, uint32_t *val)
{
    *val = pmd[7] & 0x7;
}

static bcmpkt_field_info_t
field_fmt_195_206_7_7_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 195;
    info.maxbit = 206;
    return info;
}

static void
field_fmt_195_206_7_7_set(uint32_t *pmd, uint32_t *val)
{
    pmd[7] = (pmd[7] & 0xffff8007) | ((*val & 0xfff) << 3);
}

static void
field_fmt_195_206_7_7_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[7] >> 3) & 0xfff;
}

static bcmpkt_field_info_t
field_fmt_19_19_13_13_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 19;
    info.maxbit = 19;
    return info;
}

static void
field_fmt_19_19_13_13_set(uint32_t *pmd, uint32_t *val)
{
    pmd[13] = (pmd[13] & 0xfff7ffff) | ((*val & 0x1) << 19);
}

static void
field_fmt_19_19_13_13_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[13] >> 19) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_19_19_3_3_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 19;
    info.maxbit = 19;
    return info;
}

static void
field_fmt_19_19_3_3_set(uint32_t *pmd, uint32_t *val)
{
    pmd[3] = (pmd[3] & 0xfff7ffff) | ((*val & 0x1) << 19);
}

static void
field_fmt_19_19_3_3_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[3] >> 19) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_1_1_13_13_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 1;
    info.maxbit = 1;
    return info;
}

static void
field_fmt_1_1_13_13_set(uint32_t *pmd, uint32_t *val)
{
    pmd[13] = (pmd[13] & 0xfffffffd) | ((*val & 0x1) << 1);
}

static void
field_fmt_1_1_13_13_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[13] >> 1) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_207_221_7_7_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 207;
    info.maxbit = 221;
    return info;
}

static void
field_fmt_207_221_7_7_set(uint32_t *pmd, uint32_t *val)
{
    pmd[7] = (pmd[7] & 0xc0007fff) | ((*val & 0x7fff) << 15);
}

static void
field_fmt_207_221_7_7_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[7] >> 15) & 0x7fff;
}

static bcmpkt_field_info_t
field_fmt_20_20_13_13_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 20;
    info.maxbit = 20;
    return info;
}

static void
field_fmt_20_20_13_13_set(uint32_t *pmd, uint32_t *val)
{
    pmd[13] = (pmd[13] & 0xffefffff) | ((*val & 0x1) << 20);
}

static void
field_fmt_20_20_13_13_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[13] >> 20) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_21_21_13_13_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 21;
    info.maxbit = 21;
    return info;
}

static void
field_fmt_21_21_13_13_set(uint32_t *pmd, uint32_t *val)
{
    pmd[13] = (pmd[13] & 0xffdfffff) | ((*val & 0x1) << 21);
}

static void
field_fmt_21_21_13_13_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[13] >> 21) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_21_21_3_3_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 21;
    info.maxbit = 21;
    return info;
}

static void
field_fmt_21_21_3_3_set(uint32_t *pmd, uint32_t *val)
{
    pmd[3] = (pmd[3] & 0xffdfffff) | ((*val & 0x1) << 21);
}

static void
field_fmt_21_21_3_3_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[3] >> 21) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_222_222_7_7_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 222;
    info.maxbit = 222;
    return info;
}

static void
field_fmt_222_222_7_7_set(uint32_t *pmd, uint32_t *val)
{
    pmd[7] = (pmd[7] & 0xbfffffff) | ((*val & 0x1) << 30);
}

static void
field_fmt_222_222_7_7_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[7] >> 30) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_223_242_7_6_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 223;
    info.maxbit = 242;
    return info;
}

static void
field_fmt_223_242_7_6_set(uint32_t *pmd, uint32_t *val)
{
    pmd[7] = (pmd[7] & 0x7fffffff) | (*val << 31);
    pmd[6] = (pmd[6] & 0xfff80000) | ((*val >> 1) & 0x7ffff);
}

static void
field_fmt_223_242_7_6_get(uint32_t *pmd, uint32_t *val)
{
    *val = ((pmd[7] >> 31) | (pmd[6] << 1)) & 0xfffff;
}

static bcmpkt_field_info_t
field_fmt_22_22_13_13_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 22;
    info.maxbit = 22;
    return info;
}

static void
field_fmt_22_22_13_13_set(uint32_t *pmd, uint32_t *val)
{
    pmd[13] = (pmd[13] & 0xffbfffff) | ((*val & 0x1) << 22);
}

static void
field_fmt_22_22_13_13_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[13] >> 22) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_22_22_3_3_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 22;
    info.maxbit = 22;
    return info;
}

static void
field_fmt_22_22_3_3_set(uint32_t *pmd, uint32_t *val)
{
    pmd[3] = (pmd[3] & 0xffbfffff) | ((*val & 0x1) << 22);
}

static void
field_fmt_22_22_3_3_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[3] >> 22) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_23_23_13_13_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 23;
    info.maxbit = 23;
    return info;
}

static void
field_fmt_23_23_13_13_set(uint32_t *pmd, uint32_t *val)
{
    pmd[13] = (pmd[13] & 0xff7fffff) | ((*val & 0x1) << 23);
}

static void
field_fmt_23_23_13_13_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[13] >> 23) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_243_243_6_6_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 243;
    info.maxbit = 243;
    return info;
}

static void
field_fmt_243_243_6_6_set(uint32_t *pmd, uint32_t *val)
{
    pmd[6] = (pmd[6] & 0xfff7ffff) | ((*val & 0x1) << 19);
}

static void
field_fmt_243_243_6_6_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[6] >> 19) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_244_253_6_6_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 244;
    info.maxbit = 253;
    return info;
}

static void
field_fmt_244_253_6_6_set(uint32_t *pmd, uint32_t *val)
{
    pmd[6] = (pmd[6] & 0xc00fffff) | ((*val & 0x3ff) << 20);
}

static void
field_fmt_244_253_6_6_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[6] >> 20) & 0x3ff;
}

static bcmpkt_field_info_t
field_fmt_24_24_13_13_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 24;
    info.maxbit = 24;
    return info;
}

static void
field_fmt_24_24_13_13_set(uint32_t *pmd, uint32_t *val)
{
    pmd[13] = (pmd[13] & 0xfeffffff) | ((*val & 0x1) << 24);
}

static void
field_fmt_24_24_13_13_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[13] >> 24) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_24_36_3_2_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 24;
    info.maxbit = 36;
    return info;
}

static void
field_fmt_24_36_3_2_set(uint32_t *pmd, uint32_t *val)
{
    pmd[3] = (pmd[3] & 0xffffff) | (*val << 24);
    pmd[2] = (pmd[2] & 0xffffffe0) | ((*val >> 8) & 0x1f);
}

static void
field_fmt_24_36_3_2_get(uint32_t *pmd, uint32_t *val)
{
    *val = ((pmd[3] >> 24) | (pmd[2] << 8)) & 0x1fff;
}

static bcmpkt_field_info_t
field_fmt_254_254_6_6_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 254;
    info.maxbit = 254;
    return info;
}

static void
field_fmt_254_254_6_6_set(uint32_t *pmd, uint32_t *val)
{
    pmd[6] = (pmd[6] & 0xbfffffff) | ((*val & 0x1) << 30);
}

static void
field_fmt_254_254_6_6_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[6] >> 30) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_255_286_6_5_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 255;
    info.maxbit = 286;
    return info;
}

static void
field_fmt_255_286_6_5_set(uint32_t *pmd, uint32_t *val)
{
    pmd[6] = (pmd[6] & 0x7fffffff) | (*val << 31);
    pmd[5] = (pmd[5] & 0x80000000) | ((*val >> 1) & 0x7fffffff);
}

static void
field_fmt_255_286_6_5_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[6] >> 31) | (pmd[5] << 1);
}

static bcmpkt_field_info_t
field_fmt_25_25_13_13_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 25;
    info.maxbit = 25;
    return info;
}

static void
field_fmt_25_25_13_13_set(uint32_t *pmd, uint32_t *val)
{
    pmd[13] = (pmd[13] & 0xfdffffff) | ((*val & 0x1) << 25);
}

static void
field_fmt_25_25_13_13_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[13] >> 25) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_26_26_13_13_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 26;
    info.maxbit = 26;
    return info;
}

static void
field_fmt_26_26_13_13_set(uint32_t *pmd, uint32_t *val)
{
    pmd[13] = (pmd[13] & 0xfbffffff) | ((*val & 0x1) << 26);
}

static void
field_fmt_26_26_13_13_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[13] >> 26) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_26_26_3_3_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 26;
    info.maxbit = 26;
    return info;
}

static void
field_fmt_26_26_3_3_set(uint32_t *pmd, uint32_t *val)
{
    pmd[3] = (pmd[3] & 0xfbffffff) | ((*val & 0x1) << 26);
}

static void
field_fmt_26_26_3_3_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[3] >> 26) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_27_27_13_13_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 27;
    info.maxbit = 27;
    return info;
}

static void
field_fmt_27_27_13_13_set(uint32_t *pmd, uint32_t *val)
{
    pmd[13] = (pmd[13] & 0xf7ffffff) | ((*val & 0x1) << 27);
}

static void
field_fmt_27_27_13_13_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[13] >> 27) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_27_42_3_2_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 27;
    info.maxbit = 42;
    return info;
}

static void
field_fmt_27_42_3_2_set(uint32_t *pmd, uint32_t *val)
{
    pmd[3] = (pmd[3] & 0x7ffffff) | (*val << 27);
    pmd[2] = (pmd[2] & 0xfffff800) | ((*val >> 5) & 0x7ff);
}

static void
field_fmt_27_42_3_2_get(uint32_t *pmd, uint32_t *val)
{
    *val = ((pmd[3] >> 27) | (pmd[2] << 5)) & 0xffff;
}

static bcmpkt_field_info_t
field_fmt_287_302_5_4_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 287;
    info.maxbit = 302;
    return info;
}

static void
field_fmt_287_302_5_4_set(uint32_t *pmd, uint32_t *val)
{
    pmd[5] = (pmd[5] & 0x7fffffff) | (*val << 31);
    pmd[4] = (pmd[4] & 0xffff8000) | ((*val >> 1) & 0x7fff);
}

static void
field_fmt_287_302_5_4_get(uint32_t *pmd, uint32_t *val)
{
    *val = ((pmd[5] >> 31) | (pmd[4] << 1)) & 0xffff;
}

static bcmpkt_field_info_t
field_fmt_28_28_13_13_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 28;
    info.maxbit = 28;
    return info;
}

static void
field_fmt_28_28_13_13_set(uint32_t *pmd, uint32_t *val)
{
    pmd[13] = (pmd[13] & 0xefffffff) | ((*val & 0x1) << 28);
}

static void
field_fmt_28_28_13_13_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[13] >> 28) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_29_29_13_13_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 29;
    info.maxbit = 29;
    return info;
}

static void
field_fmt_29_29_13_13_set(uint32_t *pmd, uint32_t *val)
{
    pmd[13] = (pmd[13] & 0xdfffffff) | ((*val & 0x1) << 29);
}

static void
field_fmt_29_29_13_13_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[13] >> 29) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_2_2_13_13_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 2;
    info.maxbit = 2;
    return info;
}

static void
field_fmt_2_2_13_13_set(uint32_t *pmd, uint32_t *val)
{
    pmd[13] = (pmd[13] & 0xfffffffb) | ((*val & 0x1) << 2);
}

static void
field_fmt_2_2_13_13_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[13] >> 2) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_303_303_4_4_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 303;
    info.maxbit = 303;
    return info;
}

static void
field_fmt_303_303_4_4_set(uint32_t *pmd, uint32_t *val)
{
    pmd[4] = (pmd[4] & 0xffff7fff) | ((*val & 0x1) << 15);
}

static void
field_fmt_303_303_4_4_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[4] >> 15) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_304_307_4_4_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 304;
    info.maxbit = 307;
    return info;
}

static void
field_fmt_304_307_4_4_set(uint32_t *pmd, uint32_t *val)
{
    pmd[4] = (pmd[4] & 0xfff0ffff) | ((*val & 0xf) << 16);
}

static void
field_fmt_304_307_4_4_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[4] >> 16) & 0xf;
}

static bcmpkt_field_info_t
field_fmt_308_308_4_4_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 308;
    info.maxbit = 308;
    return info;
}

static void
field_fmt_308_308_4_4_set(uint32_t *pmd, uint32_t *val)
{
    pmd[4] = (pmd[4] & 0xffefffff) | ((*val & 0x1) << 20);
}

static void
field_fmt_308_308_4_4_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[4] >> 20) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_309_309_4_4_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 309;
    info.maxbit = 309;
    return info;
}

static void
field_fmt_309_309_4_4_set(uint32_t *pmd, uint32_t *val)
{
    pmd[4] = (pmd[4] & 0xffdfffff) | ((*val & 0x1) << 21);
}

static void
field_fmt_309_309_4_4_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[4] >> 21) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_30_30_13_13_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 30;
    info.maxbit = 30;
    return info;
}

static void
field_fmt_30_30_13_13_set(uint32_t *pmd, uint32_t *val)
{
    pmd[13] = (pmd[13] & 0xbfffffff) | ((*val & 0x1) << 30);
}

static void
field_fmt_30_30_13_13_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[13] >> 30) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_310_311_4_4_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 310;
    info.maxbit = 311;
    return info;
}

static void
field_fmt_310_311_4_4_set(uint32_t *pmd, uint32_t *val)
{
    pmd[4] = (pmd[4] & 0xff3fffff) | ((*val & 0x3) << 22);
}

static void
field_fmt_310_311_4_4_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[4] >> 22) & 0x3;
}

static bcmpkt_field_info_t
field_fmt_312_318_4_4_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 312;
    info.maxbit = 318;
    return info;
}

static void
field_fmt_312_318_4_4_set(uint32_t *pmd, uint32_t *val)
{
    pmd[4] = (pmd[4] & 0x80ffffff) | ((*val & 0x7f) << 24);
}

static void
field_fmt_312_318_4_4_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[4] >> 24) & 0x7f;
}

static bcmpkt_field_info_t
field_fmt_31_31_13_13_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 31;
    info.maxbit = 31;
    return info;
}

static void
field_fmt_31_31_13_13_set(uint32_t *pmd, uint32_t *val)
{
    pmd[13] = (pmd[13] & 0x7fffffff) | (*val << 31);
}

static void
field_fmt_31_31_13_13_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[13] >> 31) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_320_447_3_0_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 320;
    info.maxbit = 447;
    return info;
}

static void
field_fmt_320_447_3_0_set(uint32_t *pmd, uint32_t *val)
{
    pmd[3] = val[0];
    pmd[2] = val[1];
    pmd[1] = val[2];
    pmd[0] = val[3];
}

static void
field_fmt_320_447_3_0_get(uint32_t *pmd, uint32_t *val)
{
    val[0] = pmd[3];
    val[1] = pmd[2];
    val[2] = pmd[1];
    val[3] = pmd[0];
}

static bcmpkt_field_info_t
field_fmt_32_32_12_12_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 32;
    info.maxbit = 32;
    return info;
}

static void
field_fmt_32_32_12_12_set(uint32_t *pmd, uint32_t *val)
{
    pmd[12] = (pmd[12] & 0xfffffffe) | (*val & 0x1);
}

static void
field_fmt_32_32_12_12_get(uint32_t *pmd, uint32_t *val)
{
    *val = pmd[12] & 0x1;
}

static bcmpkt_field_info_t
field_fmt_33_33_12_12_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 33;
    info.maxbit = 33;
    return info;
}

static void
field_fmt_33_33_12_12_set(uint32_t *pmd, uint32_t *val)
{
    pmd[12] = (pmd[12] & 0xfffffffd) | ((*val & 0x1) << 1);
}

static void
field_fmt_33_33_12_12_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[12] >> 1) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_34_34_12_12_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 34;
    info.maxbit = 34;
    return info;
}

static void
field_fmt_34_34_12_12_set(uint32_t *pmd, uint32_t *val)
{
    pmd[12] = (pmd[12] & 0xfffffffb) | ((*val & 0x1) << 2);
}

static void
field_fmt_34_34_12_12_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[12] >> 2) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_34_37_2_2_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 34;
    info.maxbit = 37;
    return info;
}

static void
field_fmt_34_37_2_2_set(uint32_t *pmd, uint32_t *val)
{
    pmd[2] = (pmd[2] & 0xffffffc3) | ((*val & 0xf) << 2);
}

static void
field_fmt_34_37_2_2_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[2] >> 2) & 0xf;
}

static bcmpkt_field_info_t
field_fmt_35_35_12_12_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 35;
    info.maxbit = 35;
    return info;
}

static void
field_fmt_35_35_12_12_set(uint32_t *pmd, uint32_t *val)
{
    pmd[12] = (pmd[12] & 0xfffffff7) | ((*val & 0x1) << 3);
}

static void
field_fmt_35_35_12_12_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[12] >> 3) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_36_36_12_12_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 36;
    info.maxbit = 36;
    return info;
}

static void
field_fmt_36_36_12_12_set(uint32_t *pmd, uint32_t *val)
{
    pmd[12] = (pmd[12] & 0xffffffef) | ((*val & 0x1) << 4);
}

static void
field_fmt_36_36_12_12_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[12] >> 4) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_37_37_12_12_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 37;
    info.maxbit = 37;
    return info;
}

static void
field_fmt_37_37_12_12_set(uint32_t *pmd, uint32_t *val)
{
    pmd[12] = (pmd[12] & 0xffffffdf) | ((*val & 0x1) << 5);
}

static void
field_fmt_37_37_12_12_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[12] >> 5) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_37_46_2_2_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 37;
    info.maxbit = 46;
    return info;
}

static void
field_fmt_37_46_2_2_set(uint32_t *pmd, uint32_t *val)
{
    pmd[2] = (pmd[2] & 0xffff801f) | ((*val & 0x3ff) << 5);
}

static void
field_fmt_37_46_2_2_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[2] >> 5) & 0x3ff;
}

static bcmpkt_field_info_t
field_fmt_38_38_12_12_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 38;
    info.maxbit = 38;
    return info;
}

static void
field_fmt_38_38_12_12_set(uint32_t *pmd, uint32_t *val)
{
    pmd[12] = (pmd[12] & 0xffffffbf) | ((*val & 0x1) << 6);
}

static void
field_fmt_38_38_12_12_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[12] >> 6) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_38_38_2_2_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 38;
    info.maxbit = 38;
    return info;
}

static void
field_fmt_38_38_2_2_set(uint32_t *pmd, uint32_t *val)
{
    pmd[2] = (pmd[2] & 0xffffffbf) | ((*val & 0x1) << 6);
}

static void
field_fmt_38_38_2_2_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[2] >> 6) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_39_39_12_12_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 39;
    info.maxbit = 39;
    return info;
}

static void
field_fmt_39_39_12_12_set(uint32_t *pmd, uint32_t *val)
{
    pmd[12] = (pmd[12] & 0xffffff7f) | ((*val & 0x1) << 7);
}

static void
field_fmt_39_39_12_12_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[12] >> 7) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_39_39_2_2_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 39;
    info.maxbit = 39;
    return info;
}

static void
field_fmt_39_39_2_2_set(uint32_t *pmd, uint32_t *val)
{
    pmd[2] = (pmd[2] & 0xffffff7f) | ((*val & 0x1) << 7);
}

static void
field_fmt_39_39_2_2_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[2] >> 7) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_3_3_13_13_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 3;
    info.maxbit = 3;
    return info;
}

static void
field_fmt_3_3_13_13_set(uint32_t *pmd, uint32_t *val)
{
    pmd[13] = (pmd[13] & 0xfffffff7) | ((*val & 0x1) << 3);
}

static void
field_fmt_3_3_13_13_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[13] >> 3) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_40_40_12_12_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 40;
    info.maxbit = 40;
    return info;
}

static void
field_fmt_40_40_12_12_set(uint32_t *pmd, uint32_t *val)
{
    pmd[12] = (pmd[12] & 0xfffffeff) | ((*val & 0x1) << 8);
}

static void
field_fmt_40_40_12_12_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[12] >> 8) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_40_43_2_2_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 40;
    info.maxbit = 43;
    return info;
}

static void
field_fmt_40_43_2_2_set(uint32_t *pmd, uint32_t *val)
{
    pmd[2] = (pmd[2] & 0xfffff0ff) | ((*val & 0xf) << 8);
}

static void
field_fmt_40_43_2_2_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[2] >> 8) & 0xf;
}

static bcmpkt_field_info_t
field_fmt_41_41_12_12_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 41;
    info.maxbit = 41;
    return info;
}

static void
field_fmt_41_41_12_12_set(uint32_t *pmd, uint32_t *val)
{
    pmd[12] = (pmd[12] & 0xfffffdff) | ((*val & 0x1) << 9);
}

static void
field_fmt_41_41_12_12_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[12] >> 9) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_42_42_12_12_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 42;
    info.maxbit = 42;
    return info;
}

static void
field_fmt_42_42_12_12_set(uint32_t *pmd, uint32_t *val)
{
    pmd[12] = (pmd[12] & 0xfffffbff) | ((*val & 0x1) << 10);
}

static void
field_fmt_42_42_12_12_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[12] >> 10) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_43_43_12_12_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 43;
    info.maxbit = 43;
    return info;
}

static void
field_fmt_43_43_12_12_set(uint32_t *pmd, uint32_t *val)
{
    pmd[12] = (pmd[12] & 0xfffff7ff) | ((*val & 0x1) << 11);
}

static void
field_fmt_43_43_12_12_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[12] >> 11) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_43_46_2_2_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 43;
    info.maxbit = 46;
    return info;
}

static void
field_fmt_43_46_2_2_set(uint32_t *pmd, uint32_t *val)
{
    pmd[2] = (pmd[2] & 0xffff87ff) | ((*val & 0xf) << 11);
}

static void
field_fmt_43_46_2_2_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[2] >> 11) & 0xf;
}

static bcmpkt_field_info_t
field_fmt_44_44_12_12_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 44;
    info.maxbit = 44;
    return info;
}

static void
field_fmt_44_44_12_12_set(uint32_t *pmd, uint32_t *val)
{
    pmd[12] = (pmd[12] & 0xffffefff) | ((*val & 0x1) << 12);
}

static void
field_fmt_44_44_12_12_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[12] >> 12) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_44_46_2_2_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 44;
    info.maxbit = 46;
    return info;
}

static void
field_fmt_44_46_2_2_set(uint32_t *pmd, uint32_t *val)
{
    pmd[2] = (pmd[2] & 0xffff8fff) | ((*val & 0x7) << 12);
}

static void
field_fmt_44_46_2_2_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[2] >> 12) & 0x7;
}

static bcmpkt_field_info_t
field_fmt_45_45_12_12_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 45;
    info.maxbit = 45;
    return info;
}

static void
field_fmt_45_45_12_12_set(uint32_t *pmd, uint32_t *val)
{
    pmd[12] = (pmd[12] & 0xffffdfff) | ((*val & 0x1) << 13);
}

static void
field_fmt_45_45_12_12_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[12] >> 13) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_46_46_12_12_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 46;
    info.maxbit = 46;
    return info;
}

static void
field_fmt_46_46_12_12_set(uint32_t *pmd, uint32_t *val)
{
    pmd[12] = (pmd[12] & 0xffffbfff) | ((*val & 0x1) << 14);
}

static void
field_fmt_46_46_12_12_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[12] >> 14) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_47_47_12_12_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 47;
    info.maxbit = 47;
    return info;
}

static void
field_fmt_47_47_12_12_set(uint32_t *pmd, uint32_t *val)
{
    pmd[12] = (pmd[12] & 0xffff7fff) | ((*val & 0x1) << 15);
}

static void
field_fmt_47_47_12_12_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[12] >> 15) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_47_47_2_2_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 47;
    info.maxbit = 47;
    return info;
}

static void
field_fmt_47_47_2_2_set(uint32_t *pmd, uint32_t *val)
{
    pmd[2] = (pmd[2] & 0xffff7fff) | ((*val & 0x1) << 15);
}

static void
field_fmt_47_47_2_2_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[2] >> 15) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_47_48_2_2_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 47;
    info.maxbit = 48;
    return info;
}

static void
field_fmt_47_48_2_2_set(uint32_t *pmd, uint32_t *val)
{
    pmd[2] = (pmd[2] & 0xfffe7fff) | ((*val & 0x3) << 15);
}

static void
field_fmt_47_48_2_2_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[2] >> 15) & 0x3;
}

static bcmpkt_field_info_t
field_fmt_48_48_12_12_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 48;
    info.maxbit = 48;
    return info;
}

static void
field_fmt_48_48_12_12_set(uint32_t *pmd, uint32_t *val)
{
    pmd[12] = (pmd[12] & 0xfffeffff) | ((*val & 0x1) << 16);
}

static void
field_fmt_48_48_12_12_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[12] >> 16) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_48_48_2_2_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 48;
    info.maxbit = 48;
    return info;
}

static void
field_fmt_48_48_2_2_set(uint32_t *pmd, uint32_t *val)
{
    pmd[2] = (pmd[2] & 0xfffeffff) | ((*val & 0x1) << 16);
}

static void
field_fmt_48_48_2_2_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[2] >> 16) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_49_49_12_12_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 49;
    info.maxbit = 49;
    return info;
}

static void
field_fmt_49_49_12_12_set(uint32_t *pmd, uint32_t *val)
{
    pmd[12] = (pmd[12] & 0xfffdffff) | ((*val & 0x1) << 17);
}

static void
field_fmt_49_49_12_12_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[12] >> 17) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_49_50_2_2_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 49;
    info.maxbit = 50;
    return info;
}

static void
field_fmt_49_50_2_2_set(uint32_t *pmd, uint32_t *val)
{
    pmd[2] = (pmd[2] & 0xfff9ffff) | ((*val & 0x3) << 17);
}

static void
field_fmt_49_50_2_2_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[2] >> 17) & 0x3;
}

static bcmpkt_field_info_t
field_fmt_49_52_2_2_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 49;
    info.maxbit = 52;
    return info;
}

static void
field_fmt_49_52_2_2_set(uint32_t *pmd, uint32_t *val)
{
    pmd[2] = (pmd[2] & 0xffe1ffff) | ((*val & 0xf) << 17);
}

static void
field_fmt_49_52_2_2_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[2] >> 17) & 0xf;
}

static bcmpkt_field_info_t
field_fmt_4_4_13_13_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 4;
    info.maxbit = 4;
    return info;
}

static void
field_fmt_4_4_13_13_set(uint32_t *pmd, uint32_t *val)
{
    pmd[13] = (pmd[13] & 0xffffffef) | ((*val & 0x1) << 4);
}

static void
field_fmt_4_4_13_13_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[13] >> 4) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_50_50_12_12_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 50;
    info.maxbit = 50;
    return info;
}

static void
field_fmt_50_50_12_12_set(uint32_t *pmd, uint32_t *val)
{
    pmd[12] = (pmd[12] & 0xfffbffff) | ((*val & 0x1) << 18);
}

static void
field_fmt_50_50_12_12_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[12] >> 18) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_51_51_2_2_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 51;
    info.maxbit = 51;
    return info;
}

static void
field_fmt_51_51_2_2_set(uint32_t *pmd, uint32_t *val)
{
    pmd[2] = (pmd[2] & 0xfff7ffff) | ((*val & 0x1) << 19);
}

static void
field_fmt_51_51_2_2_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[2] >> 19) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_52_59_2_2_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 52;
    info.maxbit = 59;
    return info;
}

static void
field_fmt_52_59_2_2_set(uint32_t *pmd, uint32_t *val)
{
    pmd[2] = (pmd[2] & 0xf00fffff) | ((*val & 0xff) << 20);
}

static void
field_fmt_52_59_2_2_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[2] >> 20) & 0xff;
}

static bcmpkt_field_info_t
field_fmt_53_54_2_2_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 53;
    info.maxbit = 54;
    return info;
}

static void
field_fmt_53_54_2_2_set(uint32_t *pmd, uint32_t *val)
{
    pmd[2] = (pmd[2] & 0xff9fffff) | ((*val & 0x3) << 21);
}

static void
field_fmt_53_54_2_2_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[2] >> 21) & 0x3;
}

static bcmpkt_field_info_t
field_fmt_55_58_2_2_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 55;
    info.maxbit = 58;
    return info;
}

static void
field_fmt_55_58_2_2_set(uint32_t *pmd, uint32_t *val)
{
    pmd[2] = (pmd[2] & 0xf87fffff) | ((*val & 0xf) << 23);
}

static void
field_fmt_55_58_2_2_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[2] >> 23) & 0xf;
}

static bcmpkt_field_info_t
field_fmt_59_59_2_2_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 59;
    info.maxbit = 59;
    return info;
}

static void
field_fmt_59_59_2_2_set(uint32_t *pmd, uint32_t *val)
{
    pmd[2] = (pmd[2] & 0xf7ffffff) | ((*val & 0x1) << 27);
}

static void
field_fmt_59_59_2_2_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[2] >> 27) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_5_5_13_13_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 5;
    info.maxbit = 5;
    return info;
}

static void
field_fmt_5_5_13_13_set(uint32_t *pmd, uint32_t *val)
{
    pmd[13] = (pmd[13] & 0xffffffdf) | ((*val & 0x1) << 5);
}

static void
field_fmt_5_5_13_13_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[13] >> 5) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_60_60_2_2_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 60;
    info.maxbit = 60;
    return info;
}

static void
field_fmt_60_60_2_2_set(uint32_t *pmd, uint32_t *val)
{
    pmd[2] = (pmd[2] & 0xefffffff) | ((*val & 0x1) << 28);
}

static void
field_fmt_60_60_2_2_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[2] >> 28) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_60_62_2_2_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 60;
    info.maxbit = 62;
    return info;
}

static void
field_fmt_60_62_2_2_set(uint32_t *pmd, uint32_t *val)
{
    pmd[2] = (pmd[2] & 0x8fffffff) | ((*val & 0x7) << 28);
}

static void
field_fmt_60_62_2_2_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[2] >> 28) & 0x7;
}

static bcmpkt_field_info_t
field_fmt_61_61_2_2_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 61;
    info.maxbit = 61;
    return info;
}

static void
field_fmt_61_61_2_2_set(uint32_t *pmd, uint32_t *val)
{
    pmd[2] = (pmd[2] & 0xdfffffff) | ((*val & 0x1) << 29);
}

static void
field_fmt_61_61_2_2_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[2] >> 29) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_62_62_2_2_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 62;
    info.maxbit = 62;
    return info;
}

static void
field_fmt_62_62_2_2_set(uint32_t *pmd, uint32_t *val)
{
    pmd[2] = (pmd[2] & 0xbfffffff) | ((*val & 0x1) << 30);
}

static void
field_fmt_62_62_2_2_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[2] >> 30) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_63_63_2_2_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 63;
    info.maxbit = 63;
    return info;
}

static void
field_fmt_63_63_2_2_set(uint32_t *pmd, uint32_t *val)
{
    pmd[2] = (pmd[2] & 0x7fffffff) | (*val << 31);
}

static void
field_fmt_63_63_2_2_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[2] >> 31) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_64_64_1_1_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 64;
    info.maxbit = 64;
    return info;
}

static void
field_fmt_64_64_1_1_set(uint32_t *pmd, uint32_t *val)
{
    pmd[1] = (pmd[1] & 0xfffffffe) | (*val & 0x1);
}

static void
field_fmt_64_64_1_1_get(uint32_t *pmd, uint32_t *val)
{
    *val = pmd[1] & 0x1;
}

static bcmpkt_field_info_t
field_fmt_64_67_11_11_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 64;
    info.maxbit = 67;
    return info;
}

static void
field_fmt_64_67_11_11_set(uint32_t *pmd, uint32_t *val)
{
    pmd[11] = (pmd[11] & 0xfffffff0) | (*val & 0xf);
}

static void
field_fmt_64_67_11_11_get(uint32_t *pmd, uint32_t *val)
{
    *val = pmd[11] & 0xf;
}

static bcmpkt_field_info_t
field_fmt_65_77_1_1_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 65;
    info.maxbit = 77;
    return info;
}

static void
field_fmt_65_77_1_1_set(uint32_t *pmd, uint32_t *val)
{
    pmd[1] = (pmd[1] & 0xffffc001) | ((*val & 0x1fff) << 1);
}

static void
field_fmt_65_77_1_1_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[1] >> 1) & 0x1fff;
}

static bcmpkt_field_info_t
field_fmt_68_79_11_11_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 68;
    info.maxbit = 79;
    return info;
}

static void
field_fmt_68_79_11_11_set(uint32_t *pmd, uint32_t *val)
{
    pmd[11] = (pmd[11] & 0xffff000f) | ((*val & 0xfff) << 4);
}

static void
field_fmt_68_79_11_11_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[11] >> 4) & 0xfff;
}

static bcmpkt_field_info_t
field_fmt_6_6_13_13_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 6;
    info.maxbit = 6;
    return info;
}

static void
field_fmt_6_6_13_13_set(uint32_t *pmd, uint32_t *val)
{
    pmd[13] = (pmd[13] & 0xffffffbf) | ((*val & 0x1) << 6);
}

static void
field_fmt_6_6_13_13_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[13] >> 6) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_78_90_1_1_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 78;
    info.maxbit = 90;
    return info;
}

static void
field_fmt_78_90_1_1_set(uint32_t *pmd, uint32_t *val)
{
    pmd[1] = (pmd[1] & 0xf8003fff) | ((*val & 0x1fff) << 14);
}

static void
field_fmt_78_90_1_1_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[1] >> 14) & 0x1fff;
}

static bcmpkt_field_info_t
field_fmt_7_7_13_13_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 7;
    info.maxbit = 7;
    return info;
}

static void
field_fmt_7_7_13_13_set(uint32_t *pmd, uint32_t *val)
{
    pmd[13] = (pmd[13] & 0xffffff7f) | ((*val & 0x1) << 7);
}

static void
field_fmt_7_7_13_13_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[13] >> 7) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_80_81_11_11_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 80;
    info.maxbit = 81;
    return info;
}

static void
field_fmt_80_81_11_11_set(uint32_t *pmd, uint32_t *val)
{
    pmd[11] = (pmd[11] & 0xfffcffff) | ((*val & 0x3) << 16);
}

static void
field_fmt_80_81_11_11_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[11] >> 16) & 0x3;
}

static bcmpkt_field_info_t
field_fmt_80_83_11_11_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 80;
    info.maxbit = 83;
    return info;
}

static void
field_fmt_80_83_11_11_set(uint32_t *pmd, uint32_t *val)
{
    pmd[11] = (pmd[11] & 0xfff0ffff) | ((*val & 0xf) << 16);
}

static void
field_fmt_80_83_11_11_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[11] >> 16) & 0xf;
}

static bcmpkt_field_info_t
field_fmt_81_84_1_1_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 81;
    info.maxbit = 84;
    return info;
}

static void
field_fmt_81_84_1_1_set(uint32_t *pmd, uint32_t *val)
{
    pmd[1] = (pmd[1] & 0xffe1ffff) | ((*val & 0xf) << 17);
}

static void
field_fmt_81_84_1_1_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[1] >> 17) & 0xf;
}

static bcmpkt_field_info_t
field_fmt_82_89_11_11_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 82;
    info.maxbit = 89;
    return info;
}

static void
field_fmt_82_89_11_11_set(uint32_t *pmd, uint32_t *val)
{
    pmd[11] = (pmd[11] & 0xfc03ffff) | ((*val & 0xff) << 18);
}

static void
field_fmt_82_89_11_11_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[11] >> 18) & 0xff;
}

static bcmpkt_field_info_t
field_fmt_85_88_1_1_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 85;
    info.maxbit = 88;
    return info;
}

static void
field_fmt_85_88_1_1_set(uint32_t *pmd, uint32_t *val)
{
    pmd[1] = (pmd[1] & 0xfe1fffff) | ((*val & 0xf) << 21);
}

static void
field_fmt_85_88_1_1_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[1] >> 21) & 0xf;
}

static bcmpkt_field_info_t
field_fmt_85_92_1_1_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 85;
    info.maxbit = 92;
    return info;
}

static void
field_fmt_85_92_1_1_set(uint32_t *pmd, uint32_t *val)
{
    pmd[1] = (pmd[1] & 0xe01fffff) | ((*val & 0xff) << 21);
}

static void
field_fmt_85_92_1_1_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[1] >> 21) & 0xff;
}

static bcmpkt_field_info_t
field_fmt_89_90_1_1_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 89;
    info.maxbit = 90;
    return info;
}

static void
field_fmt_89_90_1_1_set(uint32_t *pmd, uint32_t *val)
{
    pmd[1] = (pmd[1] & 0xf9ffffff) | ((*val & 0x3) << 25);
}

static void
field_fmt_89_90_1_1_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[1] >> 25) & 0x3;
}

static bcmpkt_field_info_t
field_fmt_8_8_13_13_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 8;
    info.maxbit = 8;
    return info;
}

static void
field_fmt_8_8_13_13_set(uint32_t *pmd, uint32_t *val)
{
    pmd[13] = (pmd[13] & 0xfffffeff) | ((*val & 0x1) << 8);
}

static void
field_fmt_8_8_13_13_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[13] >> 8) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_8_8_3_3_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 8;
    info.maxbit = 8;
    return info;
}

static void
field_fmt_8_8_3_3_set(uint32_t *pmd, uint32_t *val)
{
    pmd[3] = (pmd[3] & 0xfffffeff) | ((*val & 0x1) << 8);
}

static void
field_fmt_8_8_3_3_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[3] >> 8) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_90_95_11_11_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 90;
    info.maxbit = 95;
    return info;
}

static void
field_fmt_90_95_11_11_set(uint32_t *pmd, uint32_t *val)
{
    pmd[11] = (pmd[11] & 0x3ffffff) | (*val << 26);
}

static void
field_fmt_90_95_11_11_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[11] >> 26) & 0x3f;
}

static bcmpkt_field_info_t
field_fmt_91_91_1_1_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 91;
    info.maxbit = 91;
    return info;
}

static void
field_fmt_91_91_1_1_set(uint32_t *pmd, uint32_t *val)
{
    pmd[1] = (pmd[1] & 0xf7ffffff) | ((*val & 0x1) << 27);
}

static void
field_fmt_91_91_1_1_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[1] >> 27) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_91_92_1_1_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 91;
    info.maxbit = 92;
    return info;
}

static void
field_fmt_91_92_1_1_set(uint32_t *pmd, uint32_t *val)
{
    pmd[1] = (pmd[1] & 0xe7ffffff) | ((*val & 0x3) << 27);
}

static void
field_fmt_91_92_1_1_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[1] >> 27) & 0x3;
}

static bcmpkt_field_info_t
field_fmt_9_9_13_13_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 9;
    info.maxbit = 9;
    return info;
}

static void
field_fmt_9_9_13_13_set(uint32_t *pmd, uint32_t *val)
{
    pmd[13] = (pmd[13] & 0xfffffdff) | ((*val & 0x1) << 9);
}

static void
field_fmt_9_9_13_13_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[13] >> 9) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_9_9_3_3_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 9;
    info.maxbit = 9;
    return info;
}

static void
field_fmt_9_9_3_3_set(uint32_t *pmd, uint32_t *val)
{
    pmd[3] = (pmd[3] & 0xfffffdff) | ((*val & 0x1) << 9);
}

static void
field_fmt_9_9_3_3_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[3] >> 9) & 0x1;
}

static const shr_enum_map_t bcm78914_b0_rxpmd_reason_type_names[] =
{
    BCM78914_B0_RXPMD_REASON_TYPE_NAME_MAP_INIT
};

static bcmpkt_pmd_field_t bcm78914_b0_rxpmd_fields[BCM78914_B0_RXPMD_COUNT] = {
    {"REASON",2, field_fmt_0_63_13_12_info, field_fmt_0_63_13_12_set, field_fmt_0_63_13_12_get, NULL, 0},
    {"REASON_TYPE",1, field_fmt_64_67_11_11_info, field_fmt_64_67_11_11_set, field_fmt_64_67_11_11_get, bcm78914_b0_rxpmd_reason_type_names, 0},
    {"I2E_CLASSID",1, field_fmt_68_79_11_11_info, field_fmt_68_79_11_11_set, field_fmt_68_79_11_11_get, NULL, 0},
    {"RX_BFD_SESSION_INDEX",1, field_fmt_68_79_11_11_info, field_fmt_68_79_11_11_set, field_fmt_68_79_11_11_get, NULL, 0},
    {"I2E_CLASSID_TYPE",1, field_fmt_80_83_11_11_info, field_fmt_80_83_11_11_set, field_fmt_80_83_11_11_get, NULL, 0},
    {"RX_BFD_START_OFFSET_TYPE",1, field_fmt_80_81_11_11_info, field_fmt_80_81_11_11_set, field_fmt_80_81_11_11_get, NULL, 0},
    {"RX_BFD_START_OFFSET",1, field_fmt_82_89_11_11_info, field_fmt_82_89_11_11_set, field_fmt_82_89_11_11_get, NULL, 0},
    {"CPU_COS",1, field_fmt_90_95_11_11_info, field_fmt_90_95_11_11_set, field_fmt_90_95_11_11_get, NULL, 0},
    {"QUEUE_NUM",1, field_fmt_90_95_11_11_info, field_fmt_90_95_11_11_set, field_fmt_90_95_11_11_get, NULL, 0},
    {"ING_L3_INTF",1, field_fmt_115_127_10_10_info, field_fmt_115_127_10_10_set, field_fmt_115_127_10_10_get, NULL, 0},
    {"INCOMING_TAG_STATUS",1, field_fmt_128_128_9_9_info, field_fmt_128_128_9_9_set, field_fmt_128_128_9_9_get, NULL, 0},
    {"ING_OTAG_ACTION",1, field_fmt_129_130_9_9_info, field_fmt_129_130_9_9_set, field_fmt_129_130_9_9_get, NULL, 0},
    {"PKT_LENGTH",1, field_fmt_131_144_9_9_info, field_fmt_131_144_9_9_set, field_fmt_131_144_9_9_get, NULL, 0},
    {"O_NHI",1, field_fmt_145_159_9_9_info, field_fmt_145_159_9_9_set, field_fmt_145_159_9_9_get, NULL, 0},
    {"INCOMING_OPAQUE_TAG_STATUS",1, field_fmt_160_160_8_8_info, field_fmt_160_160_8_8_set, field_fmt_160_160_8_8_get, NULL, 0},
    {"BPDU",1, field_fmt_161_161_8_8_info, field_fmt_161_161_8_8_set, field_fmt_161_161_8_8_get, NULL, 0},
    {"CHANGE_DSCP",1, field_fmt_162_162_8_8_info, field_fmt_162_162_8_8_set, field_fmt_162_162_8_8_get, NULL, 0},
    {"CHANGE_ECN",1, field_fmt_163_163_8_8_info, field_fmt_163_163_8_8_set, field_fmt_163_163_8_8_get, NULL, 0},
    {"DLB_ID_VALID",1, field_fmt_164_164_8_8_info, field_fmt_164_164_8_8_set, field_fmt_164_164_8_8_get, NULL, 0},
    {"DO_NOT_CHANGE_TTL",1, field_fmt_165_165_8_8_info, field_fmt_165_165_8_8_set, field_fmt_165_165_8_8_get, NULL, 0},
    {"DSCP",1, field_fmt_166_171_8_8_info, field_fmt_166_171_8_8_set, field_fmt_166_171_8_8_get, NULL, 0},
    {"SPECIAL_PACKET_TYPE",1, field_fmt_166_168_8_8_info, field_fmt_166_168_8_8_set, field_fmt_166_168_8_8_get, NULL, 0},
    {"ECN",1, field_fmt_172_173_8_8_info, field_fmt_172_173_8_8_set, field_fmt_172_173_8_8_get, NULL, 0},
    {"IP_ROUTED",1, field_fmt_174_174_8_8_info, field_fmt_174_174_8_8_set, field_fmt_174_174_8_8_get, NULL, 0},
    {"L3ONLY",1, field_fmt_175_175_8_8_info, field_fmt_175_175_8_8_set, field_fmt_175_175_8_8_get, NULL, 0},
    {"MATCHED_RULE",1, field_fmt_176_187_8_8_info, field_fmt_176_187_8_8_set, field_fmt_176_187_8_8_get, NULL, 0},
    {"MATCHED_RULE_EP",1, field_fmt_176_184_8_8_info, field_fmt_176_184_8_8_set, field_fmt_176_184_8_8_get, NULL, 0},
    {"IS_EGR_TS",1, field_fmt_185_185_8_8_info, field_fmt_185_185_8_8_set, field_fmt_185_185_8_8_get, NULL, 0},
    {"MTP_INDEX",1, field_fmt_188_190_8_8_info, field_fmt_188_190_8_8_set, field_fmt_188_190_8_8_get, NULL, 0},
    {"OUTER_CFI",1, field_fmt_191_191_8_8_info, field_fmt_191_191_8_8_set, field_fmt_191_191_8_8_get, NULL, 0},
    {"OUTER_PRI",1, field_fmt_192_194_7_7_info, field_fmt_192_194_7_7_set, field_fmt_192_194_7_7_get, NULL, 0},
    {"OUTER_VID",1, field_fmt_195_206_7_7_info, field_fmt_195_206_7_7_set, field_fmt_195_206_7_7_get, NULL, 0},
    {"REPLICATION_OR_NHOP_INDEX",1, field_fmt_207_221_7_7_info, field_fmt_207_221_7_7_set, field_fmt_207_221_7_7_get, NULL, 0},
    {"MODIFIED_PKT",1, field_fmt_222_222_7_7_info, field_fmt_222_222_7_7_set, field_fmt_222_222_7_7_get, NULL, 0},
    {"ENTROPY_LABEL",1, field_fmt_223_242_7_6_info, field_fmt_223_242_7_6_set, field_fmt_223_242_7_6_get, NULL, 0},
    {"SPECIAL_PACKET_INDICATOR",1, field_fmt_243_243_6_6_info, field_fmt_243_243_6_6_set, field_fmt_243_243_6_6_get, NULL, 0},
    {"SRC_PORT_NUM",1, field_fmt_244_253_6_6_info, field_fmt_244_253_6_6_set, field_fmt_244_253_6_6_get, NULL, 0},
    {"SWITCH",1, field_fmt_254_254_6_6_info, field_fmt_254_254_6_6_set, field_fmt_254_254_6_6_get, NULL, 0},
    {"TIMESTAMP",1, field_fmt_255_286_6_5_info, field_fmt_255_286_6_5_set, field_fmt_255_286_6_5_get, NULL, 0},
    {"TIMESTAMP_HI",1, field_fmt_287_302_5_4_info, field_fmt_287_302_5_4_set, field_fmt_287_302_5_4_get, NULL, 0},
    {"IEEE_802_1AS_TIMESTAMP_ENABLED",1, field_fmt_303_303_4_4_info, field_fmt_303_303_4_4_set, field_fmt_303_303_4_4_get, NULL, 0},
    {"TUNNEL_DECAP_TYPE",1, field_fmt_304_307_4_4_info, field_fmt_304_307_4_4_set, field_fmt_304_307_4_4_get, NULL, 0},
    {"UC_SW_COPY_DROPPED",1, field_fmt_308_308_4_4_info, field_fmt_308_308_4_4_set, field_fmt_308_308_4_4_get, NULL, 0},
    {"UNICAST_QUEUE",1, field_fmt_309_309_4_4_info, field_fmt_309_309_4_4_set, field_fmt_309_309_4_4_get, NULL, 0},
    {"INCOMING_INT_HDR_TYPE",1, field_fmt_310_311_4_4_info, field_fmt_310_311_4_4_set, field_fmt_310_311_4_4_get, NULL, 0},
    {"DLB_ID",1, field_fmt_312_318_4_4_info, field_fmt_312_318_4_4_set, field_fmt_312_318_4_4_get, NULL, 0},
    {"MODULE_HDR",4, field_fmt_320_447_3_0_info, field_fmt_320_447_3_0_set, field_fmt_320_447_3_0_get, NULL, 0},

};

static const shr_enum_map_t bcm78914_b0_rxpmd_names[] =
{
    BCM78914_B0_RXPMD_NAME_MAP_INIT
};

bcmpkt_pmd_info_t bcm78914_b0_rxpmd_info_get(void)
{
    bcmpkt_pmd_info_t bcm78914_b0_rxpmd_info = {14, BCM78914_B0_RXPMD_COUNT, bcm78914_b0_rxpmd_names, bcm78914_b0_rxpmd_fields};
    return bcm78914_b0_rxpmd_info;
}

static bcmpkt_pmd_field_t bcm78914_b0_rx_reason_fields[BCM78914_B0_RX_REASON_COUNT] = {
    {"CPU_INVALID_REASON",1, field_fmt_0_0_13_13_info, field_fmt_0_0_13_13_set, field_fmt_0_0_13_13_get, NULL, 0},
    {"CPU_SLF",1, field_fmt_1_1_13_13_info, field_fmt_1_1_13_13_set, field_fmt_1_1_13_13_get, NULL, 0},
    {"CPU_DLF",1, field_fmt_2_2_13_13_info, field_fmt_2_2_13_13_set, field_fmt_2_2_13_13_get, NULL, 0},
    {"CPU_L2MOVE",1, field_fmt_3_3_13_13_info, field_fmt_3_3_13_13_set, field_fmt_3_3_13_13_get, NULL, 0},
    {"CPU_L2CPU",1, field_fmt_4_4_13_13_info, field_fmt_4_4_13_13_set, field_fmt_4_4_13_13_get, NULL, 0},
    {"CPU_L3SRC_MISS",1, field_fmt_5_5_13_13_info, field_fmt_5_5_13_13_set, field_fmt_5_5_13_13_get, NULL, 0},
    {"CPU_L3DST_MISS",1, field_fmt_6_6_13_13_info, field_fmt_6_6_13_13_set, field_fmt_6_6_13_13_get, NULL, 0},
    {"CPU_L3SRC_MOVE",1, field_fmt_7_7_13_13_info, field_fmt_7_7_13_13_set, field_fmt_7_7_13_13_get, NULL, 0},
    {"CPU_MC_MISS",1, field_fmt_8_8_13_13_info, field_fmt_8_8_13_13_set, field_fmt_8_8_13_13_get, NULL, 0},
    {"CPU_IPMC_MISS",1, field_fmt_9_9_13_13_info, field_fmt_9_9_13_13_set, field_fmt_9_9_13_13_get, NULL, 0},
    {"CPU_FFP",1, field_fmt_10_10_13_13_info, field_fmt_10_10_13_13_set, field_fmt_10_10_13_13_get, NULL, 0},
    {"CPU_L3HDR_ERR",1, field_fmt_11_11_13_13_info, field_fmt_11_11_13_13_set, field_fmt_11_11_13_13_get, NULL, 0},
    {"CPU_PROTOCOL_PKT",1, field_fmt_12_12_13_13_info, field_fmt_12_12_13_13_set, field_fmt_12_12_13_13_get, NULL, 0},
    {"CPU_DOS_ATTACK",1, field_fmt_13_13_13_13_info, field_fmt_13_13_13_13_set, field_fmt_13_13_13_13_get, NULL, 0},
    {"CPU_MARTIAN_ADDR",1, field_fmt_14_14_13_13_info, field_fmt_14_14_13_13_set, field_fmt_14_14_13_13_get, NULL, 0},
    {"CPU_TUNNEL_ERR",1, field_fmt_15_15_13_13_info, field_fmt_15_15_13_13_set, field_fmt_15_15_13_13_get, NULL, 0},
    {"CPU_SFLOW_SRC",1, field_fmt_16_16_13_13_info, field_fmt_16_16_13_13_set, field_fmt_16_16_13_13_get, NULL, 0},
    {"CPU_SFLOW_DST",1, field_fmt_17_17_13_13_info, field_fmt_17_17_13_13_set, field_fmt_17_17_13_13_get, NULL, 0},
    {"ICMP_REDIRECT",1, field_fmt_18_18_13_13_info, field_fmt_18_18_13_13_set, field_fmt_18_18_13_13_get, NULL, 0},
    {"L3_SLOWPATH",1, field_fmt_19_19_13_13_info, field_fmt_19_19_13_13_set, field_fmt_19_19_13_13_get, NULL, 0},
    {"PARITY_ERROR",1, field_fmt_20_20_13_13_info, field_fmt_20_20_13_13_set, field_fmt_20_20_13_13_get, NULL, 0},
    {"L3_MTU_CHECK_FAIL",1, field_fmt_21_21_13_13_info, field_fmt_21_21_13_13_set, field_fmt_21_21_13_13_get, NULL, 0},
    {"MPLS_TTL_CHECK",1, field_fmt_22_22_13_13_info, field_fmt_22_22_13_13_set, field_fmt_22_22_13_13_get, NULL, 0},
    {"MPLS_LABEL_MISS",1, field_fmt_23_23_13_13_info, field_fmt_23_23_13_13_set, field_fmt_23_23_13_13_get, NULL, 0},
    {"MPLS_INVALID_ACTION",1, field_fmt_24_24_13_13_info, field_fmt_24_24_13_13_set, field_fmt_24_24_13_13_get, NULL, 0},
    {"MPLS_INVALID_PAYLOAD",1, field_fmt_25_25_13_13_info, field_fmt_25_25_13_13_set, field_fmt_25_25_13_13_get, NULL, 0},
    {"CPU_VFP",1, field_fmt_26_26_13_13_info, field_fmt_26_26_13_13_set, field_fmt_26_26_13_13_get, NULL, 0},
    {"PBT_NONUC_PKT",1, field_fmt_27_27_13_13_info, field_fmt_27_27_13_13_set, field_fmt_27_27_13_13_get, NULL, 0},
    {"L3_NEXT_HOP",1, field_fmt_28_28_13_13_info, field_fmt_28_28_13_13_set, field_fmt_28_28_13_13_get, NULL, 0},
    {"MY_STATION",1, field_fmt_29_29_13_13_info, field_fmt_29_29_13_13_set, field_fmt_29_29_13_13_get, NULL, 0},
    {"TIME_SYNC",1, field_fmt_30_30_13_13_info, field_fmt_30_30_13_13_set, field_fmt_30_30_13_13_get, NULL, 0},
    {"TUNNEL_DECAP_ECN_ERROR",1, field_fmt_31_31_13_13_info, field_fmt_31_31_13_13_set, field_fmt_31_31_13_13_get, NULL, 0},
    {"BFD_SLOWPATH",1, field_fmt_32_32_12_12_info, field_fmt_32_32_12_12_set, field_fmt_32_32_12_12_get, NULL, 0},
    {"BFD_ERROR",1, field_fmt_33_33_12_12_info, field_fmt_33_33_12_12_set, field_fmt_33_33_12_12_get, NULL, 0},
    {"PACKET_TRACE_TO_CPU",1, field_fmt_34_34_12_12_info, field_fmt_34_34_12_12_set, field_fmt_34_34_12_12_get, NULL, 0},
    {"MPLS_UNKNOWN_CONTROL_PKT",1, field_fmt_35_35_12_12_info, field_fmt_35_35_12_12_set, field_fmt_35_35_12_12_get, NULL, 0},
    {"MPLS_ALERT_LABEL",1, field_fmt_36_36_12_12_info, field_fmt_36_36_12_12_set, field_fmt_36_36_12_12_get, NULL, 0},
    {"CPU_IPMC_INTERFACE_MISMATCH",1, field_fmt_37_37_12_12_info, field_fmt_37_37_12_12_set, field_fmt_37_37_12_12_get, NULL, 0},
    {"DLB_MONITOR",1, field_fmt_38_38_12_12_info, field_fmt_38_38_12_12_set, field_fmt_38_38_12_12_get, NULL, 0},
    {"CPU_SFLOW_FLEX",1, field_fmt_39_39_12_12_info, field_fmt_39_39_12_12_set, field_fmt_39_39_12_12_get, NULL, 0},
    {"CPU_UVLAN",1, field_fmt_40_40_12_12_info, field_fmt_40_40_12_12_set, field_fmt_40_40_12_12_get, NULL, 0},
    {"SRV6_ERROR",1, field_fmt_41_41_12_12_info, field_fmt_41_41_12_12_set, field_fmt_41_41_12_12_get, NULL, 0},
    {"VXLAN_VN_ID_MISS",1, field_fmt_42_42_12_12_info, field_fmt_42_42_12_12_set, field_fmt_42_42_12_12_get, NULL, 0},
    {"VXLAN_SIP_MISS",1, field_fmt_43_43_12_12_info, field_fmt_43_43_12_12_set, field_fmt_43_43_12_12_get, NULL, 0},
    {"ADAPT_MISS",1, field_fmt_44_44_12_12_info, field_fmt_44_44_12_12_set, field_fmt_44_44_12_12_get, NULL, 0},
    {"INVALID_GSH_NON_GSH",1, field_fmt_45_45_12_12_info, field_fmt_45_45_12_12_set, field_fmt_45_45_12_12_get, NULL, 0},
    {"APU_POLICY_CTC",1, field_fmt_46_46_12_12_info, field_fmt_46_46_12_12_set, field_fmt_46_46_12_12_get, NULL, 0},
    {"DELAYED_CTC",1, field_fmt_47_47_12_12_info, field_fmt_47_47_12_12_set, field_fmt_47_47_12_12_get, NULL, 0},
    {"PORT_DOWN",1, field_fmt_48_48_12_12_info, field_fmt_48_48_12_12_set, field_fmt_48_48_12_12_get, NULL, 0},
    {"SRV6_CONTROL_PKT",1, field_fmt_49_49_12_12_info, field_fmt_49_49_12_12_set, field_fmt_49_49_12_12_get, NULL, 0},
    {"OUI_COMPRESSION_MISS",1, field_fmt_50_50_12_12_info, field_fmt_50_50_12_12_set, field_fmt_50_50_12_12_get, NULL, 0},

};

static const shr_enum_map_t bcm78914_b0_rx_reason_names[] =
{
    BCM78914_B0_RX_REASON_NAME_MAP_INIT
};

bcmpkt_pmd_info_t bcm78914_b0_rx_reason_info_get(void)
{
    bcmpkt_pmd_info_t bcm78914_b0_rx_reason_info = {14, BCM78914_B0_RX_REASON_COUNT, bcm78914_b0_rx_reason_names, bcm78914_b0_rx_reason_fields};
    return bcm78914_b0_rx_reason_info;
}

static bcmpkt_pmd_field_t bcm78914_b0_ep_rx_reason_fields[BCM78914_B0_EP_RX_REASON_COUNT] = {
    {"EP_CTC",1, field_fmt_0_0_13_13_info, field_fmt_0_0_13_13_set, field_fmt_0_0_13_13_get, NULL, 0},

};

static const shr_enum_map_t bcm78914_b0_ep_rx_reason_names[] =
{
    BCM78914_B0_EP_RX_REASON_NAME_MAP_INIT
};

bcmpkt_pmd_info_t bcm78914_b0_ep_rx_reason_info_get(void)
{
    bcmpkt_pmd_info_t bcm78914_b0_ep_rx_reason_info = {14, BCM78914_B0_EP_RX_REASON_COUNT, bcm78914_b0_ep_rx_reason_names, bcm78914_b0_ep_rx_reason_fields};
    return bcm78914_b0_ep_rx_reason_info;
}

static const shr_enum_map_t bcm78914_b0_txpmd_cpu_tx_destination_type_names[] =
{
    BCM78914_B0_TXPMD_CPU_TX_DESTINATION_TYPE_NAME_MAP_INIT
};

static const shr_enum_map_t bcm78914_b0_txpmd_cpu_tx_dp_names[] =
{
    BCM78914_B0_TXPMD_CPU_TX_DP_NAME_MAP_INIT
};

static const shr_enum_map_t bcm78914_b0_txpmd_sobmh_from_cpu_destination_type_names[] =
{
    BCM78914_B0_TXPMD_SOBMH_FROM_CPU_DESTINATION_TYPE_NAME_MAP_INIT
};

static const shr_enum_map_t bcm78914_b0_txpmd_header_type_names[] =
{
    BCM78914_B0_TXPMD_HEADER_TYPE_NAME_MAP_INIT
};

static const shr_enum_map_t bcm78914_b0_txpmd_start_names[] =
{
    BCM78914_B0_TXPMD_START_NAME_MAP_INIT
};

static bcmpkt_pmd_field_t bcm78914_b0_txpmd_fields[BCM78914_B0_TXPMD_COUNT] = {
    {"CPU_TX::ECMP_MEMBER_ID",1, field_fmt_0_16_3_3_info, field_fmt_0_16_3_3_set, field_fmt_0_16_3_3_get, NULL, 2},
    {"CPU_TX::MCAST_LB_INDEX",1, field_fmt_0_7_3_3_info, field_fmt_0_7_3_3_set, field_fmt_0_7_3_3_get, NULL, 2},
    {"CPU_TX::COOKIE",1, field_fmt_17_25_3_3_info, field_fmt_17_25_3_3_set, field_fmt_17_25_3_3_get, NULL, 2},
    {"CPU_TX::COOKIE_VALID",1, field_fmt_26_26_3_3_info, field_fmt_26_26_3_3_set, field_fmt_26_26_3_3_get, NULL, 2},
    {"CPU_TX::DESTINATION",1, field_fmt_27_42_3_2_info, field_fmt_27_42_3_2_set, field_fmt_27_42_3_2_get, NULL, 2},
    {"CPU_TX::DESTINATION_TYPE",1, field_fmt_43_46_2_2_info, field_fmt_43_46_2_2_set, field_fmt_43_46_2_2_get, bcm78914_b0_txpmd_cpu_tx_destination_type_names, 2},
    {"CPU_TX::DP",1, field_fmt_47_48_2_2_info, field_fmt_47_48_2_2_set, field_fmt_47_48_2_2_get, bcm78914_b0_txpmd_cpu_tx_dp_names, 2},
    {"CPU_TX::INPUT_PRI",1, field_fmt_49_52_2_2_info, field_fmt_49_52_2_2_set, field_fmt_49_52_2_2_get, NULL, 2},
    {"CPU_TX::INT_CN",1, field_fmt_53_54_2_2_info, field_fmt_53_54_2_2_set, field_fmt_53_54_2_2_get, NULL, 2},
    {"CPU_TX::INT_PRI",1, field_fmt_55_58_2_2_info, field_fmt_55_58_2_2_set, field_fmt_55_58_2_2_get, NULL, 2},
    {"CPU_TX::MCAST_LB_INDEX_VLD",1, field_fmt_59_59_2_2_info, field_fmt_59_59_2_2_set, field_fmt_59_59_2_2_get, NULL, 2},
    {"CPU_TX::PKT_PROFILE",1, field_fmt_60_62_2_2_info, field_fmt_60_62_2_2_set, field_fmt_60_62_2_2_get, NULL, 2},
    {"CPU_TX::QOS_FIELDS_VLD",1, field_fmt_63_63_2_2_info, field_fmt_63_63_2_2_set, field_fmt_63_63_2_2_get, NULL, 2},
    {"CPU_TX::ROUTED_PKT",1, field_fmt_64_64_1_1_info, field_fmt_64_64_1_1_set, field_fmt_64_64_1_1_get, NULL, 2},
    {"CPU_TX::SVP",1, field_fmt_65_77_1_1_info, field_fmt_65_77_1_1_set, field_fmt_65_77_1_1_get, NULL, 2},
    {"CPU_TX::VRF",1, field_fmt_78_90_1_1_info, field_fmt_78_90_1_1_set, field_fmt_78_90_1_1_get, NULL, 2},
    {"CPU_TX::VRF_VALID",1, field_fmt_91_91_1_1_info, field_fmt_91_91_1_1_set, field_fmt_91_91_1_1_get, NULL, 2},
    {"SOBMH_FROM_CPU::COOKIE_7_0",1, field_fmt_0_7_3_3_info, field_fmt_0_7_3_3_set, field_fmt_0_7_3_3_get, NULL, 1},
    {"SOBMH_FROM_CPU::IEEE1588_TIMESTAMP_HDR_OFFSET",1, field_fmt_0_7_3_3_info, field_fmt_0_7_3_3_set, field_fmt_0_7_3_3_get, NULL, 1},
    {"SOBMH_FROM_CPU::COOKIE_8",1, field_fmt_8_8_3_3_info, field_fmt_8_8_3_3_set, field_fmt_8_8_3_3_get, NULL, 1},
    {"SOBMH_FROM_CPU::IEEE1588_REGEN_UDP_CHECKSUM",1, field_fmt_8_8_3_3_info, field_fmt_8_8_3_3_set, field_fmt_8_8_3_3_get, NULL, 1},
    {"SOBMH_FROM_CPU::CELL_ERROR",1, field_fmt_9_9_3_3_info, field_fmt_9_9_3_3_set, field_fmt_9_9_3_3_get, NULL, 1},
    {"SOBMH_FROM_CPU::CNG",1, field_fmt_10_11_3_3_info, field_fmt_10_11_3_3_set, field_fmt_10_11_3_3_get, NULL, 1},
    {"SOBMH_FROM_CPU::COS",1, field_fmt_12_17_3_3_info, field_fmt_12_17_3_3_set, field_fmt_12_17_3_3_get, NULL, 1},
    {"SOBMH_FROM_CPU::DESTINATION",1, field_fmt_18_33_3_2_info, field_fmt_18_33_3_2_set, field_fmt_18_33_3_2_get, NULL, 1},
    {"SOBMH_FROM_CPU::DESTINATION_TYPE",1, field_fmt_34_37_2_2_info, field_fmt_34_37_2_2_set, field_fmt_34_37_2_2_get, bcm78914_b0_txpmd_sobmh_from_cpu_destination_type_names, 1},
    {"SOBMH_FROM_CPU::IEEE1588_INGRESS_TIMESTAMP_SIGN",1, field_fmt_38_38_2_2_info, field_fmt_38_38_2_2_set, field_fmt_38_38_2_2_get, NULL, 1},
    {"SOBMH_FROM_CPU::IEEE1588_ONE_STEP_ENABLE",1, field_fmt_39_39_2_2_info, field_fmt_39_39_2_2_set, field_fmt_39_39_2_2_get, NULL, 1},
    {"SOBMH_FROM_CPU::INPUT_PRI",1, field_fmt_40_43_2_2_info, field_fmt_40_43_2_2_set, field_fmt_40_43_2_2_get, NULL, 1},
    {"SOBMH_FROM_CPU::RQE_Q_NUM",1, field_fmt_44_46_2_2_info, field_fmt_44_46_2_2_set, field_fmt_44_46_2_2_get, NULL, 1},
    {"SOBMH_FROM_CPU::SPAP",1, field_fmt_47_48_2_2_info, field_fmt_47_48_2_2_set, field_fmt_47_48_2_2_get, NULL, 1},
    {"SOBMH_FROM_CPU::SPID",1, field_fmt_49_50_2_2_info, field_fmt_49_50_2_2_set, field_fmt_49_50_2_2_get, NULL, 1},
    {"SOBMH_FROM_CPU::SPID_OVERRIDE",1, field_fmt_51_51_2_2_info, field_fmt_51_51_2_2_set, field_fmt_51_51_2_2_get, NULL, 1},
    {"SOBMH_FROM_CPU::SRC_MODID",1, field_fmt_52_59_2_2_info, field_fmt_52_59_2_2_set, field_fmt_52_59_2_2_get, NULL, 1},
    {"SOBMH_FROM_CPU::TX_TS",1, field_fmt_60_60_2_2_info, field_fmt_60_60_2_2_set, field_fmt_60_60_2_2_get, NULL, 1},
    {"SOBMH_FROM_CPU::UNICAST",1, field_fmt_61_61_2_2_info, field_fmt_61_61_2_2_set, field_fmt_61_61_2_2_get, NULL, 1},
    {"SOBMH_FROM_CPU::WRED_MARK_ELIGIBLE",1, field_fmt_62_62_2_2_info, field_fmt_62_62_2_2_set, field_fmt_62_62_2_2_get, NULL, 1},
    {"SOBMH_FROM_CPU::WRED_RESPONSE",1, field_fmt_63_63_2_2_info, field_fmt_63_63_2_2_set, field_fmt_63_63_2_2_get, NULL, 1},
    {"HEADER_TYPE",1, field_fmt_120_125_0_0_info, field_fmt_120_125_0_0_set, field_fmt_120_125_0_0_get, bcm78914_b0_txpmd_header_type_names, 0},
    {"START",1, field_fmt_126_127_0_0_info, field_fmt_126_127_0_0_set, field_fmt_126_127_0_0_get, bcm78914_b0_txpmd_start_names, 0},

};

static const shr_enum_map_t bcm78914_b0_txpmd_names[] =
{
    BCM78914_B0_TXPMD_NAME_MAP_INIT
};

bcmpkt_pmd_info_t bcm78914_b0_txpmd_info_get(void)
{
    bcmpkt_pmd_info_t bcm78914_b0_txpmd_info = {4, BCM78914_B0_TXPMD_COUNT, bcm78914_b0_txpmd_names, bcm78914_b0_txpmd_fields};
    return bcm78914_b0_txpmd_info;
}

static const shr_enum_map_t bcm78914_b0_lbhdr_header_type_names[] =
{
    BCM78914_B0_LBHDR_HEADER_TYPE_NAME_MAP_INIT
};

static const shr_enum_map_t bcm78914_b0_lbhdr_start_names[] =
{
    BCM78914_B0_LBHDR_START_NAME_MAP_INIT
};

static bcmpkt_pmd_field_t bcm78914_b0_lbhdr_fields[BCM78914_B0_LBHDR_COUNT] = {
    {"PKT_PROFILE",1, field_fmt_16_18_3_3_info, field_fmt_16_18_3_3_set, field_fmt_16_18_3_3_get, NULL, 0},
    {"QOS_FIELD_VALID",1, field_fmt_19_19_3_3_info, field_fmt_19_19_3_3_set, field_fmt_19_19_3_3_get, NULL, 0},
    {"VFI_VALID_MD_ETH",1, field_fmt_21_21_3_3_info, field_fmt_21_21_3_3_set, field_fmt_21_21_3_3_get, NULL, 0},
    {"VRF_VALID",1, field_fmt_22_22_3_3_info, field_fmt_22_22_3_3_set, field_fmt_22_22_3_3_get, NULL, 0},
    {"VFI_MD_ETH",1, field_fmt_24_36_3_2_info, field_fmt_24_36_3_2_set, field_fmt_24_36_3_2_get, NULL, 0},
    {"VRF",1, field_fmt_24_36_3_2_info, field_fmt_24_36_3_2_set, field_fmt_24_36_3_2_get, NULL, 0},
    {"PP_PORT",1, field_fmt_37_46_2_2_info, field_fmt_37_46_2_2_set, field_fmt_37_46_2_2_get, NULL, 0},
    {"VISIBILITY_PKT",1, field_fmt_47_47_2_2_info, field_fmt_47_47_2_2_set, field_fmt_47_47_2_2_get, NULL, 0},
    {"ROUTED_PKT",1, field_fmt_48_48_2_2_info, field_fmt_48_48_2_2_set, field_fmt_48_48_2_2_get, NULL, 0},
    {"OPAQUE_OBJECT",1, field_fmt_81_84_1_1_info, field_fmt_81_84_1_1_set, field_fmt_81_84_1_1_get, NULL, 0},
    {"QOS_FIELD_ETH",1, field_fmt_85_92_1_1_info, field_fmt_85_92_1_1_set, field_fmt_85_92_1_1_get, NULL, 0},
    {"INT_PRI_ETH",1, field_fmt_85_88_1_1_info, field_fmt_85_88_1_1_set, field_fmt_85_88_1_1_get, NULL, 0},
    {"INT_CN_ETH",1, field_fmt_89_90_1_1_info, field_fmt_89_90_1_1_set, field_fmt_89_90_1_1_get, NULL, 0},
    {"CNG_ETH",1, field_fmt_91_92_1_1_info, field_fmt_91_92_1_1_set, field_fmt_91_92_1_1_get, NULL, 0},
    {"INPUT_PRIORITY_MD_ETH",1, field_fmt_116_119_0_0_info, field_fmt_116_119_0_0_set, field_fmt_116_119_0_0_get, NULL, 0},
    {"HEADER_TYPE",1, field_fmt_120_125_0_0_info, field_fmt_120_125_0_0_set, field_fmt_120_125_0_0_get, bcm78914_b0_lbhdr_header_type_names, 0},
    {"START",1, field_fmt_126_127_0_0_info, field_fmt_126_127_0_0_set, field_fmt_126_127_0_0_get, bcm78914_b0_lbhdr_start_names, 0},

};

static const shr_enum_map_t bcm78914_b0_lbhdr_names[] =
{
    BCM78914_B0_LBHDR_NAME_MAP_INIT
};

bcmpkt_pmd_info_t bcm78914_b0_lbhdr_info_get(void)
{
    bcmpkt_pmd_info_t bcm78914_b0_lbhdr_info = {4, BCM78914_B0_LBHDR_COUNT, bcm78914_b0_lbhdr_names, bcm78914_b0_lbhdr_fields};
    return bcm78914_b0_lbhdr_info;
}
