# SPDX-License-Identifier: GPL-2.0
#
# Makefile for Marvell's OcteonTX2 SDEI/GHES device driver
#

obj-$(CONFIG_MARVELL_SDEI_GHES) += mrvl_sdei_ghes.o
mrvl_sdei_ghes-$(CONFIG_MARVELL_GHES_BERT) += mrvl-ghes-bert.o
mrvl_sdei_ghes-y += mrvl-sdei-ghes.o

obj-$(CONFIG_MARVELL_EINJ) += mrvl-einj.o
