# SPDX-License-Identifier: GPL-2.0
#
# Makefile for Marvell's OcteonTX2 RVU Admin Function driver
#

obj-$(CONFIG_OCTEONTX2_CGX) += octeontx2_cgx.o
obj-$(CONFIG_OCTEONTX2_AF) += octeontx2_af.o

octeontx2_cgx-y := cgx.o
octeontx2_af-y := rvu.o mbox.o rvu_cgx.o rvu_npa.o
