/*******************************************************************************
 *
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated from the registers file.
 * Edits to this file will be lost when it is regenerated.
 * Tool: INTERNAL/regs/xgs/generate-pmd.pl
 *
 * Copyright 2018-2024 Broadcom. All rights reserved.
 * The term 'Broadcom' refers to Broadcom Inc. and/or its subsidiaries.
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License 
 * version 2 as published by the Free Software Foundation.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * A copy of the GNU General Public License version 2 (GPLv2) can
 * be found in the LICENSES folder.
 *
 * This file provides PMD field defines for BCM56780_A0.
 *
 ******************************************************************************/

#ifndef BCM56780_A0_PMD_FIELD_H
#define BCM56780_A0_PMD_FIELD_H

/* RXPMD defines */
#define BCM56780_A0_RXPMD_FLEX_DATA                                  0
#define BCM56780_A0_RXPMD_MPB_FLEX_DATA_TYPE                         1
#define BCM56780_A0_RXPMD_DOP_TRIGGER                                2
#define BCM56780_A0_RXPMD_EPARSE_EXTRACT_OFFSETS_3_0_OR_MIRROR_ENCAP_INDEX 3
#define BCM56780_A0_RXPMD_EPARSE_EXTRACT_OFFSETS_7_4                 4
#define BCM56780_A0_RXPMD_INT_CN                                     5
#define BCM56780_A0_RXPMD_CNG                                        6
#define BCM56780_A0_RXPMD_MULTICAST                                  7
#define BCM56780_A0_RXPMD_IP_ROUTED                                  8
#define BCM56780_A0_RXPMD_COPY_TO_CPU                                9
#define BCM56780_A0_RXPMD_TRUNCATE_CPU_COPY                          10
#define BCM56780_A0_RXPMD_EGR_ZONE_REMAP_CTRL                        11
#define BCM56780_A0_RXPMD_SWITCH                                     12
#define BCM56780_A0_RXPMD_L3ONLY                                     13
#define BCM56780_A0_RXPMD_UC_SW_COPY_DROPPED                         14
#define BCM56780_A0_RXPMD_UNICAST_QUEUE                              15
#define BCM56780_A0_RXPMD_MATCH_ID_LO                                16
#define BCM56780_A0_RXPMD_MATCH_ID_HI                                17
#define BCM56780_A0_RXPMD_REPLICATION_OR_NHOP_INDEX                  18
#define BCM56780_A0_RXPMD_DMA_HEADER_VERSION                         19
#define BCM56780_A0_RXPMD_QUEUE_NUM                                  20
#define BCM56780_A0_RXPMD_SRC_PORT_NUM                               21
#define BCM56780_A0_RXPMD_PKT_LENGTH                                 22
#define BCM56780_A0_RXPMD_COUNT                                      23

/* RXPMD name map */
#define BCM56780_A0_RXPMD_NAME_MAP_INIT \
    {"FLEX_DATA", BCM56780_A0_RXPMD_FLEX_DATA}, \
    {"MPB_FLEX_DATA_TYPE", BCM56780_A0_RXPMD_MPB_FLEX_DATA_TYPE}, \
    {"DOP_TRIGGER", BCM56780_A0_RXPMD_DOP_TRIGGER}, \
    {"EPARSE_EXTRACT_OFFSETS_3_0_OR_MIRROR_ENCAP_INDEX", BCM56780_A0_RXPMD_EPARSE_EXTRACT_OFFSETS_3_0_OR_MIRROR_ENCAP_INDEX}, \
    {"EPARSE_EXTRACT_OFFSETS_7_4", BCM56780_A0_RXPMD_EPARSE_EXTRACT_OFFSETS_7_4}, \
    {"INT_CN", BCM56780_A0_RXPMD_INT_CN}, \
    {"CNG", BCM56780_A0_RXPMD_CNG}, \
    {"MULTICAST", BCM56780_A0_RXPMD_MULTICAST}, \
    {"IP_ROUTED", BCM56780_A0_RXPMD_IP_ROUTED}, \
    {"COPY_TO_CPU", BCM56780_A0_RXPMD_COPY_TO_CPU}, \
    {"TRUNCATE_CPU_COPY", BCM56780_A0_RXPMD_TRUNCATE_CPU_COPY}, \
    {"EGR_ZONE_REMAP_CTRL", BCM56780_A0_RXPMD_EGR_ZONE_REMAP_CTRL}, \
    {"SWITCH", BCM56780_A0_RXPMD_SWITCH}, \
    {"L3ONLY", BCM56780_A0_RXPMD_L3ONLY}, \
    {"UC_SW_COPY_DROPPED", BCM56780_A0_RXPMD_UC_SW_COPY_DROPPED}, \
    {"UNICAST_QUEUE", BCM56780_A0_RXPMD_UNICAST_QUEUE}, \
    {"MATCH_ID_LO", BCM56780_A0_RXPMD_MATCH_ID_LO}, \
    {"MATCH_ID_HI", BCM56780_A0_RXPMD_MATCH_ID_HI}, \
    {"REPLICATION_OR_NHOP_INDEX", BCM56780_A0_RXPMD_REPLICATION_OR_NHOP_INDEX}, \
    {"DMA_HEADER_VERSION", BCM56780_A0_RXPMD_DMA_HEADER_VERSION}, \
    {"QUEUE_NUM", BCM56780_A0_RXPMD_QUEUE_NUM}, \
    {"SRC_PORT_NUM", BCM56780_A0_RXPMD_SRC_PORT_NUM}, \
    {"PKT_LENGTH", BCM56780_A0_RXPMD_PKT_LENGTH}, \
    {"COUNT", BCM56780_A0_RXPMD_COUNT}

/* TXPMD defines */
#define BCM56780_A0_TXPMD_CELL_LENGTH                                0
#define BCM56780_A0_TXPMD_EOP                                        1
#define BCM56780_A0_TXPMD_SOP                                        2
#define BCM56780_A0_TXPMD_PKT_LENGTH                                 3
#define BCM56780_A0_TXPMD_COS                                        4
#define BCM56780_A0_TXPMD_UNICAST_PKT                                5
#define BCM56780_A0_TXPMD_UNICAST                                    6
#define BCM56780_A0_TXPMD_SET_L2BM                                   7
#define BCM56780_A0_TXPMD_RQE_Q_NUM                                  8
#define BCM56780_A0_TXPMD_SPAP                                       9
#define BCM56780_A0_TXPMD_SPID                                       10
#define BCM56780_A0_TXPMD_SPID_OVERRIDE                              11
#define BCM56780_A0_TXPMD_INPUT_PRI                                  12
#define BCM56780_A0_TXPMD_LOCAL_DEST_PORT                            13
#define BCM56780_A0_TXPMD_IEEE1588_TIMESTAMP_HDR_OFFSET              14
#define BCM56780_A0_TXPMD_TX_TS                                      15
#define BCM56780_A0_TXPMD_IEEE1588_INGRESS_TIMESTAMP_SIGN            16
#define BCM56780_A0_TXPMD_IEEE1588_REGEN_UDP_CHECKSUM                17
#define BCM56780_A0_TXPMD_IEEE1588_ONE_STEP_ENABLE                   18
#define BCM56780_A0_TXPMD_CELL_ERROR                                 19
#define BCM56780_A0_TXPMD_HEADER_TYPE                                20
#define BCM56780_A0_TXPMD_START                                      21
#define BCM56780_A0_TXPMD_COUNT                                      22

/* TXPMD name map */
#define BCM56780_A0_TXPMD_NAME_MAP_INIT \
    {"CELL_LENGTH", BCM56780_A0_TXPMD_CELL_LENGTH}, \
    {"EOP", BCM56780_A0_TXPMD_EOP}, \
    {"SOP", BCM56780_A0_TXPMD_SOP}, \
    {"PKT_LENGTH", BCM56780_A0_TXPMD_PKT_LENGTH}, \
    {"COS", BCM56780_A0_TXPMD_COS}, \
    {"UNICAST_PKT", BCM56780_A0_TXPMD_UNICAST_PKT}, \
    {"UNICAST", BCM56780_A0_TXPMD_UNICAST}, \
    {"SET_L2BM", BCM56780_A0_TXPMD_SET_L2BM}, \
    {"RQE_Q_NUM", BCM56780_A0_TXPMD_RQE_Q_NUM}, \
    {"SPAP", BCM56780_A0_TXPMD_SPAP}, \
    {"SPID", BCM56780_A0_TXPMD_SPID}, \
    {"SPID_OVERRIDE", BCM56780_A0_TXPMD_SPID_OVERRIDE}, \
    {"INPUT_PRI", BCM56780_A0_TXPMD_INPUT_PRI}, \
    {"LOCAL_DEST_PORT", BCM56780_A0_TXPMD_LOCAL_DEST_PORT}, \
    {"IEEE1588_TIMESTAMP_HDR_OFFSET", BCM56780_A0_TXPMD_IEEE1588_TIMESTAMP_HDR_OFFSET}, \
    {"TX_TS", BCM56780_A0_TXPMD_TX_TS}, \
    {"IEEE1588_INGRESS_TIMESTAMP_SIGN", BCM56780_A0_TXPMD_IEEE1588_INGRESS_TIMESTAMP_SIGN}, \
    {"IEEE1588_REGEN_UDP_CHECKSUM", BCM56780_A0_TXPMD_IEEE1588_REGEN_UDP_CHECKSUM}, \
    {"IEEE1588_ONE_STEP_ENABLE", BCM56780_A0_TXPMD_IEEE1588_ONE_STEP_ENABLE}, \
    {"CELL_ERROR", BCM56780_A0_TXPMD_CELL_ERROR}, \
    {"HEADER_TYPE", BCM56780_A0_TXPMD_HEADER_TYPE}, \
    {"START", BCM56780_A0_TXPMD_START}, \
    {"COUNT", BCM56780_A0_TXPMD_COUNT}

/*!
 * \name BCM56780_A0_TXPMD_HEADER_TYPE encodings.
 * \anchor BCM56780_A0_TXPMD_HEADER_TYPE_XXX
 */
/*! \{ */
#define BCM56780_A0_TXPMD_HEADER_TYPE_RESERVED_0                     0
#define BCM56780_A0_TXPMD_HEADER_TYPE_SOBMH_FROM_INTERNAL_PORT       1
/*! \} */

/*! BCM56780_A0_TXPMD_HEADER_TYPE encoding name strings maps. */
#define BCM56780_A0_TXPMD_HEADER_TYPE_NAME_MAP_INIT \
    {"RESERVED_0", BCM56780_A0_TXPMD_HEADER_TYPE_RESERVED_0},\
    {"SOBMH_FROM_INTERNAL_PORT", BCM56780_A0_TXPMD_HEADER_TYPE_SOBMH_FROM_INTERNAL_PORT},\
    {NULL, 0}

/*!
 * \name BCM56780_A0_TXPMD_START encodings.
 * \anchor BCM56780_A0_TXPMD_START_XXX
 */
/*! \{ */
#define BCM56780_A0_TXPMD_START_RESERVED_0                           0
#define BCM56780_A0_TXPMD_START_RESERVED_1                           1
#define BCM56780_A0_TXPMD_START_INTERNAL_HEADER                      2
#define BCM56780_A0_TXPMD_START_HIGIG                                3
/*! \} */

/*! BCM56780_A0_TXPMD_START encoding name strings maps. */
#define BCM56780_A0_TXPMD_START_NAME_MAP_INIT \
    {"RESERVED_0", BCM56780_A0_TXPMD_START_RESERVED_0},\
    {"RESERVED_1", BCM56780_A0_TXPMD_START_RESERVED_1},\
    {"INTERNAL_HEADER", BCM56780_A0_TXPMD_START_INTERNAL_HEADER},\
    {"HIGIG", BCM56780_A0_TXPMD_START_HIGIG},\
    {NULL, 0}

#endif /* BCM56780_A0_PMD_FIELD_H */
