# SPDX-License-Identifier: GPL-2.0
#
# Makefile for Marvell's OcteonTX2 PCI console driver
#

obj-$(CONFIG_OCTEONTX2_PCI_CONSOLE) += octeontx2_pcicons.o
ccflags-y += -mno-outline-atomics
octeontx2_pcicons-y := otx2-pci-console.o
