/* Copyright (C) 2011-2014 Oracle, Inc. */

DTRACE_SYSCALL_STUB(EXECVE,		execve)
DTRACE_SYSCALL_STUB(PIPE,		pipe)
DTRACE_SYSCALL_STUB(MEMORY_ORDERING,	memory_ordering)
DTRACE_SYSCALL_STUB(SIGALTSTACK,	sigaltstack)
DTRACE_SYSCALL_STUB(RT_SIGRETURN,	rt_sigreturn)
DTRACE_SYSCALL_STUB(VFORK,		vfork)
DTRACE_SYSCALL_STUB(FORK,		fork)
DTRACE_SYSCALL_STUB(CLONE,		clone)
DTRACE_SYSCALL_STUB(EXIT_GROUP,		exit_group)
DTRACE_SYSCALL_STUB(EXIT,		exit)
