#
# Makefile for Broadcom 10-Gigabit ethernet driver
#

obj-$(CONFIG_BNX2X) += bnx2x.o

bnx2x-objs := bnx2x_main.o bnx2x_link.o bnx2x_cmn.o bnx2x_ethtool.o bnx2x_stats.o bnx2x_dcb.o bnx2x_sp.o bnx2x_stats.o bnx2x_self_test.o bnx2x_sriov.o bnx2x_vfpf.o bnx2x_init_values_e1.o bnx2x_init_values_e1h.o bnx2x_init_values_e2.o

