# -*- Kbuild -*-
#
# Linux PTP Clock module.
#
# Copyright 2018-2024 Broadcom. All rights reserved.
# The term 'Broadcom' refers to Broadcom Inc. and/or its subsidiaries.
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License 
# version 2 as published by the Free Software Foundation.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# A copy of the GNU General Public License version 2 (GPLv2) can
# be found in the LICENSES folder.
#

obj-m := linux_ngptpclock.o

ccflags-y := $(LKM_CFLAGS) $(LKM_CPPFLAGS) \
             -I$(SDK)/shr/include \
             -I$(SDK)/bcmdrd/include \
             -I$(SDK)/linux/include \
             -I$(SDK)/linux/knet/include \
             -I$(SDK)/linux/knet

linux_ngptpclock-y := ngptpclock_main.o
