/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2021, Pensando Systems Inc.
 */

#ifndef __CAP_PCIE_CAPRI_H__
#define __CAP_PCIE_CAPRI_H__

#define PCIEPORT_NPORTS		8

#define CAP_ADDR_BASE_PP_PP_OFFSET 0x7000000
#define CAP_PXC_CSR_BYTE_SIZE 0x00002000

#define CAP_PP_CSR_PORT_C_CFG_C_PORT_MAC_BYTE_ADDRESS 0x110f8
#define CAP_PXC_CSR_CFG_C_PORT_MAC_CFG_C_PORT_MAC_0_2_LTSSM_EN_FIELD_MASK 0x00000002
#define CAP_PXC_CSR_CFG_C_PORT_MAC_CFG_C_PORT_MAC_0_2_CFG_RETRY_EN_FIELD_MASK 0x00000008

#define CAP_PP_CSR_PORT_C_INT_C_MAC_INTREG_BYTE_ADDRESS 0x111b0
#define CAP_PXC_CSR_INT_C_MAC_INTREG_RST_DN2UP_INTERRUPT_FIELD_MASK 0x00000010

#define _PP_BASE(pn)    CAP_ADDR_BASE_PP_PP_OFFSET
#define PP_(REG, pn)	(_PP_BASE(pn) + CAP_PP_CSR_ ##REG## _BYTE_ADDRESS)
#define _PXC_OFFSET(pn)	((pn) * CAP_PXC_CSR_BYTE_SIZE)
#define _PXC_REG_(REG)	(CAP_PP_CSR_PORT_C_ ##REG## _BYTE_ADDRESS)
#define PXC_(REG, pn)	(_PP_BASE(pn) + _PXC_OFFSET(pn) + _PXC_REG_(REG))

#define CFG_MACF_(REG) \
	(CAP_PXC_CSR_CFG_C_PORT_MAC_CFG_C_PORT_MAC_ ##REG## _FIELD_MASK)
#define MAC_INTREGF_(REG) \
	(CAP_PXC_CSR_INT_C_MAC_INTREG_ ##REG## _INTERRUPT_FIELD_MASK)

#define CAP_MS_CSR_CFG_WDT_RST_EN_LSB 0
#define CFG_WDT_RST_EN  CAP_MS_CSR_CFG_WDT_RST_EN_LSB

#define WDT_CR          0x00
#define WDT_TORR        0x01
#define WDT_CRR         0x03

#define WDT_CR_ENABLE   0x1
#define WDT_CR_PCLK_256 (0x7 << 2)

#define WDT_KICK_VAL    0x76

#endif /* __CAP_PCIE_CAPRI_H__ */
