#
# Pensando SoC drivers
#
obj-y += cap_soc.o
obj-$(CONFIG_PENSANDO_SOC_CAPMEM) += cap_mem.o
obj-$(CONFIG_PENSANDO_SOC_PCIE) += cap_pcie.o cap_reboot.o cap_rstcause.o kpcimgr.o
obj-$(CONFIG_PENSANDO_SOC_CRASH) += cap_crash.o
obj-$(CONFIG_PENSANDO_SOC_BSM) += cap_bsm.o
obj-$(CONFIG_PENSANDO_SOC_SBUS) += sbus.o
