#ifndef BCMPKT_TXPMD_DEFS_H
#define BCMPKT_TXPMD_DEFS_H
/*******************************************************************************
 *
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated from the registers file.
 * Edits to this file will be lost when it is regenerated.
 * Tool: INTERNAL/regs/xgs/generate-pmd.pl
 *
 *
 * Copyright 2018-2025 Broadcom. All rights reserved.
 * The term 'Broadcom' refers to Broadcom Inc. and/or its subsidiaries.
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License 
 * version 2 as published by the Free Software Foundation.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * A copy of the GNU General Public License version 2 (GPLv2) can
 * be found in the LICENSES folder.
 *
 * This file provides field macros for the TX Packet MetaData (TXPMD, called
 * SOBMH in hardware.) access.
 *
 ******************************************************************************/

/*!
 * \name TX packet metadata field IDs.
 * \anchor BCMPKT_TXPMD_XXX
 */
/*! \{ */
/*! Invalid BCMPKT_TXPMD FID indicator */
#define BCMPKT_TXPMD_FID_INVALID                 -1
/*! Start of frame indicator. */
#define BCMPKT_TXPMD_START                       0
/*!
 * 64 Header Types Supported. 1 means Packets from CPU with SOBMH header format
 * to Passthru NLF
 */
#define BCMPKT_TXPMD_HEADER_TYPE                 1
/*! PKT_LENGTH (set by hardware - in Iarb). */
#define BCMPKT_TXPMD_PKT_LENGTH                  2
/*! Pointer to cell buffer of this SOBMH cell. (Set by hardware) */
#define BCMPKT_TXPMD_IPCF_PTR                    3
/*! SOP indicator (set by hardware - in Iarb). */
#define BCMPKT_TXPMD_SOP                         4
/*! EOP indicator (set by hardware - in Iarb). */
#define BCMPKT_TXPMD_EOP                         5
/*! CELL_LENGTH (set by hardware - in Iarb). */
#define BCMPKT_TXPMD_CELL_LENGTH                 6
/*! CELL_ERROR or PURGE */
#define BCMPKT_TXPMD_CELL_ERROR                  7
/*! Indicates the local port to send a SOBMH packet out. */
#define BCMPKT_TXPMD_LOCAL_DEST_PORT             8
/*! Source module ID, must be programmed to MY_MODID. */
#define BCMPKT_TXPMD_SRC_MODID                   9
/*!
 * Class of service for MMU queueing for this packet - sets COS values,
 * PBI.UC_COS, PBI.MC_COS1, and PBI.MC_COS2.
 */
#define BCMPKT_TXPMD_COS                         10
/*! Traffic priority to be applied to MMU via PBI.INPUT_PRIORITY. */
#define BCMPKT_TXPMD_INPUT_PRI                   11
/*! Indicates that PBI.UNICAST should be set to queue as unicast packet. */
#define BCMPKT_TXPMD_UNICAST                     12
/*! Value for CCBI.RSQ_Q_NUM. */
#define BCMPKT_TXPMD_RQE_Q_NUM                   13
/*! Indicates that PBI.L2_BITMAP should be set (to queue as L2MC packet). */
#define BCMPKT_TXPMD_SET_L2BM                    14
/*! ONE STEP TIME STAMPING ENABLE */
#define BCMPKT_TXPMD_IEEE1588_ONE_STEP_ENABLE    15
/*! Regenerate UDP Checksum */
#define BCMPKT_TXPMD_IEEE1588_REGEN_UDP_CHECKSUM 16
/*! ITS_SIGN bit */
#define BCMPKT_TXPMD_IEEE1588_INGRESS_TIMESTAMP_SIGN 17
/*! HDR_OFFSET */
#define BCMPKT_TXPMD_IEEE1588_TIMESTAMP_HDR_OFFSET 18
/*!
 * Indicates for TS packet transmitted from CPU into IP that the outgoing packet
 * needs to have its transmit timestamp captured by the port.
 */
#define BCMPKT_TXPMD_TX_TS                       19
/*! For PBI.SPID_Override */
#define BCMPKT_TXPMD_SPID_OVERRIDE               20
/*! For PBI.SPID - Service Pool ID */
#define BCMPKT_TXPMD_SPID                        21
/*! For PBI.SPAP - Service Pool Priority (color) */
#define BCMPKT_TXPMD_SPAP                        22
/*! Will set CCBI_B.UNICAST_PKT */
#define BCMPKT_TXPMD_UNICAST_PKT                 23
/*! Timestamp action LSB. */
#define BCMPKT_TXPMD_TS_ACTION_LSB               24
/*! Timestamp action MSB. */
#define BCMPKT_TXPMD_TS_ACTION_MSB               25
/*! Time statmp type.  Encodings are 0-NTP TOD(64 bit), 1-PTP TOD(64bit) */
#define BCMPKT_TXPMD_TS_TYPE                     26
/*! Destination subport number */
#define BCMPKT_TXPMD_DST_SUBPORT_NUM             27
/*! Enable UDP incremental checksum */
#define BCMPKT_TXPMD_UDP_CHECKSUM_UPDATE_ENABLE  28
/*! Offset to UDP checksum field from start of MACS-SA. */
#define BCMPKT_TXPMD_UDP_CHECKSUM_OFFSET         29
/*! CNG Field. */
#define BCMPKT_TXPMD_CNG                         30
/*! DESTINATION Field. */
#define BCMPKT_TXPMD_DESTINATION                 31
/*! Destination Field Type. */
#define BCMPKT_TXPMD_DESTINATION_TYPE            32
/*! WRED Mark Eligible field. */
#define BCMPKT_TXPMD_WRED_MARK_ELIGIBLE          33
/*! WRED Response Field. */
#define BCMPKT_TXPMD_WRED_RESPONSE               34
/*! Allows software to select load balancing bitmap for non-unicast packets. */
#define BCMPKT_TXPMD_CPU_TX_MCAST_LB_INDEX       35
/*! ECMP member ID for case where DESTINATION_TYPE=ECMP_MEMBER. Only valid for single level ECMP */
#define BCMPKT_TXPMD_CPU_TX_ECMP_MEMBER_ID       36
/*! Destination Field. */
#define BCMPKT_TXPMD_CPU_TX_DESTINATION          37
/*! Destination Field Type. */
#define BCMPKT_TXPMD_CPU_TX_DESTINATION_TYPE     38
/*! Drop Precedence. */
#define BCMPKT_TXPMD_CPU_TX_DP                   39
/*! Traffic priority to be applied to MMU via PBI.INPUT_PRIORITY. */
#define BCMPKT_TXPMD_CPU_TX_INPUT_PRI            40
/*! Internal congestion. */
#define BCMPKT_TXPMD_CPU_TX_INT_CN               41
/*! Internal priority */
#define BCMPKT_TXPMD_CPU_TX_INT_PRI              42
/*! Load balancing bitmap is valid indication. */
#define BCMPKT_TXPMD_CPU_TX_MCAST_LB_INDEX_VLD   43
/*! Pointer to CPU_PACKET_PROFILE_1/2 registers. */
#define BCMPKT_TXPMD_CPU_TX_PKT_PROFILE          44
/*! QoS fields (INT_PRI, DP, INT_CN) valid indication. */
#define BCMPKT_TXPMD_CPU_TX_QOS_FIELDS_VLD       45
/*! If set packet marked as Layer 3 routed. */
#define BCMPKT_TXPMD_CPU_TX_ROUTED_PKT           46
/*! Indicates that PBI.UNICAST should be set to queue as unicast packet. */
#define BCMPKT_TXPMD_CPU_TX_UNICAST              47
/*! SOP indication. */
#define BCMPKT_TXPMD_CPU_TX_SOP                  48
/*! VRF ID. */
#define BCMPKT_TXPMD_CPU_TX_VRF                  49
/*! VRF ID is valid. */
#define BCMPKT_TXPMD_CPU_TX_VRF_VALID            50
/*! WCMP Selection. */
#define BCMPKT_TXPMD_CPU_TX_WCMP_SEL             51
/*! Cell error. */
#define BCMPKT_TXPMD_OAM_DOWNMEP_TX_CELL_ERROR   52
/*! Cell length. */
#define BCMPKT_TXPMD_OAM_DOWNMEP_TX_CELL_LENGTH  53
/*! Class of service. */
#define BCMPKT_TXPMD_OAM_DOWNMEP_TX_COS          54
/*! Destination. */
#define BCMPKT_TXPMD_OAM_DOWNMEP_TX_DESTINATION  55
/*! Destination type. */
#define BCMPKT_TXPMD_OAM_DOWNMEP_TX_DESTINATION_TYPE 56
/*! EOP indicator. */
#define BCMPKT_TXPMD_OAM_DOWNMEP_TX_EOP          57
/*! Input priority. */
#define BCMPKT_TXPMD_OAM_DOWNMEP_TX_INPUT_PRI    58
/*! LM counter action. */
#define BCMPKT_TXPMD_OAM_DOWNMEP_TX_LM_COUNTER_ACTION 59
/*! LM counter ID. */
#define BCMPKT_TXPMD_OAM_DOWNMEP_TX_LM_COUNTER_ID 60
/*! OAM replacement offset. */
#define BCMPKT_TXPMD_OAM_DOWNMEP_TX_OAM_REPLACEMENT_OFFSET 61
/*! Packet length. */
#define BCMPKT_TXPMD_OAM_DOWNMEP_TX_PKT_LENGTH   62
/*! RQE Queue Number. */
#define BCMPKT_TXPMD_OAM_DOWNMEP_TX_RQE_Q_NUM    63
/*! SOP indicator. */
#define BCMPKT_TXPMD_OAM_DOWNMEP_TX_SOP          64
/*! Service Pool Allocation Precedence. */
#define BCMPKT_TXPMD_OAM_DOWNMEP_TX_SPAP         65
/*! Service Pool ID. */
#define BCMPKT_TXPMD_OAM_DOWNMEP_TX_SPID         66
/*! For Service Pool ID override. */
#define BCMPKT_TXPMD_OAM_DOWNMEP_TX_SPID_OVERRIDE 67
/*! Source module ID. */
#define BCMPKT_TXPMD_OAM_DOWNMEP_TX_SRC_MODID    68
/*! Timestamp action. */
#define BCMPKT_TXPMD_OAM_DOWNMEP_TX_TIMESTAMP_ACTION 69
/*! Unicast packet. */
#define BCMPKT_TXPMD_OAM_DOWNMEP_TX_UNICAST      70
/*! Indicates a copy should be sent to the the CPU port mapped to R5. */
#define BCMPKT_TXPMD_COPY_TO_DEBUG               71

#define BCMPKT_TXPMD_COPY_TO_CPU                 72
/*! Used to set PBI.WRED_RESPONSIVE */
#define BCMPKT_TXPMD_WRED_RESPONSIVE             73
/*! Cookie correspoding to 1588 2-step */
#define BCMPKT_TXPMD_CPU_TX_COOKIE               74
/*! Validates Cookie field */
#define BCMPKT_TXPMD_CPU_TX_COOKIE_VALID         75
/*! The 8 LSB bits of Cookie corresponding to 1588 2-Step */
#define BCMPKT_TXPMD_COOKIE_7_0                  76
/*! The MSB of Cookie corresponding to 1588 2-Step */
#define BCMPKT_TXPMD_COOKIE_8                    77
/*! Unicast packet type. */
#define BCMPKT_TXPMD_AUX_SOBMH_UNICAST_PKT       78
/*! vpp_port to send a SOBMH packet out. */
#define BCMPKT_TXPMD_AUX_SOBMH_TX_VPP_PORT       79
/*! Destination chip_port number. */
#define BCMPKT_TXPMD_AUX_SOBMH_TX_CHIP_PORT      80
/*! RX chip port. */
#define BCMPKT_TXPMD_AUX_SOBMH_RX_CHIP_PORT      81
/*! SVP */
#define BCMPKT_TXPMD_CPU_TX_SVP                  82
/*! Switch packet copy is accepted. */
#define BCMPKT_TXPMD_SWITCH_COPY                 83
/*! Switch packet copy type. */
#define BCMPKT_TXPMD_SWITCH_COPY_TYPE            84
/*! Destination port of switch packet copy. */
#define BCMPKT_TXPMD_SWITCH_COPY_DEST_PORT       85
/*! Queue number of the switch packet copy. */
#define BCMPKT_TXPMD_SWITCH_COPY_COS             86
/*! Adaptive routing group. */
#define BCMPKT_TXPMD_CPU_TX_AR_GROUP             87
/*! INCA group ID. */
#define BCMPKT_TXPMD_CPU_TX_INCA_GROUP_ID        88
/*! INCA collective ID. */
#define BCMPKT_TXPMD_CPU_TX_INCA_COLLECTIVE_ID   89
/*! INCA internal QP ID. */
#define BCMPKT_TXPMD_CPU_TX_INCA_INTERNAL_QP_ID  90
/*! INCA source host profile. */
#define BCMPKT_TXPMD_CPU_TX_INCA_SRC_HOST_PROFILE 91
/*! INCA flow type. */
#define BCMPKT_TXPMD_CPU_TX_INCA_FLOW_TYPE       92
/*! INCA Reduction required: 0 : Reduction not required (Broadcast), 1 : Reduction required         (AllReduce/Reduce) */
#define BCMPKT_TXPMD_CPU_TX_INCA_REDN_REQD       93
/*! INCA Replication required: 0 : Replication not required (Reduce), 1 : Replication required (AllReduce/Broadcast) */
#define BCMPKT_TXPMD_CPU_TX_INCA_REPL_REQD       94
/*! INCA Second pass destination. */
#define BCMPKT_TXPMD_CPU_TX_INCA_SECOND_PASS_DEST 95
/*!
 * Operation type. 0-Sum, 1-Sum and Scale, 2-15 - Reserved.
 * Valid only when the INCA_REDN_REQD==1 where INCA reduction is required.
 * This field is consumed by ICE and not carried beyond to second pass.
 */
#define BCMPKT_TXPMD_CPU_TX_INCA_ICE_OPER_TYPE   96
/*! Vlan profile. */
#define BCMPKT_TXPMD_CPU_TX_VLAN_PROFILE         97
/*! Forwarding profile. */
#define BCMPKT_TXPMD_CPU_TX_FWD_PROFILE          98
/*! Data format. Valid only when INCA_REDN_REQD==1 where INCA reduction is required. This field is consumed by ICE and not carried beyond to second pass. */
#define BCMPKT_TXPMD_CPU_TX_INCA_ICE_DATA_FORMAT 99
/*! Indicates the offset at 2B granularity from beginning of the pkt to the start  of INCA DATA for reduction.Valid only when INCA_REDN_REQD==1 where INCA reduction is required. This  is consumed by IDN and not carried beyond to second pass. */
#define BCMPKT_TXPMD_CPU_TX_INCA_ICE_DATA_OFFSET 100
/*! CNG field. */
#define BCMPKT_TXPMD_CPU_TX_CNG                  101
/*! Packet Entropy. */
#define BCMPKT_TXPMD_CPU_TX_PACKET_ENTROPY       102
/*! Source port number. */
#define BCMPKT_TXPMD_CPU_TX_SRC_PORT_NUM         103
/*! Packet control profile. */
#define BCMPKT_TXPMD_CPU_TX_PKT_CTRL_PROFILE     104
/*! Queue number. */
#define BCMPKT_TXPMD_CPU_TX_COS                  105
/*! Internal priority valid. */
#define BCMPKT_TXPMD_CPU_TX_INT_PRI_VALID        106
/*! CNG vaild. */
#define BCMPKT_TXPMD_CPU_TX_CNG_VALID            107
/*! Internal congestion valid. */
#define BCMPKT_TXPMD_CPU_TX_INT_CN_VALID         108
/*! Input priority valid. */
#define BCMPKT_TXPMD_CPU_TX_INPUT_PRI_VALID      109
/*! COS valid. */
#define BCMPKT_TXPMD_CPU_TX_COS_VALID            110
/*! CPU Tx Type. */
#define BCMPKT_TXPMD_CPU_TX_CPU_TX_TYPE          111
/*! DOP Trigger. */
#define BCMPKT_TXPMD_CPU_TX_DOP_TRIGGER          112
/*! Aux to LPP class ID. */
#define BCMPKT_TXPMD_CPU_TX_VPP_TO_LPP_CLASS_ID  113
/*! Cell length */
#define BCMPKT_TXPMD_AUX_SOBMH_CELL_LENGTH       114
/*! End of Packet indication. */
#define BCMPKT_TXPMD_AUX_SOBMH_EOP               115
/*! Start of packet indication. */
#define BCMPKT_TXPMD_AUX_SOBMH_SOP               116
/*! Packet length. */
#define BCMPKT_TXPMD_AUX_SOBMH_PKT_LENGTH        117
/*! Copy to CPU. */
#define BCMPKT_TXPMD_AUX_SOBMH_COPY_TO_CPU       118
/*! Copy to debug. */
#define BCMPKT_TXPMD_AUX_SOBMH_COPY_TO_DEBUG     119
/*! CNG field. */
#define BCMPKT_TXPMD_AUX_SOBMH_CNG               120
/*! Queue number. */
#define BCMPKT_TXPMD_AUX_SOBMH_COS               121
/*! Indicates that PBI.UNICAST should be set to queue as unicast packet. */
#define BCMPKT_TXPMD_AUX_SOBMH_UNICAST           122
/*! Indicates that PBI.L2_BITMAP should be set (to queue as L2MC packet). */
#define BCMPKT_TXPMD_AUX_SOBMH_SET_L2BM          123
/*! RQE queue number. */
#define BCMPKT_TXPMD_AUX_SOBMH_RQE_Q_NUM         124
/*! Input priority. */
#define BCMPKT_TXPMD_AUX_SOBMH_INPUT_PRI         125
/*! Cell error indication. */
#define BCMPKT_TXPMD_AUX_SOBMH_CELL_ERROR        126
/*! Header type. */
#define BCMPKT_TXPMD_AUX_SOBMH_HEADER_TYPE       127
/*! Start of frame indicator. */
#define BCMPKT_TXPMD_AUX_SOBMH_START             128
/*! INCA uplink port. */
#define BCMPKT_TXPMD_CPU_TX_INCA_UPLINK_PORT     129
/*! TXPMD FIELD ID NUMBER */
#define BCMPKT_TXPMD_FID_COUNT                   130
/*! \} */

/*! TXPMD field name strings for debugging. */
#define BCMPKT_TXPMD_FIELD_NAME_MAP_INIT \
    {"START", BCMPKT_TXPMD_START},\
    {"HEADER_TYPE", BCMPKT_TXPMD_HEADER_TYPE},\
    {"PKT_LENGTH", BCMPKT_TXPMD_PKT_LENGTH},\
    {"IPCF_PTR", BCMPKT_TXPMD_IPCF_PTR},\
    {"SOP", BCMPKT_TXPMD_SOP},\
    {"EOP", BCMPKT_TXPMD_EOP},\
    {"CELL_LENGTH", BCMPKT_TXPMD_CELL_LENGTH},\
    {"CELL_ERROR", BCMPKT_TXPMD_CELL_ERROR},\
    {"LOCAL_DEST_PORT", BCMPKT_TXPMD_LOCAL_DEST_PORT},\
    {"SRC_MODID", BCMPKT_TXPMD_SRC_MODID},\
    {"COS", BCMPKT_TXPMD_COS},\
    {"INPUT_PRI", BCMPKT_TXPMD_INPUT_PRI},\
    {"UNICAST", BCMPKT_TXPMD_UNICAST},\
    {"RQE_Q_NUM", BCMPKT_TXPMD_RQE_Q_NUM},\
    {"SET_L2BM", BCMPKT_TXPMD_SET_L2BM},\
    {"IEEE1588_ONE_STEP_ENABLE", BCMPKT_TXPMD_IEEE1588_ONE_STEP_ENABLE},\
    {"IEEE1588_REGEN_UDP_CHECKSUM", BCMPKT_TXPMD_IEEE1588_REGEN_UDP_CHECKSUM},\
    {"IEEE1588_INGRESS_TIMESTAMP_SIGN", BCMPKT_TXPMD_IEEE1588_INGRESS_TIMESTAMP_SIGN},\
    {"IEEE1588_TIMESTAMP_HDR_OFFSET", BCMPKT_TXPMD_IEEE1588_TIMESTAMP_HDR_OFFSET},\
    {"TX_TS", BCMPKT_TXPMD_TX_TS},\
    {"SPID_OVERRIDE", BCMPKT_TXPMD_SPID_OVERRIDE},\
    {"SPID", BCMPKT_TXPMD_SPID},\
    {"SPAP", BCMPKT_TXPMD_SPAP},\
    {"UNICAST_PKT", BCMPKT_TXPMD_UNICAST_PKT},\
    {"TS_ACTION_LSB", BCMPKT_TXPMD_TS_ACTION_LSB},\
    {"TS_ACTION_MSB", BCMPKT_TXPMD_TS_ACTION_MSB},\
    {"TS_TYPE", BCMPKT_TXPMD_TS_TYPE},\
    {"DST_SUBPORT_NUM", BCMPKT_TXPMD_DST_SUBPORT_NUM},\
    {"UDP_CHECKSUM_UPDATE_ENABLE", BCMPKT_TXPMD_UDP_CHECKSUM_UPDATE_ENABLE},\
    {"UDP_CHECKSUM_OFFSET", BCMPKT_TXPMD_UDP_CHECKSUM_OFFSET},\
    {"CNG", BCMPKT_TXPMD_CNG},\
    {"DESTINATION", BCMPKT_TXPMD_DESTINATION},\
    {"DESTINATION_TYPE", BCMPKT_TXPMD_DESTINATION_TYPE},\
    {"WRED_MARK_ELIGIBLE", BCMPKT_TXPMD_WRED_MARK_ELIGIBLE},\
    {"WRED_RESPONSE", BCMPKT_TXPMD_WRED_RESPONSE},\
    {"CPU_TX::MCAST_LB_INDEX", BCMPKT_TXPMD_CPU_TX_MCAST_LB_INDEX},\
    {"CPU_TX::ECMP_MEMBER_ID", BCMPKT_TXPMD_CPU_TX_ECMP_MEMBER_ID},\
    {"CPU_TX::DESTINATION", BCMPKT_TXPMD_CPU_TX_DESTINATION},\
    {"CPU_TX::DESTINATION_TYPE", BCMPKT_TXPMD_CPU_TX_DESTINATION_TYPE},\
    {"CPU_TX::DP", BCMPKT_TXPMD_CPU_TX_DP},\
    {"CPU_TX::INPUT_PRI", BCMPKT_TXPMD_CPU_TX_INPUT_PRI},\
    {"CPU_TX::INT_CN", BCMPKT_TXPMD_CPU_TX_INT_CN},\
    {"CPU_TX::INT_PRI", BCMPKT_TXPMD_CPU_TX_INT_PRI},\
    {"CPU_TX::MCAST_LB_INDEX_VLD", BCMPKT_TXPMD_CPU_TX_MCAST_LB_INDEX_VLD},\
    {"CPU_TX::PKT_PROFILE", BCMPKT_TXPMD_CPU_TX_PKT_PROFILE},\
    {"CPU_TX::QOS_FIELDS_VLD", BCMPKT_TXPMD_CPU_TX_QOS_FIELDS_VLD},\
    {"CPU_TX::ROUTED_PKT", BCMPKT_TXPMD_CPU_TX_ROUTED_PKT},\
    {"CPU_TX::UNICAST", BCMPKT_TXPMD_CPU_TX_UNICAST},\
    {"CPU_TX::SOP", BCMPKT_TXPMD_CPU_TX_SOP},\
    {"CPU_TX::VRF", BCMPKT_TXPMD_CPU_TX_VRF},\
    {"CPU_TX::VRF_VALID", BCMPKT_TXPMD_CPU_TX_VRF_VALID},\
    {"CPU_TX::WCMP_SEL", BCMPKT_TXPMD_CPU_TX_WCMP_SEL},\
    {"OAM_DOWNMEP_TX::CELL_ERROR", BCMPKT_TXPMD_OAM_DOWNMEP_TX_CELL_ERROR},\
    {"OAM_DOWNMEP_TX::CELL_LENGTH", BCMPKT_TXPMD_OAM_DOWNMEP_TX_CELL_LENGTH},\
    {"OAM_DOWNMEP_TX::COS", BCMPKT_TXPMD_OAM_DOWNMEP_TX_COS},\
    {"OAM_DOWNMEP_TX::DESTINATION", BCMPKT_TXPMD_OAM_DOWNMEP_TX_DESTINATION},\
    {"OAM_DOWNMEP_TX::DESTINATION_TYPE", BCMPKT_TXPMD_OAM_DOWNMEP_TX_DESTINATION_TYPE},\
    {"OAM_DOWNMEP_TX::EOP", BCMPKT_TXPMD_OAM_DOWNMEP_TX_EOP},\
    {"OAM_DOWNMEP_TX::INPUT_PRI", BCMPKT_TXPMD_OAM_DOWNMEP_TX_INPUT_PRI},\
    {"OAM_DOWNMEP_TX::LM_COUNTER_ACTION", BCMPKT_TXPMD_OAM_DOWNMEP_TX_LM_COUNTER_ACTION},\
    {"OAM_DOWNMEP_TX::LM_COUNTER_ID", BCMPKT_TXPMD_OAM_DOWNMEP_TX_LM_COUNTER_ID},\
    {"OAM_DOWNMEP_TX::OAM_REPLACEMENT_OFFSET", BCMPKT_TXPMD_OAM_DOWNMEP_TX_OAM_REPLACEMENT_OFFSET},\
    {"OAM_DOWNMEP_TX::PKT_LENGTH", BCMPKT_TXPMD_OAM_DOWNMEP_TX_PKT_LENGTH},\
    {"OAM_DOWNMEP_TX::RQE_Q_NUM", BCMPKT_TXPMD_OAM_DOWNMEP_TX_RQE_Q_NUM},\
    {"OAM_DOWNMEP_TX::SOP", BCMPKT_TXPMD_OAM_DOWNMEP_TX_SOP},\
    {"OAM_DOWNMEP_TX::SPAP", BCMPKT_TXPMD_OAM_DOWNMEP_TX_SPAP},\
    {"OAM_DOWNMEP_TX::SPID", BCMPKT_TXPMD_OAM_DOWNMEP_TX_SPID},\
    {"OAM_DOWNMEP_TX::SPID_OVERRIDE", BCMPKT_TXPMD_OAM_DOWNMEP_TX_SPID_OVERRIDE},\
    {"OAM_DOWNMEP_TX::SRC_MODID", BCMPKT_TXPMD_OAM_DOWNMEP_TX_SRC_MODID},\
    {"OAM_DOWNMEP_TX::TIMESTAMP_ACTION", BCMPKT_TXPMD_OAM_DOWNMEP_TX_TIMESTAMP_ACTION},\
    {"OAM_DOWNMEP_TX::UNICAST", BCMPKT_TXPMD_OAM_DOWNMEP_TX_UNICAST},\
    {"COPY_TO_DEBUG", BCMPKT_TXPMD_COPY_TO_DEBUG},\
    {"COPY_TO_CPU", BCMPKT_TXPMD_COPY_TO_CPU},\
    {"WRED_RESPONSIVE", BCMPKT_TXPMD_WRED_RESPONSIVE},\
    {"CPU_TX::COOKIE", BCMPKT_TXPMD_CPU_TX_COOKIE},\
    {"CPU_TX::COOKIE_VALID", BCMPKT_TXPMD_CPU_TX_COOKIE_VALID},\
    {"COOKIE_7_0", BCMPKT_TXPMD_COOKIE_7_0},\
    {"COOKIE_8", BCMPKT_TXPMD_COOKIE_8},\
    {"AUX_SOBMH::UNICAST_PKT", BCMPKT_TXPMD_AUX_SOBMH_UNICAST_PKT},\
    {"AUX_SOBMH::TX_VPP_PORT", BCMPKT_TXPMD_AUX_SOBMH_TX_VPP_PORT},\
    {"AUX_SOBMH::TX_CHIP_PORT", BCMPKT_TXPMD_AUX_SOBMH_TX_CHIP_PORT},\
    {"AUX_SOBMH::RX_CHIP_PORT", BCMPKT_TXPMD_AUX_SOBMH_RX_CHIP_PORT},\
    {"CPU_TX::SVP", BCMPKT_TXPMD_CPU_TX_SVP},\
    {"SWITCH_COPY", BCMPKT_TXPMD_SWITCH_COPY},\
    {"SWITCH_COPY_TYPE", BCMPKT_TXPMD_SWITCH_COPY_TYPE},\
    {"SWITCH_COPY_DEST_PORT", BCMPKT_TXPMD_SWITCH_COPY_DEST_PORT},\
    {"SWITCH_COPY_COS", BCMPKT_TXPMD_SWITCH_COPY_COS},\
    {"CPU_TX::AR_GROUP", BCMPKT_TXPMD_CPU_TX_AR_GROUP},\
    {"CPU_TX::INCA_GROUP_ID", BCMPKT_TXPMD_CPU_TX_INCA_GROUP_ID},\
    {"CPU_TX::INCA_COLLECTIVE_ID", BCMPKT_TXPMD_CPU_TX_INCA_COLLECTIVE_ID},\
    {"CPU_TX::INCA_INTERNAL_QP_ID", BCMPKT_TXPMD_CPU_TX_INCA_INTERNAL_QP_ID},\
    {"CPU_TX::INCA_SRC_HOST_PROFILE", BCMPKT_TXPMD_CPU_TX_INCA_SRC_HOST_PROFILE},\
    {"CPU_TX::INCA_FLOW_TYPE", BCMPKT_TXPMD_CPU_TX_INCA_FLOW_TYPE},\
    {"CPU_TX::INCA_REDN_REQD", BCMPKT_TXPMD_CPU_TX_INCA_REDN_REQD},\
    {"CPU_TX::INCA_REPL_REQD", BCMPKT_TXPMD_CPU_TX_INCA_REPL_REQD},\
    {"CPU_TX::INCA_SECOND_PASS_DEST", BCMPKT_TXPMD_CPU_TX_INCA_SECOND_PASS_DEST},\
    {"CPU_TX::INCA_ICE_OPER_TYPE", BCMPKT_TXPMD_CPU_TX_INCA_ICE_OPER_TYPE},\
    {"CPU_TX::VLAN_PROFILE", BCMPKT_TXPMD_CPU_TX_VLAN_PROFILE},\
    {"CPU_TX::FWD_PROFILE", BCMPKT_TXPMD_CPU_TX_FWD_PROFILE},\
    {"CPU_TX::INCA_ICE_DATA_FORMAT", BCMPKT_TXPMD_CPU_TX_INCA_ICE_DATA_FORMAT},\
    {"CPU_TX::INCA_ICE_DATA_OFFSET", BCMPKT_TXPMD_CPU_TX_INCA_ICE_DATA_OFFSET},\
    {"CPU_TX::CNG", BCMPKT_TXPMD_CPU_TX_CNG},\
    {"CPU_TX::PACKET_ENTROPY", BCMPKT_TXPMD_CPU_TX_PACKET_ENTROPY},\
    {"CPU_TX::SRC_PORT_NUM", BCMPKT_TXPMD_CPU_TX_SRC_PORT_NUM},\
    {"CPU_TX::PKT_CTRL_PROFILE", BCMPKT_TXPMD_CPU_TX_PKT_CTRL_PROFILE},\
    {"CPU_TX::COS", BCMPKT_TXPMD_CPU_TX_COS},\
    {"CPU_TX::INT_PRI_VALID", BCMPKT_TXPMD_CPU_TX_INT_PRI_VALID},\
    {"CPU_TX::CNG_VALID", BCMPKT_TXPMD_CPU_TX_CNG_VALID},\
    {"CPU_TX::INT_CN_VALID", BCMPKT_TXPMD_CPU_TX_INT_CN_VALID},\
    {"CPU_TX::INPUT_PRI_VALID", BCMPKT_TXPMD_CPU_TX_INPUT_PRI_VALID},\
    {"CPU_TX::COS_VALID", BCMPKT_TXPMD_CPU_TX_COS_VALID},\
    {"CPU_TX::CPU_TX_TYPE", BCMPKT_TXPMD_CPU_TX_CPU_TX_TYPE},\
    {"CPU_TX::DOP_TRIGGER", BCMPKT_TXPMD_CPU_TX_DOP_TRIGGER},\
    {"CPU_TX::VPP_TO_LPP_CLASS_ID", BCMPKT_TXPMD_CPU_TX_VPP_TO_LPP_CLASS_ID},\
    {"AUX_SOBMH::CELL_LENGTH", BCMPKT_TXPMD_AUX_SOBMH_CELL_LENGTH},\
    {"AUX_SOBMH::EOP", BCMPKT_TXPMD_AUX_SOBMH_EOP},\
    {"AUX_SOBMH::SOP", BCMPKT_TXPMD_AUX_SOBMH_SOP},\
    {"AUX_SOBMH::PKT_LENGTH", BCMPKT_TXPMD_AUX_SOBMH_PKT_LENGTH},\
    {"AUX_SOBMH::COPY_TO_CPU", BCMPKT_TXPMD_AUX_SOBMH_COPY_TO_CPU},\
    {"AUX_SOBMH::COPY_TO_DEBUG", BCMPKT_TXPMD_AUX_SOBMH_COPY_TO_DEBUG},\
    {"AUX_SOBMH::CNG", BCMPKT_TXPMD_AUX_SOBMH_CNG},\
    {"AUX_SOBMH::COS", BCMPKT_TXPMD_AUX_SOBMH_COS},\
    {"AUX_SOBMH::UNICAST", BCMPKT_TXPMD_AUX_SOBMH_UNICAST},\
    {"AUX_SOBMH::SET_L2BM", BCMPKT_TXPMD_AUX_SOBMH_SET_L2BM},\
    {"AUX_SOBMH::RQE_Q_NUM", BCMPKT_TXPMD_AUX_SOBMH_RQE_Q_NUM},\
    {"AUX_SOBMH::INPUT_PRI", BCMPKT_TXPMD_AUX_SOBMH_INPUT_PRI},\
    {"AUX_SOBMH::CELL_ERROR", BCMPKT_TXPMD_AUX_SOBMH_CELL_ERROR},\
    {"AUX_SOBMH::HEADER_TYPE", BCMPKT_TXPMD_AUX_SOBMH_HEADER_TYPE},\
    {"AUX_SOBMH::START", BCMPKT_TXPMD_AUX_SOBMH_START},\
    {"CPU_TX::INCA_UPLINK_PORT", BCMPKT_TXPMD_CPU_TX_INCA_UPLINK_PORT},\
    {"fid count", BCMPKT_TXPMD_FID_COUNT}

/*!
 * \name BCMPKT_TXPMD_START encodings.
 * \anchor BCMPKT_TXPMD_START_XXX
 */
/*! \{ */
/*! The header used internally only */
#define BCMPKT_TXPMD_START_INTERNAL_HEADER       2
/*! Frame type is Higig */
#define BCMPKT_TXPMD_START_HIGIG                 3
/*! \} */

/*! BCMPKT_TXPMD_START encoding name strings for debugging. */
#define BCMPKT_TXPMD_START_NAME_MAP_INIT \
    {"RESERVED_COUNTER", 0},\
    {"RESERVED_COUNTER", 1},\
    {"INTERNAL_HEADER", BCMPKT_TXPMD_START_INTERNAL_HEADER},\
    {"HIGIG", BCMPKT_TXPMD_START_HIGIG},\

/*!
 * \name BCMPKT_TXPMD_HEADER_TYPE encodings.
 * \anchor BCMPKT_TXPMD_HEADER_TYPE_XXX
 */
/*! \{ */
/*! EP Copy to CPU format, SOBMH header in EP to Passthru NLF */
#define BCMPKT_TXPMD_HEADER_T_TO_CPU             0
/*! Packets from CPU with SOBMH header format to Passthru NLF */
#define BCMPKT_TXPMD_HEADER_T_FROM_CPU           1
/*! Header type CPU_TX in LPP pipeline */
#define BCMPKT_TXPMD_HEADER_T_LPP_CPU_TX         1
/*! Header type CPU_TX */
#define BCMPKT_TXPMD_HEADER_T_CPU_TX             2
/*! Header type TX_MD in LPP pipeline */
#define BCMPKT_TXPMD_HEADER_T_LPP_TX_MD_HEADER   2
/*! MAC in MAC packets to Passthru NLF */
#define BCMPKT_TXPMD_HEADER_T_MIM                2
/*! Packet with SOBMH header format */
#define BCMPKT_TXPMD_HEADER_T_LPP_SOBMH          3
/*! MPLS packets to Passthru NLF */
#define BCMPKT_TXPMD_HEADER_T_MPLS_PMP           3
/*! Trill Network Packets to Passthru NLF */
#define BCMPKT_TXPMD_HEADER_T_TRILL_NW           4
/*! Trill Access Layer Packets to Passthru NLF */
#define BCMPKT_TXPMD_HEADER_T_TRILL_AC           5
/*! WLAN Decap packets sent to WRX NLF */
#define BCMPKT_TXPMD_HEADER_T_WLAN_DECAP         6
/*! WLAN Encap packets sent to WTX NLF */
#define BCMPKT_TXPMD_HEADER_T_WLAN_ENCAP         7
/*! QCN Packets to Passthru NLF */
#define BCMPKT_TXPMD_HEADER_T_QCN                8
/*! DPI/Signature Matcher packets sent to SM NLF */
#define BCMPKT_TXPMD_HEADER_T_SM_DPI             9
/*! EP Redirection packets to Passthru NLF */
#define BCMPKT_TXPMD_HEADER_T_EP_REDIR           10
/*! Other generic passthrough to Passthru NLF */
#define BCMPKT_TXPMD_HEADER_T_GENERIC            11
/*! DOWN MEP Transmit OAM Packets from CPU or CCM from HW Engine or OLP */
#define BCMPKT_TXPMD_HEADER_T_OAM_DOWNMEP_TX     12
/*! UP MEP Transmit OAM Packets from CPU or CCM from HW Engine or OLP */
#define BCMPKT_TXPMD_HEADER_T_OAM_UPMEP_TX       13
/*! \} */

/*! BCMPKT_TXPMD_HEADER_TYPE encoding name strings for debugging. */
#define BCMPKT_TXPMD_HEADER_TYPE_NAME_MAP_INIT \
    {"SOBMH_EP_COPY_TO_CPU", BCMPKT_TXPMD_HEADER_T_TO_CPU},\
    {"SOBMH_FROM_CPU", BCMPKT_TXPMD_HEADER_T_FROM_CPU},\
    {"LPP_CPU_TX", BCMPKT_TXPMD_HEADER_T_LPP_CPU_TX},\
    {"CPU_TX", BCMPKT_TXPMD_HEADER_T_CPU_TX},\
    {"LPP_TX_MD_HEADER", BCMPKT_TXPMD_HEADER_T_LPP_TX_MD_HEADER},\
    {"MIM", BCMPKT_TXPMD_HEADER_T_MIM},\
    {"LPP_SOBMH", BCMPKT_TXPMD_HEADER_T_LPP_SOBMH},\
    {"MPLS_PMP", BCMPKT_TXPMD_HEADER_T_MPLS_PMP},\
    {"TRILL_NW", BCMPKT_TXPMD_HEADER_T_TRILL_NW},\
    {"TRILL_AC", BCMPKT_TXPMD_HEADER_T_TRILL_AC},\
    {"WLAN_DECAP", BCMPKT_TXPMD_HEADER_T_WLAN_DECAP},\
    {"WLAN_ENCAP", BCMPKT_TXPMD_HEADER_T_WLAN_ENCAP},\
    {"QCN", BCMPKT_TXPMD_HEADER_T_QCN},\
    {"SM_DPI", BCMPKT_TXPMD_HEADER_T_SM_DPI},\
    {"EP_REDIR", BCMPKT_TXPMD_HEADER_T_EP_REDIR},\
    {"GENERIC", BCMPKT_TXPMD_HEADER_T_GENERIC},\
    {"OAM_DOWNMEP_TX", BCMPKT_TXPMD_HEADER_T_OAM_DOWNMEP_TX},\
    {"OAM_UPMEP_TX", BCMPKT_TXPMD_HEADER_T_OAM_UPMEP_TX},\

/*!
 * \name BCMPKT_TXPMD_DESTINATION_TYPE encodings.
 * \anchor BCMPKT_TXPMD_DESTINATION_TYPE_XXX
 */
/*! \{ */
/*! Egress Port */
#define BCMPKT_TXPMD_DESTINATION_T_EGRESS_PORT   0
/*! Asserts bit selected by destination field in L2_PBM */
#define BCMPKT_TXPMD_DESTINATION_T_L2_PBM        7
/*! Destination is Invalid */
#define BCMPKT_TXPMD_DESTINATION_T_INVALID       15
/*! \} */

/*! BCMPKT_TXPMD_DESTINATION_TYPE encoding name strings for debugging. */
#define BCMPKT_TXPMD_DESTINATION_TYPE_NAME_MAP_INIT \
    {"EGRESS_PORT", BCMPKT_TXPMD_DESTINATION_T_EGRESS_PORT},\
    {"RESERVED_COUNTER", 1},\
    {"RESERVED_COUNTER", 2},\
    {"RESERVED_COUNTER", 3},\
    {"RESERVED_COUNTER", 4},\
    {"RESERVED_COUNTER", 5},\
    {"RESERVED_COUNTER", 6},\
    {"L2_PBM", BCMPKT_TXPMD_DESTINATION_T_L2_PBM},\
    {"RESERVED_COUNTER", 8},\
    {"RESERVED_COUNTER", 9},\
    {"RESERVED_COUNTER", 10},\
    {"RESERVED_COUNTER", 11},\
    {"RESERVED_COUNTER", 12},\
    {"RESERVED_COUNTER", 13},\
    {"RESERVED_COUNTER", 14},\
    {"INVALID", BCMPKT_TXPMD_DESTINATION_T_INVALID},\

/*!
 * \name BCMPKT_TXPMD_CPU_TX_DESTINATION_TYPE encodings.
 * \anchor BCMPKT_TXPMD_CPU_TX_DESTINATION_TYPE_XXX
 */
/*! \{ */
/*! Egress Port */
#define BCMPKT_TXPMD_CPU_TX_DESTINATION_T_EGRESS_PORT 0
/*! Next Hop Index */
#define BCMPKT_TXPMD_CPU_TX_DESTINATION_T_NHI    1
/*! ECMP Group */
#define BCMPKT_TXPMD_CPU_TX_DESTINATION_T_ECMP   2
/*! ECMP member id */
#define BCMPKT_TXPMD_CPU_TX_DESTINATION_T_ECMP_MEMBER 3
/*! IP Multicast Group */
#define BCMPKT_TXPMD_CPU_TX_DESTINATION_T_IPMC   4
/*! L2MC group */
#define BCMPKT_TXPMD_CPU_TX_DESTINATION_T_L2MC   5
/*! Vlan Flooding */
#define BCMPKT_TXPMD_CPU_TX_DESTINATION_T_VLAN_FLOOD 6
/*! Asserts bit selected by destination field in L2_PBM */
#define BCMPKT_TXPMD_CPU_TX_DESTINATION_T_L2_PBM 7
/*! LAG ID */
#define BCMPKT_TXPMD_CPU_TX_DESTINATION_T_LAG_ID 8
/*! Destination is Invalid */
#define BCMPKT_TXPMD_CPU_TX_DESTINATION_T_NULL   9
/*! Egress Port */
#define BCMPKT_TXPMD_CPU_TX_DESTINATION_T_DEST_PORT 10
/*! Trunk ID */
#define BCMPKT_TXPMD_CPU_TX_DESTINATION_T_TGID   11
/*! Next Hop Index */
#define BCMPKT_TXPMD_CPU_TX_DESTINATION_T_NEXT_HOP 12
/*! Forward and derive destination normally */
#define BCMPKT_TXPMD_CPU_TX_DESTINATION_T_FORWARD 15
/*! Destination is Invalid */
#define BCMPKT_TXPMD_CPU_TX_DESTINATION_T_INVALID 15
/*! \} */

/*! BCMPKT_TXPMD_CPU_TX_DESTINATION_TYPE encoding name strings for debugging. */
#define BCMPKT_TXPMD_CPU_TX_DESTINATION_TYPE_NAME_MAP_INIT \
    {"EGRESS_PORT", BCMPKT_TXPMD_CPU_TX_DESTINATION_T_EGRESS_PORT},\
    {"NHI", BCMPKT_TXPMD_CPU_TX_DESTINATION_T_NHI},\
    {"ECMP", BCMPKT_TXPMD_CPU_TX_DESTINATION_T_ECMP},\
    {"ECMP_MEMBER", BCMPKT_TXPMD_CPU_TX_DESTINATION_T_ECMP_MEMBER},\
    {"IPMC", BCMPKT_TXPMD_CPU_TX_DESTINATION_T_IPMC},\
    {"L2MC", BCMPKT_TXPMD_CPU_TX_DESTINATION_T_L2MC},\
    {"VLAN_FLOOD", BCMPKT_TXPMD_CPU_TX_DESTINATION_T_VLAN_FLOOD},\
    {"L2_PBM", BCMPKT_TXPMD_CPU_TX_DESTINATION_T_L2_PBM},\
    {"LAG_ID", BCMPKT_TXPMD_CPU_TX_DESTINATION_T_LAG_ID},\
    {"NULL", BCMPKT_TXPMD_CPU_TX_DESTINATION_T_NULL},\
    {"DEST_PORT", BCMPKT_TXPMD_CPU_TX_DESTINATION_T_DEST_PORT},\
    {"TGID", BCMPKT_TXPMD_CPU_TX_DESTINATION_T_TGID},\
    {"NEXT_HOP", BCMPKT_TXPMD_CPU_TX_DESTINATION_T_NEXT_HOP},\
    {"RESERVED_COUNTER", 13},\
    {"RESERVED_COUNTER", 14},\
    {"FORWARD", BCMPKT_TXPMD_CPU_TX_DESTINATION_T_FORWARD},\
    {"INVALID", BCMPKT_TXPMD_CPU_TX_DESTINATION_T_INVALID},\

/*!
 * \name BCMPKT_TXPMD_CPU_TX_DP encodings.
 * \anchor BCMPKT_TXPMD_CPU_TX_DP_XXX
 */
/*! \{ */
/*! Green */
#define BCMPKT_TXPMD_CPU_TX_DP_GREEN             0
/*! Red */
#define BCMPKT_TXPMD_CPU_TX_DP_RED               1
/*! Yellow */
#define BCMPKT_TXPMD_CPU_TX_DP_YELLOW            3
/*! \} */

/*! BCMPKT_TXPMD_CPU_TX_DP encoding name strings for debugging. */
#define BCMPKT_TXPMD_CPU_TX_DP_NAME_MAP_INIT \
    {"GREEN", BCMPKT_TXPMD_CPU_TX_DP_GREEN},\
    {"RED", BCMPKT_TXPMD_CPU_TX_DP_RED},\
    {"RESERVED_COUNTER", 2},\
    {"YELLOW", BCMPKT_TXPMD_CPU_TX_DP_YELLOW},\

/*!
 * \name BCMPKT_TXPMD_OAM_DOWNMEP_TX_DESTINATION_TYPE encodings.
 * \anchor BCMPKT_TXPMD_OAM_DOWNMEP_TX_DESTINATION_TYPE_XXX
 */
/*! \{ */
/*! Egress Port */
#define BCMPKT_TXPMD_OAM_DOWNMEP_TX_DESTINATION_T_EGRESS_PORT 0
/*! \} */

/*! BCMPKT_TXPMD_OAM_DOWNMEP_TX_DESTINATION_TYPE encoding name strings for debugging. */
#define BCMPKT_TXPMD_OAM_DOWNMEP_TX_DESTINATION_TYPE_NAME_MAP_INIT \
    {"EGRESS_PORT", BCMPKT_TXPMD_OAM_DOWNMEP_TX_DESTINATION_T_EGRESS_PORT},\

/*!
 * \name BCMPKT_TXPMD_OAM_DOWNMEP_TX_LM_COUNTER_ACTION encodings.
 * \anchor BCMPKT_TXPMD_OAM_DOWNMEP_TX_LM_COUNTER_ACTION_XXX
 */
/*! \{ */
/*! No operation. */
#define BCMPKT_TXPMD_OAM_DOWNMEP_TX_LM_COUNTER_ACTION_NO_OP 0
/*! Increment. */
#define BCMPKT_TXPMD_OAM_DOWNMEP_TX_LM_COUNTER_ACTION_INCREMENT 1
/*! Increment and sample. */
#define BCMPKT_TXPMD_OAM_DOWNMEP_TX_LM_COUNTER_ACTION_INCREMENT_SAMPLE 2
/*! Sample. */
#define BCMPKT_TXPMD_OAM_DOWNMEP_TX_LM_COUNTER_ACTION_SAMPLE 3
/*! \} */

/*! BCMPKT_TXPMD_OAM_DOWNMEP_TX_LM_COUNTER_ACTION encoding name strings for debugging. */
#define BCMPKT_TXPMD_OAM_DOWNMEP_TX_LM_COUNTER_ACTION_NAME_MAP_INIT \
    {"NO_OP", BCMPKT_TXPMD_OAM_DOWNMEP_TX_LM_COUNTER_ACTION_NO_OP},\
    {"INCREMENT", BCMPKT_TXPMD_OAM_DOWNMEP_TX_LM_COUNTER_ACTION_INCREMENT},\
    {"INCREMENT_SAMPLE", BCMPKT_TXPMD_OAM_DOWNMEP_TX_LM_COUNTER_ACTION_INCREMENT_SAMPLE},\
    {"SAMPLE", BCMPKT_TXPMD_OAM_DOWNMEP_TX_LM_COUNTER_ACTION_SAMPLE},\

/*!
 * \name BCMPKT_TXPMD_OAM_DOWNMEP_TX_TIMESTAMP_ACTION encodings.
 * \anchor BCMPKT_TXPMD_OAM_DOWNMEP_TX_TIMESTAMP_ACTION_XXX
 */
/*! \{ */
/*! No operation. */
#define BCMPKT_TXPMD_OAM_DOWNMEP_TX_TIMESTAMP_ACTION_NO_OP 0
/*! Sample timestamp. */
#define BCMPKT_TXPMD_OAM_DOWNMEP_TX_TIMESTAMP_ACTION_SAMPLE 1
/*! \} */

/*! BCMPKT_TXPMD_OAM_DOWNMEP_TX_TIMESTAMP_ACTION encoding name strings for debugging. */
#define BCMPKT_TXPMD_OAM_DOWNMEP_TX_TIMESTAMP_ACTION_NAME_MAP_INIT \
    {"NO_OP", BCMPKT_TXPMD_OAM_DOWNMEP_TX_TIMESTAMP_ACTION_NO_OP},\
    {"SAMPLE", BCMPKT_TXPMD_OAM_DOWNMEP_TX_TIMESTAMP_ACTION_SAMPLE},\

/*!
 * \name BCMPKT_TXPMD_CPU_TX_INCA_REDN_REQD encodings.
 * \anchor BCMPKT_TXPMD_CPU_TX_INCA_REDN_REQD_XXX
 */
/*! \{ */
/*! Reduction not required. */
#define BCMPKT_TXPMD_CPU_TX_INCA_REDN_REQD_BROADCAST 0
/*! Reduction required. */
#define BCMPKT_TXPMD_CPU_TX_INCA_REDN_REQD_REDUCE 1
/*! \} */

/*! BCMPKT_TXPMD_CPU_TX_INCA_REDN_REQD encoding name strings for debugging. */
#define BCMPKT_TXPMD_CPU_TX_INCA_REDN_REQD_NAME_MAP_INIT \
    {"BROADCAST", BCMPKT_TXPMD_CPU_TX_INCA_REDN_REQD_BROADCAST},\
    {"REDUCE", BCMPKT_TXPMD_CPU_TX_INCA_REDN_REQD_REDUCE},\

/*!
 * \name BCMPKT_TXPMD_CPU_TX_INCA_REPL_REQD encodings.
 * \anchor BCMPKT_TXPMD_CPU_TX_INCA_REPL_REQD_XXX
 */
/*! \{ */
/*! Replication required. */
#define BCMPKT_TXPMD_CPU_TX_INCA_REPL_REQD_REDUCE 0
/*! Replication not required. */
#define BCMPKT_TXPMD_CPU_TX_INCA_REPL_REQD_BROADCAST 1
/*! \} */

/*! BCMPKT_TXPMD_CPU_TX_INCA_REPL_REQD encoding name strings for debugging. */
#define BCMPKT_TXPMD_CPU_TX_INCA_REPL_REQD_NAME_MAP_INIT \
    {"REDUCE", BCMPKT_TXPMD_CPU_TX_INCA_REPL_REQD_REDUCE},\
    {"BROADCAST", BCMPKT_TXPMD_CPU_TX_INCA_REPL_REQD_BROADCAST},\

/*!
 * \name BCMPKT_TXPMD_CPU_TX_INCA_ICE_OPER_TYPE encodings.
 * \anchor BCMPKT_TXPMD_CPU_TX_INCA_ICE_OPER_TYPE_XXX
 */
/*! \{ */
/*!  */
#define BCMPKT_TXPMD_CPU_TX_INCA_ICE_OPER_T_SUM  0
/*!  */
#define BCMPKT_TXPMD_CPU_TX_INCA_ICE_OPER_T_SUM_AND_SCALE 1
/*! \} */

/*! BCMPKT_TXPMD_CPU_TX_INCA_ICE_OPER_TYPE encoding name strings for debugging. */
#define BCMPKT_TXPMD_CPU_TX_INCA_ICE_OPER_TYPE_NAME_MAP_INIT \
    {"SUM", BCMPKT_TXPMD_CPU_TX_INCA_ICE_OPER_T_SUM},\
    {"SUM_AND_SCALE", BCMPKT_TXPMD_CPU_TX_INCA_ICE_OPER_T_SUM_AND_SCALE},\

/*!
 * \name BCMPKT_TXPMD_CPU_TX_INCA_ICE_DATA_FORMAT encodings.
 * \anchor BCMPKT_TXPMD_CPU_TX_INCA_ICE_DATA_FORMAT_XXX
 */
/*! \{ */
/*!  */
#define BCMPKT_TXPMD_CPU_TX_INCA_ICE_DATA_FORMAT_FP32 0
/*!  */
#define BCMPKT_TXPMD_CPU_TX_INCA_ICE_DATA_FORMAT_FP16 1
/*!  */
#define BCMPKT_TXPMD_CPU_TX_INCA_ICE_DATA_FORMAT_BF16 2
/*!  */
#define BCMPKT_TXPMD_CPU_TX_INCA_ICE_DATA_FORMAT_INT32 3
/*!  */
#define BCMPKT_TXPMD_CPU_TX_INCA_ICE_DATA_FORMAT_FP8 4
/*! \} */

/*! BCMPKT_TXPMD_CPU_TX_INCA_ICE_DATA_FORMAT encoding name strings for debugging. */
#define BCMPKT_TXPMD_CPU_TX_INCA_ICE_DATA_FORMAT_NAME_MAP_INIT \
    {"FP32", BCMPKT_TXPMD_CPU_TX_INCA_ICE_DATA_FORMAT_FP32},\
    {"FP16", BCMPKT_TXPMD_CPU_TX_INCA_ICE_DATA_FORMAT_FP16},\
    {"BF16", BCMPKT_TXPMD_CPU_TX_INCA_ICE_DATA_FORMAT_BF16},\
    {"INT32", BCMPKT_TXPMD_CPU_TX_INCA_ICE_DATA_FORMAT_INT32},\
    {"FP8", BCMPKT_TXPMD_CPU_TX_INCA_ICE_DATA_FORMAT_FP8},\

/*!
 * \name BCMPKT_TXPMD_CPU_TX_CPU_TX_TYPE encodings.
 * \anchor BCMPKT_TXPMD_CPU_TX_CPU_TX_TYPE_XXX
 */
/*! \{ */
/*! Classic CPU TX (Masquerade, Dest-based). */
#define BCMPKT_TXPMD_CPU_TX_CPU_TX_T_MASQUERADE  0
/*! Sample timestamp. */
#define BCMPKT_TXPMD_CPU_TX_CPU_TX_T_INCA        1
/*! \} */

/*! BCMPKT_TXPMD_CPU_TX_CPU_TX_TYPE encoding name strings for debugging. */
#define BCMPKT_TXPMD_CPU_TX_CPU_TX_TYPE_NAME_MAP_INIT \
    {"MASQUERADE", BCMPKT_TXPMD_CPU_TX_CPU_TX_T_MASQUERADE},\
    {"INCA", BCMPKT_TXPMD_CPU_TX_CPU_TX_T_INCA},\

/*!
 * \name BCMPKT_TXPMD_AUX_SOBMH_HEADER_TYPE encodings.
 * \anchor BCMPKT_TXPMD_AUX_SOBMH_HEADER_TYPE_XXX
 */
/*! \{ */
/*! Reserved. */
#define BCMPKT_TXPMD_AUX_SOBMH_HEADER_T_RESERVED 0
/*! Packets from CPU with SOBMH header format to Passthru NLF */
#define BCMPKT_TXPMD_AUX_SOBMH_HEADER_T_FROM_CPU 1
/*! \} */

/*! BCMPKT_TXPMD_AUX_SOBMH_HEADER_TYPE encoding name strings for debugging. */
#define BCMPKT_TXPMD_AUX_SOBMH_HEADER_TYPE_NAME_MAP_INIT \
    {"RESERVED", BCMPKT_TXPMD_AUX_SOBMH_HEADER_T_RESERVED},\
    {"SOBMH_FROM_CPU", BCMPKT_TXPMD_AUX_SOBMH_HEADER_T_FROM_CPU},\

/*!
 * \name TX packet metadata internal usage field IDs.
 * \anchor BCMPKT_TXPMD_I_XXX
 */
/*! \{ */
/*! Invalid BCMPKT_TXPMD_I FID indicator */
#define BCMPKT_TXPMD_I_FID_INVALID               -1
/*! TXPMD RX raw data size. */
#define BCMPKT_TXPMD_I_SIZE                      0
/*! TXPMD_I FIELD ID NUMBER */
#define BCMPKT_TXPMD_I_FID_COUNT                 1
/*! \} */

/*! TXPMD_I field name strings for debugging. */
#define BCMPKT_TXPMD_I_FIELD_NAME_MAP_INIT \
    {"SIZE", BCMPKT_TXPMD_I_SIZE},\
    {"fid count", BCMPKT_TXPMD_I_FID_COUNT}

#endif /*! BCMPKT_TXPMD_DEFS_H */
