# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Pensando network device drivers.
#

obj-$(CONFIG_IONIC) += ionic/
obj-$(CONFIG_MDEV) += mdev/
obj-$(CONFIG_MNET_UIO_PDRV_GENIRQ) += mnet_uio_pdrv_genirq/
