obj-$(CONFIG_MLX4_VNIC)	+= mlx4_vnic.o

mlx4_vnic-y :=  vnic_data_main.o    vnic_data_ib.o    vnic_data_netdev.o    vnic_data_neigh.o   \
		vnic_data_fs.o      vnic_data_tx.o    vnic_data_ethtool.o   vnic_data_rx.o      \
		vnic_fip_main.o	    vnic_fip_ib.o     vnic_fip_discover.o   vnic_fip_pkt.o      \
		vnic_fip_login.o    vnic_fip_vhub.o   vnic_mcast.o          vnic_port.o         \
		vnic_param.o        vnic_qp.o         vnic_main.o	    fip_parser.o	\
		vnic_data_mac.o

