/*******************************************************************************
 *
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated from the registers file.
 * Edits to this file will be lost when it is regenerated.
 * Tool: INTERNAL/regs/xgs/generate-pmd.pl
 *
 * Copyright 2018-2024 Broadcom. All rights reserved.
 * The term 'Broadcom' refers to Broadcom Inc. and/or its subsidiaries.
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License 
 * version 2 as published by the Free Software Foundation.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * A copy of the GNU General Public License version 2 (GPLv2) can
 * be found in the LICENSES folder.
 *
 * This file provides PMD field info for BCM78900_B0.
 *
 ******************************************************************************/

#include <bcmpkt/bcmpkt_pmd_field_internal.h>
#include <bcmpkt/chip/bcm78900_b0/bcm78900_b0_pmd_field.h>

static bcmpkt_field_info_t
field_fmt_0_0_12_12_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 0;
    info.maxbit = 0;
    return info;
}

static void
field_fmt_0_0_12_12_set(uint32_t *pmd, uint32_t *val)
{
    pmd[12] = (pmd[12] & 0xfffffffe) | (*val & 0x1);
}

static void
field_fmt_0_0_12_12_get(uint32_t *pmd, uint32_t *val)
{
    *val = pmd[12] & 0x1;
}

static bcmpkt_field_info_t
field_fmt_0_0_3_3_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 0;
    info.maxbit = 0;
    return info;
}

static void
field_fmt_0_0_3_3_set(uint32_t *pmd, uint32_t *val)
{
    pmd[3] = (pmd[3] & 0xfffffffe) | (*val & 0x1);
}

static void
field_fmt_0_0_3_3_get(uint32_t *pmd, uint32_t *val)
{
    *val = pmd[3] & 0x1;
}

static bcmpkt_field_info_t
field_fmt_0_16_3_3_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 0;
    info.maxbit = 16;
    return info;
}

static void
field_fmt_0_16_3_3_set(uint32_t *pmd, uint32_t *val)
{
    pmd[3] = (pmd[3] & 0xfffe0000) | (*val & 0x1ffff);
}

static void
field_fmt_0_16_3_3_get(uint32_t *pmd, uint32_t *val)
{
    *val = pmd[3] & 0x1ffff;
}

static bcmpkt_field_info_t
field_fmt_0_63_12_11_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 0;
    info.maxbit = 63;
    return info;
}

static void
field_fmt_0_63_12_11_set(uint32_t *pmd, uint32_t *val)
{
    pmd[12] = val[0];
    pmd[11] = val[1];
}

static void
field_fmt_0_63_12_11_get(uint32_t *pmd, uint32_t *val)
{
    val[0] = pmd[12];
    val[1] = pmd[11];
}

static bcmpkt_field_info_t
field_fmt_0_7_3_3_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 0;
    info.maxbit = 7;
    return info;
}

static void
field_fmt_0_7_3_3_set(uint32_t *pmd, uint32_t *val)
{
    pmd[3] = (pmd[3] & 0xffffff00) | (*val & 0xff);
}

static void
field_fmt_0_7_3_3_get(uint32_t *pmd, uint32_t *val)
{
    *val = pmd[3] & 0xff;
}

static bcmpkt_field_info_t
field_fmt_104_107_0_0_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 104;
    info.maxbit = 107;
    return info;
}

static void
field_fmt_104_107_0_0_set(uint32_t *pmd, uint32_t *val)
{
    pmd[0] = (pmd[0] & 0xfffff0ff) | ((*val & 0xf) << 8);
}

static void
field_fmt_104_107_0_0_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[0] >> 8) & 0xf;
}

static bcmpkt_field_info_t
field_fmt_108_111_0_0_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 108;
    info.maxbit = 111;
    return info;
}

static void
field_fmt_108_111_0_0_set(uint32_t *pmd, uint32_t *val)
{
    pmd[0] = (pmd[0] & 0xffff0fff) | ((*val & 0xf) << 12);
}

static void
field_fmt_108_111_0_0_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[0] >> 12) & 0xf;
}

static bcmpkt_field_info_t
field_fmt_108_115_0_0_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 108;
    info.maxbit = 115;
    return info;
}

static void
field_fmt_108_115_0_0_set(uint32_t *pmd, uint32_t *val)
{
    pmd[0] = (pmd[0] & 0xfff00fff) | ((*val & 0xff) << 12);
}

static void
field_fmt_108_115_0_0_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[0] >> 12) & 0xff;
}

static bcmpkt_field_info_t
field_fmt_10_10_12_12_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 10;
    info.maxbit = 10;
    return info;
}

static void
field_fmt_10_10_12_12_set(uint32_t *pmd, uint32_t *val)
{
    pmd[12] = (pmd[12] & 0xfffffbff) | ((*val & 0x1) << 10);
}

static void
field_fmt_10_10_12_12_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[12] >> 10) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_112_113_0_0_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 112;
    info.maxbit = 113;
    return info;
}

static void
field_fmt_112_113_0_0_set(uint32_t *pmd, uint32_t *val)
{
    pmd[0] = (pmd[0] & 0xfffcffff) | ((*val & 0x3) << 16);
}

static void
field_fmt_112_113_0_0_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[0] >> 16) & 0x3;
}

static bcmpkt_field_info_t
field_fmt_113_127_9_9_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 113;
    info.maxbit = 127;
    return info;
}

static void
field_fmt_113_127_9_9_set(uint32_t *pmd, uint32_t *val)
{
    pmd[9] = (pmd[9] & 0x1ffff) | (*val << 17);
}

static void
field_fmt_113_127_9_9_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[9] >> 17) & 0x7fff;
}

static bcmpkt_field_info_t
field_fmt_114_115_0_0_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 114;
    info.maxbit = 115;
    return info;
}

static void
field_fmt_114_115_0_0_set(uint32_t *pmd, uint32_t *val)
{
    pmd[0] = (pmd[0] & 0xfff3ffff) | ((*val & 0x3) << 18);
}

static void
field_fmt_114_115_0_0_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[0] >> 18) & 0x3;
}

static bcmpkt_field_info_t
field_fmt_11_11_12_12_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 11;
    info.maxbit = 11;
    return info;
}

static void
field_fmt_11_11_12_12_set(uint32_t *pmd, uint32_t *val)
{
    pmd[12] = (pmd[12] & 0xfffff7ff) | ((*val & 0x1) << 11);
}

static void
field_fmt_11_11_12_12_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[12] >> 11) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_120_125_0_0_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 120;
    info.maxbit = 125;
    return info;
}

static void
field_fmt_120_125_0_0_set(uint32_t *pmd, uint32_t *val)
{
    pmd[0] = (pmd[0] & 0xc0ffffff) | ((*val & 0x3f) << 24);
}

static void
field_fmt_120_125_0_0_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[0] >> 24) & 0x3f;
}

static bcmpkt_field_info_t
field_fmt_126_127_0_0_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 126;
    info.maxbit = 127;
    return info;
}

static void
field_fmt_126_127_0_0_set(uint32_t *pmd, uint32_t *val)
{
    pmd[0] = (pmd[0] & 0x3fffffff) | (*val << 30);
}

static void
field_fmt_126_127_0_0_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[0] >> 30) & 0x3;
}

static bcmpkt_field_info_t
field_fmt_128_128_8_8_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 128;
    info.maxbit = 128;
    return info;
}

static void
field_fmt_128_128_8_8_set(uint32_t *pmd, uint32_t *val)
{
    pmd[8] = (pmd[8] & 0xfffffffe) | (*val & 0x1);
}

static void
field_fmt_128_128_8_8_get(uint32_t *pmd, uint32_t *val)
{
    *val = pmd[8] & 0x1;
}

static bcmpkt_field_info_t
field_fmt_129_129_8_8_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 129;
    info.maxbit = 129;
    return info;
}

static void
field_fmt_129_129_8_8_set(uint32_t *pmd, uint32_t *val)
{
    pmd[8] = (pmd[8] & 0xfffffffd) | ((*val & 0x1) << 1);
}

static void
field_fmt_129_129_8_8_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[8] >> 1) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_12_12_12_12_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 12;
    info.maxbit = 12;
    return info;
}

static void
field_fmt_12_12_12_12_set(uint32_t *pmd, uint32_t *val)
{
    pmd[12] = (pmd[12] & 0xffffefff) | ((*val & 0x1) << 12);
}

static void
field_fmt_12_12_12_12_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[12] >> 12) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_130_130_8_8_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 130;
    info.maxbit = 130;
    return info;
}

static void
field_fmt_130_130_8_8_set(uint32_t *pmd, uint32_t *val)
{
    pmd[8] = (pmd[8] & 0xfffffffb) | ((*val & 0x1) << 2);
}

static void
field_fmt_130_130_8_8_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[8] >> 2) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_131_131_8_8_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 131;
    info.maxbit = 131;
    return info;
}

static void
field_fmt_131_131_8_8_set(uint32_t *pmd, uint32_t *val)
{
    pmd[8] = (pmd[8] & 0xfffffff7) | ((*val & 0x1) << 3);
}

static void
field_fmt_131_131_8_8_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[8] >> 3) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_132_132_8_8_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 132;
    info.maxbit = 132;
    return info;
}

static void
field_fmt_132_132_8_8_set(uint32_t *pmd, uint32_t *val)
{
    pmd[8] = (pmd[8] & 0xffffffef) | ((*val & 0x1) << 4);
}

static void
field_fmt_132_132_8_8_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[8] >> 4) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_133_133_8_8_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 133;
    info.maxbit = 133;
    return info;
}

static void
field_fmt_133_133_8_8_set(uint32_t *pmd, uint32_t *val)
{
    pmd[8] = (pmd[8] & 0xffffffdf) | ((*val & 0x1) << 5);
}

static void
field_fmt_133_133_8_8_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[8] >> 5) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_134_136_8_8_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 134;
    info.maxbit = 136;
    return info;
}

static void
field_fmt_134_136_8_8_set(uint32_t *pmd, uint32_t *val)
{
    pmd[8] = (pmd[8] & 0xfffffe3f) | ((*val & 0x7) << 6);
}

static void
field_fmt_134_136_8_8_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[8] >> 6) & 0x7;
}

static bcmpkt_field_info_t
field_fmt_134_139_8_8_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 134;
    info.maxbit = 139;
    return info;
}

static void
field_fmt_134_139_8_8_set(uint32_t *pmd, uint32_t *val)
{
    pmd[8] = (pmd[8] & 0xfffff03f) | ((*val & 0x3f) << 6);
}

static void
field_fmt_134_139_8_8_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[8] >> 6) & 0x3f;
}

static bcmpkt_field_info_t
field_fmt_13_13_12_12_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 13;
    info.maxbit = 13;
    return info;
}

static void
field_fmt_13_13_12_12_set(uint32_t *pmd, uint32_t *val)
{
    pmd[12] = (pmd[12] & 0xffffdfff) | ((*val & 0x1) << 13);
}

static void
field_fmt_13_13_12_12_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[12] >> 13) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_140_141_8_8_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 140;
    info.maxbit = 141;
    return info;
}

static void
field_fmt_140_141_8_8_set(uint32_t *pmd, uint32_t *val)
{
    pmd[8] = (pmd[8] & 0xffffcfff) | ((*val & 0x3) << 12);
}

static void
field_fmt_140_141_8_8_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[8] >> 12) & 0x3;
}

static bcmpkt_field_info_t
field_fmt_142_142_8_8_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 142;
    info.maxbit = 142;
    return info;
}

static void
field_fmt_142_142_8_8_set(uint32_t *pmd, uint32_t *val)
{
    pmd[8] = (pmd[8] & 0xffffbfff) | ((*val & 0x1) << 14);
}

static void
field_fmt_142_142_8_8_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[8] >> 14) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_143_143_8_8_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 143;
    info.maxbit = 143;
    return info;
}

static void
field_fmt_143_143_8_8_set(uint32_t *pmd, uint32_t *val)
{
    pmd[8] = (pmd[8] & 0xffff7fff) | ((*val & 0x1) << 15);
}

static void
field_fmt_143_143_8_8_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[8] >> 15) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_144_155_8_8_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 144;
    info.maxbit = 155;
    return info;
}

static void
field_fmt_144_155_8_8_set(uint32_t *pmd, uint32_t *val)
{
    pmd[8] = (pmd[8] & 0xf000ffff) | ((*val & 0xfff) << 16);
}

static void
field_fmt_144_155_8_8_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[8] >> 16) & 0xfff;
}

static bcmpkt_field_info_t
field_fmt_14_14_12_12_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 14;
    info.maxbit = 14;
    return info;
}

static void
field_fmt_14_14_12_12_set(uint32_t *pmd, uint32_t *val)
{
    pmd[12] = (pmd[12] & 0xffffbfff) | ((*val & 0x1) << 14);
}

static void
field_fmt_14_14_12_12_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[12] >> 14) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_156_158_8_8_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 156;
    info.maxbit = 158;
    return info;
}

static void
field_fmt_156_158_8_8_set(uint32_t *pmd, uint32_t *val)
{
    pmd[8] = (pmd[8] & 0x8fffffff) | ((*val & 0x7) << 28);
}

static void
field_fmt_156_158_8_8_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[8] >> 28) & 0x7;
}

static bcmpkt_field_info_t
field_fmt_159_159_8_8_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 159;
    info.maxbit = 159;
    return info;
}

static void
field_fmt_159_159_8_8_set(uint32_t *pmd, uint32_t *val)
{
    pmd[8] = (pmd[8] & 0x7fffffff) | (*val << 31);
}

static void
field_fmt_159_159_8_8_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[8] >> 31) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_15_15_12_12_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 15;
    info.maxbit = 15;
    return info;
}

static void
field_fmt_15_15_12_12_set(uint32_t *pmd, uint32_t *val)
{
    pmd[12] = (pmd[12] & 0xffff7fff) | ((*val & 0x1) << 15);
}

static void
field_fmt_15_15_12_12_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[12] >> 15) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_160_162_7_7_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 160;
    info.maxbit = 162;
    return info;
}

static void
field_fmt_160_162_7_7_set(uint32_t *pmd, uint32_t *val)
{
    pmd[7] = (pmd[7] & 0xfffffff8) | (*val & 0x7);
}

static void
field_fmt_160_162_7_7_get(uint32_t *pmd, uint32_t *val)
{
    *val = pmd[7] & 0x7;
}

static bcmpkt_field_info_t
field_fmt_163_174_7_7_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 163;
    info.maxbit = 174;
    return info;
}

static void
field_fmt_163_174_7_7_set(uint32_t *pmd, uint32_t *val)
{
    pmd[7] = (pmd[7] & 0xffff8007) | ((*val & 0xfff) << 3);
}

static void
field_fmt_163_174_7_7_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[7] >> 3) & 0xfff;
}

static bcmpkt_field_info_t
field_fmt_16_16_12_12_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 16;
    info.maxbit = 16;
    return info;
}

static void
field_fmt_16_16_12_12_set(uint32_t *pmd, uint32_t *val)
{
    pmd[12] = (pmd[12] & 0xfffeffff) | ((*val & 0x1) << 16);
}

static void
field_fmt_16_16_12_12_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[12] >> 16) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_175_191_7_7_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 175;
    info.maxbit = 191;
    return info;
}

static void
field_fmt_175_191_7_7_set(uint32_t *pmd, uint32_t *val)
{
    pmd[7] = (pmd[7] & 0x7fff) | (*val << 15);
}

static void
field_fmt_175_191_7_7_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[7] >> 15) & 0x1ffff;
}

static bcmpkt_field_info_t
field_fmt_17_17_12_12_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 17;
    info.maxbit = 17;
    return info;
}

static void
field_fmt_17_17_12_12_set(uint32_t *pmd, uint32_t *val)
{
    pmd[12] = (pmd[12] & 0xfffdffff) | ((*val & 0x1) << 17);
}

static void
field_fmt_17_17_12_12_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[12] >> 17) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_17_32_3_2_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 17;
    info.maxbit = 32;
    return info;
}

static void
field_fmt_17_32_3_2_set(uint32_t *pmd, uint32_t *val)
{
    pmd[3] = (pmd[3] & 0x1ffff) | (*val << 17);
    pmd[2] = (pmd[2] & 0xfffffffe) | ((*val >> 15) & 0x1);
}

static void
field_fmt_17_32_3_2_get(uint32_t *pmd, uint32_t *val)
{
    *val = ((pmd[3] >> 17) | (pmd[2] << 15)) & 0xffff;
}

static bcmpkt_field_info_t
field_fmt_18_18_12_12_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 18;
    info.maxbit = 18;
    return info;
}

static void
field_fmt_18_18_12_12_set(uint32_t *pmd, uint32_t *val)
{
    pmd[12] = (pmd[12] & 0xfffbffff) | ((*val & 0x1) << 18);
}

static void
field_fmt_18_18_12_12_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[12] >> 18) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_192_192_6_6_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 192;
    info.maxbit = 192;
    return info;
}

static void
field_fmt_192_192_6_6_set(uint32_t *pmd, uint32_t *val)
{
    pmd[6] = (pmd[6] & 0xfffffffe) | (*val & 0x1);
}

static void
field_fmt_192_192_6_6_get(uint32_t *pmd, uint32_t *val)
{
    *val = pmd[6] & 0x1;
}

static bcmpkt_field_info_t
field_fmt_193_212_6_6_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 193;
    info.maxbit = 212;
    return info;
}

static void
field_fmt_193_212_6_6_set(uint32_t *pmd, uint32_t *val)
{
    pmd[6] = (pmd[6] & 0xffe00001) | ((*val & 0xfffff) << 1);
}

static void
field_fmt_193_212_6_6_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[6] >> 1) & 0xfffff;
}

static bcmpkt_field_info_t
field_fmt_19_19_12_12_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 19;
    info.maxbit = 19;
    return info;
}

static void
field_fmt_19_19_12_12_set(uint32_t *pmd, uint32_t *val)
{
    pmd[12] = (pmd[12] & 0xfff7ffff) | ((*val & 0x1) << 19);
}

static void
field_fmt_19_19_12_12_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[12] >> 19) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_1_1_12_12_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 1;
    info.maxbit = 1;
    return info;
}

static void
field_fmt_1_1_12_12_set(uint32_t *pmd, uint32_t *val)
{
    pmd[12] = (pmd[12] & 0xfffffffd) | ((*val & 0x1) << 1);
}

static void
field_fmt_1_1_12_12_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[12] >> 1) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_1_2_3_3_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 1;
    info.maxbit = 2;
    return info;
}

static void
field_fmt_1_2_3_3_set(uint32_t *pmd, uint32_t *val)
{
    pmd[3] = (pmd[3] & 0xfffffff9) | ((*val & 0x3) << 1);
}

static void
field_fmt_1_2_3_3_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[3] >> 1) & 0x3;
}

static bcmpkt_field_info_t
field_fmt_20_20_12_12_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 20;
    info.maxbit = 20;
    return info;
}

static void
field_fmt_20_20_12_12_set(uint32_t *pmd, uint32_t *val)
{
    pmd[12] = (pmd[12] & 0xffefffff) | ((*val & 0x1) << 20);
}

static void
field_fmt_20_20_12_12_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[12] >> 20) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_213_213_6_6_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 213;
    info.maxbit = 213;
    return info;
}

static void
field_fmt_213_213_6_6_set(uint32_t *pmd, uint32_t *val)
{
    pmd[6] = (pmd[6] & 0xffdfffff) | ((*val & 0x1) << 21);
}

static void
field_fmt_213_213_6_6_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[6] >> 21) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_214_222_6_6_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 214;
    info.maxbit = 222;
    return info;
}

static void
field_fmt_214_222_6_6_set(uint32_t *pmd, uint32_t *val)
{
    pmd[6] = (pmd[6] & 0x803fffff) | ((*val & 0x1ff) << 22);
}

static void
field_fmt_214_222_6_6_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[6] >> 22) & 0x1ff;
}

static bcmpkt_field_info_t
field_fmt_21_21_12_12_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 21;
    info.maxbit = 21;
    return info;
}

static void
field_fmt_21_21_12_12_set(uint32_t *pmd, uint32_t *val)
{
    pmd[12] = (pmd[12] & 0xffdfffff) | ((*val & 0x1) << 21);
}

static void
field_fmt_21_21_12_12_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[12] >> 21) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_223_223_6_6_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 223;
    info.maxbit = 223;
    return info;
}

static void
field_fmt_223_223_6_6_set(uint32_t *pmd, uint32_t *val)
{
    pmd[6] = (pmd[6] & 0x7fffffff) | (*val << 31);
}

static void
field_fmt_223_223_6_6_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[6] >> 31) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_224_255_5_5_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 224;
    info.maxbit = 255;
    return info;
}

static void
field_fmt_224_255_5_5_set(uint32_t *pmd, uint32_t *val)
{
    pmd[5] = *val;
}

static void
field_fmt_224_255_5_5_get(uint32_t *pmd, uint32_t *val)
{
    *val = pmd[5];
}

static bcmpkt_field_info_t
field_fmt_22_22_12_12_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 22;
    info.maxbit = 22;
    return info;
}

static void
field_fmt_22_22_12_12_set(uint32_t *pmd, uint32_t *val)
{
    pmd[12] = (pmd[12] & 0xffbfffff) | ((*val & 0x1) << 22);
}

static void
field_fmt_22_22_12_12_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[12] >> 22) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_23_23_12_12_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 23;
    info.maxbit = 23;
    return info;
}

static void
field_fmt_23_23_12_12_set(uint32_t *pmd, uint32_t *val)
{
    pmd[12] = (pmd[12] & 0xff7fffff) | ((*val & 0x1) << 23);
}

static void
field_fmt_23_23_12_12_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[12] >> 23) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_24_24_12_12_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 24;
    info.maxbit = 24;
    return info;
}

static void
field_fmt_24_24_12_12_set(uint32_t *pmd, uint32_t *val)
{
    pmd[12] = (pmd[12] & 0xfeffffff) | ((*val & 0x1) << 24);
}

static void
field_fmt_24_24_12_12_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[12] >> 24) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_256_271_4_4_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 256;
    info.maxbit = 271;
    return info;
}

static void
field_fmt_256_271_4_4_set(uint32_t *pmd, uint32_t *val)
{
    pmd[4] = (pmd[4] & 0xffff0000) | (*val & 0xffff);
}

static void
field_fmt_256_271_4_4_get(uint32_t *pmd, uint32_t *val)
{
    *val = pmd[4] & 0xffff;
}

static bcmpkt_field_info_t
field_fmt_25_25_12_12_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 25;
    info.maxbit = 25;
    return info;
}

static void
field_fmt_25_25_12_12_set(uint32_t *pmd, uint32_t *val)
{
    pmd[12] = (pmd[12] & 0xfdffffff) | ((*val & 0x1) << 25);
}

static void
field_fmt_25_25_12_12_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[12] >> 25) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_25_28_3_3_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 25;
    info.maxbit = 28;
    return info;
}

static void
field_fmt_25_28_3_3_set(uint32_t *pmd, uint32_t *val)
{
    pmd[3] = (pmd[3] & 0xe1ffffff) | ((*val & 0xf) << 25);
}

static void
field_fmt_25_28_3_3_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[3] >> 25) & 0xf;
}

static bcmpkt_field_info_t
field_fmt_26_26_12_12_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 26;
    info.maxbit = 26;
    return info;
}

static void
field_fmt_26_26_12_12_set(uint32_t *pmd, uint32_t *val)
{
    pmd[12] = (pmd[12] & 0xfbffffff) | ((*val & 0x1) << 26);
}

static void
field_fmt_26_26_12_12_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[12] >> 26) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_272_272_4_4_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 272;
    info.maxbit = 272;
    return info;
}

static void
field_fmt_272_272_4_4_set(uint32_t *pmd, uint32_t *val)
{
    pmd[4] = (pmd[4] & 0xfffeffff) | ((*val & 0x1) << 16);
}

static void
field_fmt_272_272_4_4_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[4] >> 16) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_273_276_4_4_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 273;
    info.maxbit = 276;
    return info;
}

static void
field_fmt_273_276_4_4_set(uint32_t *pmd, uint32_t *val)
{
    pmd[4] = (pmd[4] & 0xffe1ffff) | ((*val & 0xf) << 17);
}

static void
field_fmt_273_276_4_4_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[4] >> 17) & 0xf;
}

static bcmpkt_field_info_t
field_fmt_277_277_4_4_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 277;
    info.maxbit = 277;
    return info;
}

static void
field_fmt_277_277_4_4_set(uint32_t *pmd, uint32_t *val)
{
    pmd[4] = (pmd[4] & 0xffdfffff) | ((*val & 0x1) << 21);
}

static void
field_fmt_277_277_4_4_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[4] >> 21) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_278_278_4_4_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 278;
    info.maxbit = 278;
    return info;
}

static void
field_fmt_278_278_4_4_set(uint32_t *pmd, uint32_t *val)
{
    pmd[4] = (pmd[4] & 0xffbfffff) | ((*val & 0x1) << 22);
}

static void
field_fmt_278_278_4_4_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[4] >> 22) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_279_280_4_4_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 279;
    info.maxbit = 280;
    return info;
}

static void
field_fmt_279_280_4_4_set(uint32_t *pmd, uint32_t *val)
{
    pmd[4] = (pmd[4] & 0xfe7fffff) | ((*val & 0x3) << 23);
}

static void
field_fmt_279_280_4_4_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[4] >> 23) & 0x3;
}

static bcmpkt_field_info_t
field_fmt_27_27_12_12_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 27;
    info.maxbit = 27;
    return info;
}

static void
field_fmt_27_27_12_12_set(uint32_t *pmd, uint32_t *val)
{
    pmd[12] = (pmd[12] & 0xf7ffffff) | ((*val & 0x1) << 27);
}

static void
field_fmt_27_27_12_12_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[12] >> 27) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_281_287_4_4_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 281;
    info.maxbit = 287;
    return info;
}

static void
field_fmt_281_287_4_4_set(uint32_t *pmd, uint32_t *val)
{
    pmd[4] = (pmd[4] & 0x1ffffff) | (*val << 25);
}

static void
field_fmt_281_287_4_4_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[4] >> 25) & 0x7f;
}

static bcmpkt_field_info_t
field_fmt_288_415_3_0_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 288;
    info.maxbit = 415;
    return info;
}

static void
field_fmt_288_415_3_0_set(uint32_t *pmd, uint32_t *val)
{
    pmd[3] = val[0];
    pmd[2] = val[1];
    pmd[1] = val[2];
    pmd[0] = val[3];
}

static void
field_fmt_288_415_3_0_get(uint32_t *pmd, uint32_t *val)
{
    val[0] = pmd[3];
    val[1] = pmd[2];
    val[2] = pmd[1];
    val[3] = pmd[0];
}

static bcmpkt_field_info_t
field_fmt_28_28_12_12_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 28;
    info.maxbit = 28;
    return info;
}

static void
field_fmt_28_28_12_12_set(uint32_t *pmd, uint32_t *val)
{
    pmd[12] = (pmd[12] & 0xefffffff) | ((*val & 0x1) << 28);
}

static void
field_fmt_28_28_12_12_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[12] >> 28) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_29_29_12_12_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 29;
    info.maxbit = 29;
    return info;
}

static void
field_fmt_29_29_12_12_set(uint32_t *pmd, uint32_t *val)
{
    pmd[12] = (pmd[12] & 0xdfffffff) | ((*val & 0x1) << 29);
}

static void
field_fmt_29_29_12_12_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[12] >> 29) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_29_29_3_3_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 29;
    info.maxbit = 29;
    return info;
}

static void
field_fmt_29_29_3_3_set(uint32_t *pmd, uint32_t *val)
{
    pmd[3] = (pmd[3] & 0xdfffffff) | ((*val & 0x1) << 29);
}

static void
field_fmt_29_29_3_3_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[3] >> 29) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_2_2_12_12_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 2;
    info.maxbit = 2;
    return info;
}

static void
field_fmt_2_2_12_12_set(uint32_t *pmd, uint32_t *val)
{
    pmd[12] = (pmd[12] & 0xfffffffb) | ((*val & 0x1) << 2);
}

static void
field_fmt_2_2_12_12_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[12] >> 2) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_30_30_12_12_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 30;
    info.maxbit = 30;
    return info;
}

static void
field_fmt_30_30_12_12_set(uint32_t *pmd, uint32_t *val)
{
    pmd[12] = (pmd[12] & 0xbfffffff) | ((*val & 0x1) << 30);
}

static void
field_fmt_30_30_12_12_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[12] >> 30) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_30_30_3_3_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 30;
    info.maxbit = 30;
    return info;
}

static void
field_fmt_30_30_3_3_set(uint32_t *pmd, uint32_t *val)
{
    pmd[3] = (pmd[3] & 0xbfffffff) | ((*val & 0x1) << 30);
}

static void
field_fmt_30_30_3_3_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[3] >> 30) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_31_31_12_12_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 31;
    info.maxbit = 31;
    return info;
}

static void
field_fmt_31_31_12_12_set(uint32_t *pmd, uint32_t *val)
{
    pmd[12] = (pmd[12] & 0x7fffffff) | (*val << 31);
}

static void
field_fmt_31_31_12_12_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[12] >> 31) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_31_31_3_3_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 31;
    info.maxbit = 31;
    return info;
}

static void
field_fmt_31_31_3_3_set(uint32_t *pmd, uint32_t *val)
{
    pmd[3] = (pmd[3] & 0x7fffffff) | (*val << 31);
}

static void
field_fmt_31_31_3_3_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[3] >> 31) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_32_32_11_11_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 32;
    info.maxbit = 32;
    return info;
}

static void
field_fmt_32_32_11_11_set(uint32_t *pmd, uint32_t *val)
{
    pmd[11] = (pmd[11] & 0xfffffffe) | (*val & 0x1);
}

static void
field_fmt_32_32_11_11_get(uint32_t *pmd, uint32_t *val)
{
    *val = pmd[11] & 0x1;
}

static bcmpkt_field_info_t
field_fmt_32_39_2_2_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 32;
    info.maxbit = 39;
    return info;
}

static void
field_fmt_32_39_2_2_set(uint32_t *pmd, uint32_t *val)
{
    pmd[2] = (pmd[2] & 0xffffff00) | (*val & 0xff);
}

static void
field_fmt_32_39_2_2_get(uint32_t *pmd, uint32_t *val)
{
    *val = pmd[2] & 0xff;
}

static bcmpkt_field_info_t
field_fmt_33_33_11_11_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 33;
    info.maxbit = 33;
    return info;
}

static void
field_fmt_33_33_11_11_set(uint32_t *pmd, uint32_t *val)
{
    pmd[11] = (pmd[11] & 0xfffffffd) | ((*val & 0x1) << 1);
}

static void
field_fmt_33_33_11_11_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[11] >> 1) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_33_36_2_2_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 33;
    info.maxbit = 36;
    return info;
}

static void
field_fmt_33_36_2_2_set(uint32_t *pmd, uint32_t *val)
{
    pmd[2] = (pmd[2] & 0xffffffe1) | ((*val & 0xf) << 1);
}

static void
field_fmt_33_36_2_2_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[2] >> 1) & 0xf;
}

static bcmpkt_field_info_t
field_fmt_34_34_11_11_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 34;
    info.maxbit = 34;
    return info;
}

static void
field_fmt_34_34_11_11_set(uint32_t *pmd, uint32_t *val)
{
    pmd[11] = (pmd[11] & 0xfffffffb) | ((*val & 0x1) << 2);
}

static void
field_fmt_34_34_11_11_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[11] >> 2) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_35_35_11_11_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 35;
    info.maxbit = 35;
    return info;
}

static void
field_fmt_35_35_11_11_set(uint32_t *pmd, uint32_t *val)
{
    pmd[11] = (pmd[11] & 0xfffffff7) | ((*val & 0x1) << 3);
}

static void
field_fmt_35_35_11_11_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[11] >> 3) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_36_36_11_11_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 36;
    info.maxbit = 36;
    return info;
}

static void
field_fmt_36_36_11_11_set(uint32_t *pmd, uint32_t *val)
{
    pmd[11] = (pmd[11] & 0xffffffef) | ((*val & 0x1) << 4);
}

static void
field_fmt_36_36_11_11_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[11] >> 4) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_37_37_11_11_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 37;
    info.maxbit = 37;
    return info;
}

static void
field_fmt_37_37_11_11_set(uint32_t *pmd, uint32_t *val)
{
    pmd[11] = (pmd[11] & 0xffffffdf) | ((*val & 0x1) << 5);
}

static void
field_fmt_37_37_11_11_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[11] >> 5) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_37_38_2_2_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 37;
    info.maxbit = 38;
    return info;
}

static void
field_fmt_37_38_2_2_set(uint32_t *pmd, uint32_t *val)
{
    pmd[2] = (pmd[2] & 0xffffff9f) | ((*val & 0x3) << 5);
}

static void
field_fmt_37_38_2_2_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[2] >> 5) & 0x3;
}

static bcmpkt_field_info_t
field_fmt_38_38_11_11_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 38;
    info.maxbit = 38;
    return info;
}

static void
field_fmt_38_38_11_11_set(uint32_t *pmd, uint32_t *val)
{
    pmd[11] = (pmd[11] & 0xffffffbf) | ((*val & 0x1) << 6);
}

static void
field_fmt_38_38_11_11_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[11] >> 6) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_39_39_11_11_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 39;
    info.maxbit = 39;
    return info;
}

static void
field_fmt_39_39_11_11_set(uint32_t *pmd, uint32_t *val)
{
    pmd[11] = (pmd[11] & 0xffffff7f) | ((*val & 0x1) << 7);
}

static void
field_fmt_39_39_11_11_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[11] >> 7) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_39_42_2_2_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 39;
    info.maxbit = 42;
    return info;
}

static void
field_fmt_39_42_2_2_set(uint32_t *pmd, uint32_t *val)
{
    pmd[2] = (pmd[2] & 0xfffff87f) | ((*val & 0xf) << 7);
}

static void
field_fmt_39_42_2_2_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[2] >> 7) & 0xf;
}

static bcmpkt_field_info_t
field_fmt_3_3_12_12_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 3;
    info.maxbit = 3;
    return info;
}

static void
field_fmt_3_3_12_12_set(uint32_t *pmd, uint32_t *val)
{
    pmd[12] = (pmd[12] & 0xfffffff7) | ((*val & 0x1) << 3);
}

static void
field_fmt_3_3_12_12_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[12] >> 3) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_3_8_3_3_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 3;
    info.maxbit = 8;
    return info;
}

static void
field_fmt_3_8_3_3_set(uint32_t *pmd, uint32_t *val)
{
    pmd[3] = (pmd[3] & 0xfffffe07) | ((*val & 0x3f) << 3);
}

static void
field_fmt_3_8_3_3_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[3] >> 3) & 0x3f;
}

static bcmpkt_field_info_t
field_fmt_40_40_11_11_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 40;
    info.maxbit = 40;
    return info;
}

static void
field_fmt_40_40_11_11_set(uint32_t *pmd, uint32_t *val)
{
    pmd[11] = (pmd[11] & 0xfffffeff) | ((*val & 0x1) << 8);
}

static void
field_fmt_40_40_11_11_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[11] >> 8) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_40_43_2_2_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 40;
    info.maxbit = 43;
    return info;
}

static void
field_fmt_40_43_2_2_set(uint32_t *pmd, uint32_t *val)
{
    pmd[2] = (pmd[2] & 0xfffff0ff) | ((*val & 0xf) << 8);
}

static void
field_fmt_40_43_2_2_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[2] >> 8) & 0xf;
}

static bcmpkt_field_info_t
field_fmt_41_41_11_11_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 41;
    info.maxbit = 41;
    return info;
}

static void
field_fmt_41_41_11_11_set(uint32_t *pmd, uint32_t *val)
{
    pmd[11] = (pmd[11] & 0xfffffdff) | ((*val & 0x1) << 9);
}

static void
field_fmt_41_41_11_11_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[11] >> 9) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_42_42_11_11_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 42;
    info.maxbit = 42;
    return info;
}

static void
field_fmt_42_42_11_11_set(uint32_t *pmd, uint32_t *val)
{
    pmd[11] = (pmd[11] & 0xfffffbff) | ((*val & 0x1) << 10);
}

static void
field_fmt_42_42_11_11_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[11] >> 10) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_43_43_11_11_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 43;
    info.maxbit = 43;
    return info;
}

static void
field_fmt_43_43_11_11_set(uint32_t *pmd, uint32_t *val)
{
    pmd[11] = (pmd[11] & 0xfffff7ff) | ((*val & 0x1) << 11);
}

static void
field_fmt_43_43_11_11_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[11] >> 11) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_43_44_2_2_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 43;
    info.maxbit = 44;
    return info;
}

static void
field_fmt_43_44_2_2_set(uint32_t *pmd, uint32_t *val)
{
    pmd[2] = (pmd[2] & 0xffffe7ff) | ((*val & 0x3) << 11);
}

static void
field_fmt_43_44_2_2_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[2] >> 11) & 0x3;
}

static bcmpkt_field_info_t
field_fmt_44_44_11_11_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 44;
    info.maxbit = 44;
    return info;
}

static void
field_fmt_44_44_11_11_set(uint32_t *pmd, uint32_t *val)
{
    pmd[11] = (pmd[11] & 0xffffefff) | ((*val & 0x1) << 12);
}

static void
field_fmt_44_44_11_11_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[11] >> 12) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_44_46_2_2_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 44;
    info.maxbit = 46;
    return info;
}

static void
field_fmt_44_46_2_2_set(uint32_t *pmd, uint32_t *val)
{
    pmd[2] = (pmd[2] & 0xffff8fff) | ((*val & 0x7) << 12);
}

static void
field_fmt_44_46_2_2_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[2] >> 12) & 0x7;
}

static bcmpkt_field_info_t
field_fmt_45_45_11_11_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 45;
    info.maxbit = 45;
    return info;
}

static void
field_fmt_45_45_11_11_set(uint32_t *pmd, uint32_t *val)
{
    pmd[11] = (pmd[11] & 0xffffdfff) | ((*val & 0x1) << 13);
}

static void
field_fmt_45_45_11_11_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[11] >> 13) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_45_45_2_2_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 45;
    info.maxbit = 45;
    return info;
}

static void
field_fmt_45_45_2_2_set(uint32_t *pmd, uint32_t *val)
{
    pmd[2] = (pmd[2] & 0xffffdfff) | ((*val & 0x1) << 13);
}

static void
field_fmt_45_45_2_2_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[2] >> 13) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_45_48_2_2_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 45;
    info.maxbit = 48;
    return info;
}

static void
field_fmt_45_48_2_2_set(uint32_t *pmd, uint32_t *val)
{
    pmd[2] = (pmd[2] & 0xfffe1fff) | ((*val & 0xf) << 13);
}

static void
field_fmt_45_48_2_2_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[2] >> 13) & 0xf;
}

static bcmpkt_field_info_t
field_fmt_46_46_2_2_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 46;
    info.maxbit = 46;
    return info;
}

static void
field_fmt_46_46_2_2_set(uint32_t *pmd, uint32_t *val)
{
    pmd[2] = (pmd[2] & 0xffffbfff) | ((*val & 0x1) << 14);
}

static void
field_fmt_46_46_2_2_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[2] >> 14) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_47_47_2_2_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 47;
    info.maxbit = 47;
    return info;
}

static void
field_fmt_47_47_2_2_set(uint32_t *pmd, uint32_t *val)
{
    pmd[2] = (pmd[2] & 0xffff7fff) | ((*val & 0x1) << 15);
}

static void
field_fmt_47_47_2_2_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[2] >> 15) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_47_48_2_2_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 47;
    info.maxbit = 48;
    return info;
}

static void
field_fmt_47_48_2_2_set(uint32_t *pmd, uint32_t *val)
{
    pmd[2] = (pmd[2] & 0xfffe7fff) | ((*val & 0x3) << 15);
}

static void
field_fmt_47_48_2_2_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[2] >> 15) & 0x3;
}

static bcmpkt_field_info_t
field_fmt_49_49_2_2_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 49;
    info.maxbit = 49;
    return info;
}

static void
field_fmt_49_49_2_2_set(uint32_t *pmd, uint32_t *val)
{
    pmd[2] = (pmd[2] & 0xfffdffff) | ((*val & 0x1) << 17);
}

static void
field_fmt_49_49_2_2_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[2] >> 17) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_49_50_2_2_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 49;
    info.maxbit = 50;
    return info;
}

static void
field_fmt_49_50_2_2_set(uint32_t *pmd, uint32_t *val)
{
    pmd[2] = (pmd[2] & 0xfff9ffff) | ((*val & 0x3) << 17);
}

static void
field_fmt_49_50_2_2_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[2] >> 17) & 0x3;
}

static bcmpkt_field_info_t
field_fmt_4_4_12_12_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 4;
    info.maxbit = 4;
    return info;
}

static void
field_fmt_4_4_12_12_set(uint32_t *pmd, uint32_t *val)
{
    pmd[12] = (pmd[12] & 0xffffffef) | ((*val & 0x1) << 4);
}

static void
field_fmt_4_4_12_12_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[12] >> 4) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_50_52_2_2_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 50;
    info.maxbit = 52;
    return info;
}

static void
field_fmt_50_52_2_2_set(uint32_t *pmd, uint32_t *val)
{
    pmd[2] = (pmd[2] & 0xffe3ffff) | ((*val & 0x7) << 18);
}

static void
field_fmt_50_52_2_2_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[2] >> 18) & 0x7;
}

static bcmpkt_field_info_t
field_fmt_51_51_2_2_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 51;
    info.maxbit = 51;
    return info;
}

static void
field_fmt_51_51_2_2_set(uint32_t *pmd, uint32_t *val)
{
    pmd[2] = (pmd[2] & 0xfff7ffff) | ((*val & 0x1) << 19);
}

static void
field_fmt_51_51_2_2_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[2] >> 19) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_52_59_2_2_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 52;
    info.maxbit = 59;
    return info;
}

static void
field_fmt_52_59_2_2_set(uint32_t *pmd, uint32_t *val)
{
    pmd[2] = (pmd[2] & 0xf00fffff) | ((*val & 0xff) << 20);
}

static void
field_fmt_52_59_2_2_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[2] >> 20) & 0xff;
}

static bcmpkt_field_info_t
field_fmt_53_53_2_2_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 53;
    info.maxbit = 53;
    return info;
}

static void
field_fmt_53_53_2_2_set(uint32_t *pmd, uint32_t *val)
{
    pmd[2] = (pmd[2] & 0xffdfffff) | ((*val & 0x1) << 21);
}

static void
field_fmt_53_53_2_2_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[2] >> 21) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_54_54_2_2_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 54;
    info.maxbit = 54;
    return info;
}

static void
field_fmt_54_54_2_2_set(uint32_t *pmd, uint32_t *val)
{
    pmd[2] = (pmd[2] & 0xffbfffff) | ((*val & 0x1) << 22);
}

static void
field_fmt_54_54_2_2_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[2] >> 22) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_55_67_2_1_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 55;
    info.maxbit = 67;
    return info;
}

static void
field_fmt_55_67_2_1_set(uint32_t *pmd, uint32_t *val)
{
    pmd[2] = (pmd[2] & 0x7fffff) | (*val << 23);
    pmd[1] = (pmd[1] & 0xfffffff0) | ((*val >> 9) & 0xf);
}

static void
field_fmt_55_67_2_1_get(uint32_t *pmd, uint32_t *val)
{
    *val = ((pmd[2] >> 23) | (pmd[1] << 9)) & 0x1fff;
}

static bcmpkt_field_info_t
field_fmt_5_5_12_12_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 5;
    info.maxbit = 5;
    return info;
}

static void
field_fmt_5_5_12_12_set(uint32_t *pmd, uint32_t *val)
{
    pmd[12] = (pmd[12] & 0xffffffdf) | ((*val & 0x1) << 5);
}

static void
field_fmt_5_5_12_12_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[12] >> 5) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_60_60_2_2_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 60;
    info.maxbit = 60;
    return info;
}

static void
field_fmt_60_60_2_2_set(uint32_t *pmd, uint32_t *val)
{
    pmd[2] = (pmd[2] & 0xefffffff) | ((*val & 0x1) << 28);
}

static void
field_fmt_60_60_2_2_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[2] >> 28) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_61_61_2_2_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 61;
    info.maxbit = 61;
    return info;
}

static void
field_fmt_61_61_2_2_set(uint32_t *pmd, uint32_t *val)
{
    pmd[2] = (pmd[2] & 0xdfffffff) | ((*val & 0x1) << 29);
}

static void
field_fmt_61_61_2_2_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[2] >> 29) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_62_62_2_2_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 62;
    info.maxbit = 62;
    return info;
}

static void
field_fmt_62_62_2_2_set(uint32_t *pmd, uint32_t *val)
{
    pmd[2] = (pmd[2] & 0xbfffffff) | ((*val & 0x1) << 30);
}

static void
field_fmt_62_62_2_2_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[2] >> 30) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_63_63_2_2_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 63;
    info.maxbit = 63;
    return info;
}

static void
field_fmt_63_63_2_2_set(uint32_t *pmd, uint32_t *val)
{
    pmd[2] = (pmd[2] & 0x7fffffff) | (*val << 31);
}

static void
field_fmt_63_63_2_2_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[2] >> 31) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_64_67_10_10_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 64;
    info.maxbit = 67;
    return info;
}

static void
field_fmt_64_67_10_10_set(uint32_t *pmd, uint32_t *val)
{
    pmd[10] = (pmd[10] & 0xfffffff0) | (*val & 0xf);
}

static void
field_fmt_64_67_10_10_get(uint32_t *pmd, uint32_t *val)
{
    *val = pmd[10] & 0xf;
}

static bcmpkt_field_info_t
field_fmt_66_78_1_1_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 66;
    info.maxbit = 78;
    return info;
}

static void
field_fmt_66_78_1_1_set(uint32_t *pmd, uint32_t *val)
{
    pmd[1] = (pmd[1] & 0xffff8003) | ((*val & 0x1fff) << 2);
}

static void
field_fmt_66_78_1_1_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[1] >> 2) & 0x1fff;
}

static bcmpkt_field_info_t
field_fmt_68_68_1_1_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 68;
    info.maxbit = 68;
    return info;
}

static void
field_fmt_68_68_1_1_set(uint32_t *pmd, uint32_t *val)
{
    pmd[1] = (pmd[1] & 0xffffffef) | ((*val & 0x1) << 4);
}

static void
field_fmt_68_68_1_1_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[1] >> 4) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_68_79_10_10_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 68;
    info.maxbit = 79;
    return info;
}

static void
field_fmt_68_79_10_10_set(uint32_t *pmd, uint32_t *val)
{
    pmd[10] = (pmd[10] & 0xffff000f) | ((*val & 0xfff) << 4);
}

static void
field_fmt_68_79_10_10_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[10] >> 4) & 0xfff;
}

static bcmpkt_field_info_t
field_fmt_68_80_10_10_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 68;
    info.maxbit = 80;
    return info;
}

static void
field_fmt_68_80_10_10_set(uint32_t *pmd, uint32_t *val)
{
    pmd[10] = (pmd[10] & 0xfffe000f) | ((*val & 0x1fff) << 4);
}

static void
field_fmt_68_80_10_10_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[10] >> 4) & 0x1fff;
}

static bcmpkt_field_info_t
field_fmt_6_6_12_12_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 6;
    info.maxbit = 6;
    return info;
}

static void
field_fmt_6_6_12_12_set(uint32_t *pmd, uint32_t *val)
{
    pmd[12] = (pmd[12] & 0xffffffbf) | ((*val & 0x1) << 6);
}

static void
field_fmt_6_6_12_12_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[12] >> 6) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_7_7_12_12_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 7;
    info.maxbit = 7;
    return info;
}

static void
field_fmt_7_7_12_12_set(uint32_t *pmd, uint32_t *val)
{
    pmd[12] = (pmd[12] & 0xffffff7f) | ((*val & 0x1) << 7);
}

static void
field_fmt_7_7_12_12_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[12] >> 7) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_80_81_10_10_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 80;
    info.maxbit = 81;
    return info;
}

static void
field_fmt_80_81_10_10_set(uint32_t *pmd, uint32_t *val)
{
    pmd[10] = (pmd[10] & 0xfffcffff) | ((*val & 0x3) << 16);
}

static void
field_fmt_80_81_10_10_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[10] >> 16) & 0x3;
}

static bcmpkt_field_info_t
field_fmt_80_82_1_1_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 80;
    info.maxbit = 82;
    return info;
}

static void
field_fmt_80_82_1_1_set(uint32_t *pmd, uint32_t *val)
{
    pmd[1] = (pmd[1] & 0xfff8ffff) | ((*val & 0x7) << 16);
}

static void
field_fmt_80_82_1_1_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[1] >> 16) & 0x7;
}

static bcmpkt_field_info_t
field_fmt_80_83_10_10_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 80;
    info.maxbit = 83;
    return info;
}

static void
field_fmt_80_83_10_10_set(uint32_t *pmd, uint32_t *val)
{
    pmd[10] = (pmd[10] & 0xfff0ffff) | ((*val & 0xf) << 16);
}

static void
field_fmt_80_83_10_10_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[10] >> 16) & 0xf;
}

static bcmpkt_field_info_t
field_fmt_82_89_10_10_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 82;
    info.maxbit = 89;
    return info;
}

static void
field_fmt_82_89_10_10_set(uint32_t *pmd, uint32_t *val)
{
    pmd[10] = (pmd[10] & 0xfc03ffff) | ((*val & 0xff) << 18);
}

static void
field_fmt_82_89_10_10_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[10] >> 18) & 0xff;
}

static bcmpkt_field_info_t
field_fmt_83_83_1_1_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 83;
    info.maxbit = 83;
    return info;
}

static void
field_fmt_83_83_1_1_set(uint32_t *pmd, uint32_t *val)
{
    pmd[1] = (pmd[1] & 0xfff7ffff) | ((*val & 0x1) << 19);
}

static void
field_fmt_83_83_1_1_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[1] >> 19) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_84_84_10_10_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 84;
    info.maxbit = 84;
    return info;
}

static void
field_fmt_84_84_10_10_set(uint32_t *pmd, uint32_t *val)
{
    pmd[10] = (pmd[10] & 0xffefffff) | ((*val & 0x1) << 20);
}

static void
field_fmt_84_84_10_10_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[10] >> 20) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_85_93_1_1_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 85;
    info.maxbit = 93;
    return info;
}

static void
field_fmt_85_93_1_1_set(uint32_t *pmd, uint32_t *val)
{
    pmd[1] = (pmd[1] & 0xc01fffff) | ((*val & 0x1ff) << 21);
}

static void
field_fmt_85_93_1_1_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[1] >> 21) & 0x1ff;
}

static bcmpkt_field_info_t
field_fmt_8_8_12_12_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 8;
    info.maxbit = 8;
    return info;
}

static void
field_fmt_8_8_12_12_set(uint32_t *pmd, uint32_t *val)
{
    pmd[12] = (pmd[12] & 0xfffffeff) | ((*val & 0x1) << 8);
}

static void
field_fmt_8_8_12_12_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[12] >> 8) & 0x1;
}

static bcmpkt_field_info_t
field_fmt_90_95_10_10_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 90;
    info.maxbit = 95;
    return info;
}

static void
field_fmt_90_95_10_10_set(uint32_t *pmd, uint32_t *val)
{
    pmd[10] = (pmd[10] & 0x3ffffff) | (*val << 26);
}

static void
field_fmt_90_95_10_10_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[10] >> 26) & 0x3f;
}

static bcmpkt_field_info_t
field_fmt_96_96_9_9_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 96;
    info.maxbit = 96;
    return info;
}

static void
field_fmt_96_96_9_9_set(uint32_t *pmd, uint32_t *val)
{
    pmd[9] = (pmd[9] & 0xfffffffe) | (*val & 0x1);
}

static void
field_fmt_96_96_9_9_get(uint32_t *pmd, uint32_t *val)
{
    *val = pmd[9] & 0x1;
}

static bcmpkt_field_info_t
field_fmt_97_98_9_9_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 97;
    info.maxbit = 98;
    return info;
}

static void
field_fmt_97_98_9_9_set(uint32_t *pmd, uint32_t *val)
{
    pmd[9] = (pmd[9] & 0xfffffff9) | ((*val & 0x3) << 1);
}

static void
field_fmt_97_98_9_9_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[9] >> 1) & 0x3;
}

static bcmpkt_field_info_t
field_fmt_99_112_9_9_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 99;
    info.maxbit = 112;
    return info;
}

static void
field_fmt_99_112_9_9_set(uint32_t *pmd, uint32_t *val)
{
    pmd[9] = (pmd[9] & 0xfffe0007) | ((*val & 0x3fff) << 3);
}

static void
field_fmt_99_112_9_9_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[9] >> 3) & 0x3fff;
}

static bcmpkt_field_info_t
field_fmt_9_24_3_3_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 9;
    info.maxbit = 24;
    return info;
}

static void
field_fmt_9_24_3_3_set(uint32_t *pmd, uint32_t *val)
{
    pmd[3] = (pmd[3] & 0xfe0001ff) | ((*val & 0xffff) << 9);
}

static void
field_fmt_9_24_3_3_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[3] >> 9) & 0xffff;
}

static bcmpkt_field_info_t
field_fmt_9_9_12_12_info(void)
{
    bcmpkt_field_info_t info;
    info.minbit = 9;
    info.maxbit = 9;
    return info;
}

static void
field_fmt_9_9_12_12_set(uint32_t *pmd, uint32_t *val)
{
    pmd[12] = (pmd[12] & 0xfffffdff) | ((*val & 0x1) << 9);
}

static void
field_fmt_9_9_12_12_get(uint32_t *pmd, uint32_t *val)
{
    *val = (pmd[12] >> 9) & 0x1;
}

static const shr_enum_map_t bcm78900_b0_rxpmd_reason_type_names[] =
{
    BCM78900_B0_RXPMD_REASON_TYPE_NAME_MAP_INIT
};

static const shr_enum_map_t bcm78900_b0_rxpmd_ieee_802_1as_timestamp_enabled_names[] =
{
    BCM78900_B0_RXPMD_IEEE_802_1AS_TIMESTAMP_ENABLED_NAME_MAP_INIT
};

static bcmpkt_pmd_field_t bcm78900_b0_rxpmd_fields[BCM78900_B0_RXPMD_COUNT] = {
    {2, field_fmt_0_63_12_11_info, field_fmt_0_63_12_11_set, field_fmt_0_63_12_11_get, NULL, 0},
    {1, field_fmt_64_67_10_10_info, field_fmt_64_67_10_10_set, field_fmt_64_67_10_10_get, bcm78900_b0_rxpmd_reason_type_names, 0},
    {1, field_fmt_68_80_10_10_info, field_fmt_68_80_10_10_set, field_fmt_68_80_10_10_get, NULL, 0},
    {1, field_fmt_68_79_10_10_info, field_fmt_68_79_10_10_set, field_fmt_68_79_10_10_get, NULL, 0},
    {1, field_fmt_68_79_10_10_info, field_fmt_68_79_10_10_set, field_fmt_68_79_10_10_get, NULL, 0},
    {1, field_fmt_80_83_10_10_info, field_fmt_80_83_10_10_set, field_fmt_80_83_10_10_get, NULL, 0},
    {1, field_fmt_80_81_10_10_info, field_fmt_80_81_10_10_set, field_fmt_80_81_10_10_get, NULL, 0},
    {1, field_fmt_82_89_10_10_info, field_fmt_82_89_10_10_set, field_fmt_82_89_10_10_get, NULL, 0},
    {1, field_fmt_84_84_10_10_info, field_fmt_84_84_10_10_set, field_fmt_84_84_10_10_get, NULL, 0},
    {1, field_fmt_90_95_10_10_info, field_fmt_90_95_10_10_set, field_fmt_90_95_10_10_get, NULL, 0},
    {1, field_fmt_90_95_10_10_info, field_fmt_90_95_10_10_set, field_fmt_90_95_10_10_get, NULL, 0},
    {1, field_fmt_96_96_9_9_info, field_fmt_96_96_9_9_set, field_fmt_96_96_9_9_get, NULL, 0},
    {1, field_fmt_97_98_9_9_info, field_fmt_97_98_9_9_set, field_fmt_97_98_9_9_get, NULL, 0},
    {1, field_fmt_99_112_9_9_info, field_fmt_99_112_9_9_set, field_fmt_99_112_9_9_get, NULL, 0},
    {1, field_fmt_113_127_9_9_info, field_fmt_113_127_9_9_set, field_fmt_113_127_9_9_get, NULL, 0},
    {1, field_fmt_128_128_8_8_info, field_fmt_128_128_8_8_set, field_fmt_128_128_8_8_get, NULL, 0},
    {1, field_fmt_129_129_8_8_info, field_fmt_129_129_8_8_set, field_fmt_129_129_8_8_get, NULL, 0},
    {1, field_fmt_130_130_8_8_info, field_fmt_130_130_8_8_set, field_fmt_130_130_8_8_get, NULL, 0},
    {1, field_fmt_131_131_8_8_info, field_fmt_131_131_8_8_set, field_fmt_131_131_8_8_get, NULL, 0},
    {1, field_fmt_132_132_8_8_info, field_fmt_132_132_8_8_set, field_fmt_132_132_8_8_get, NULL, 0},
    {1, field_fmt_133_133_8_8_info, field_fmt_133_133_8_8_set, field_fmt_133_133_8_8_get, NULL, 0},
    {1, field_fmt_134_139_8_8_info, field_fmt_134_139_8_8_set, field_fmt_134_139_8_8_get, NULL, 0},
    {1, field_fmt_134_136_8_8_info, field_fmt_134_136_8_8_set, field_fmt_134_136_8_8_get, NULL, 0},
    {1, field_fmt_140_141_8_8_info, field_fmt_140_141_8_8_set, field_fmt_140_141_8_8_get, NULL, 0},
    {1, field_fmt_142_142_8_8_info, field_fmt_142_142_8_8_set, field_fmt_142_142_8_8_get, NULL, 0},
    {1, field_fmt_143_143_8_8_info, field_fmt_143_143_8_8_set, field_fmt_143_143_8_8_get, NULL, 0},
    {1, field_fmt_144_155_8_8_info, field_fmt_144_155_8_8_set, field_fmt_144_155_8_8_get, NULL, 0},
    {1, field_fmt_156_158_8_8_info, field_fmt_156_158_8_8_set, field_fmt_156_158_8_8_get, NULL, 0},
    {1, field_fmt_159_159_8_8_info, field_fmt_159_159_8_8_set, field_fmt_159_159_8_8_get, NULL, 0},
    {1, field_fmt_160_162_7_7_info, field_fmt_160_162_7_7_set, field_fmt_160_162_7_7_get, NULL, 0},
    {1, field_fmt_163_174_7_7_info, field_fmt_163_174_7_7_set, field_fmt_163_174_7_7_get, NULL, 0},
    {1, field_fmt_175_191_7_7_info, field_fmt_175_191_7_7_set, field_fmt_175_191_7_7_get, NULL, 0},
    {1, field_fmt_192_192_6_6_info, field_fmt_192_192_6_6_set, field_fmt_192_192_6_6_get, NULL, 0},
    {1, field_fmt_193_212_6_6_info, field_fmt_193_212_6_6_set, field_fmt_193_212_6_6_get, NULL, 0},
    {1, field_fmt_213_213_6_6_info, field_fmt_213_213_6_6_set, field_fmt_213_213_6_6_get, NULL, 0},
    {1, field_fmt_214_222_6_6_info, field_fmt_214_222_6_6_set, field_fmt_214_222_6_6_get, NULL, 0},
    {1, field_fmt_223_223_6_6_info, field_fmt_223_223_6_6_set, field_fmt_223_223_6_6_get, NULL, 0},
    {1, field_fmt_224_255_5_5_info, field_fmt_224_255_5_5_set, field_fmt_224_255_5_5_get, NULL, 0},
    {1, field_fmt_256_271_4_4_info, field_fmt_256_271_4_4_set, field_fmt_256_271_4_4_get, NULL, 0},
    {1, field_fmt_272_272_4_4_info, field_fmt_272_272_4_4_set, field_fmt_272_272_4_4_get, bcm78900_b0_rxpmd_ieee_802_1as_timestamp_enabled_names, 0},
    {1, field_fmt_273_276_4_4_info, field_fmt_273_276_4_4_set, field_fmt_273_276_4_4_get, NULL, 0},
    {1, field_fmt_277_277_4_4_info, field_fmt_277_277_4_4_set, field_fmt_277_277_4_4_get, NULL, 0},
    {1, field_fmt_278_278_4_4_info, field_fmt_278_278_4_4_set, field_fmt_278_278_4_4_get, NULL, 0},
    {1, field_fmt_279_280_4_4_info, field_fmt_279_280_4_4_set, field_fmt_279_280_4_4_get, NULL, 0},
    {1, field_fmt_281_287_4_4_info, field_fmt_281_287_4_4_set, field_fmt_281_287_4_4_get, NULL, 0},
    {4, field_fmt_288_415_3_0_info, field_fmt_288_415_3_0_set, field_fmt_288_415_3_0_get, NULL, 0},

};

static const shr_enum_map_t bcm78900_b0_rxpmd_names[] =
{
    BCM78900_B0_RXPMD_NAME_MAP_INIT
};

bcmpkt_pmd_info_t bcm78900_b0_rxpmd_info_get(void)
{
    bcmpkt_pmd_info_t bcm78900_b0_rxpmd_info = {13, BCM78900_B0_RXPMD_COUNT, bcm78900_b0_rxpmd_names, bcm78900_b0_rxpmd_fields};
    return bcm78900_b0_rxpmd_info;
}

static bcmpkt_pmd_field_t bcm78900_b0_rx_reason_fields[BCM78900_B0_RX_REASON_COUNT] = {
    {1, field_fmt_0_0_12_12_info, field_fmt_0_0_12_12_set, field_fmt_0_0_12_12_get, NULL, 0},
    {1, field_fmt_1_1_12_12_info, field_fmt_1_1_12_12_set, field_fmt_1_1_12_12_get, NULL, 0},
    {1, field_fmt_2_2_12_12_info, field_fmt_2_2_12_12_set, field_fmt_2_2_12_12_get, NULL, 0},
    {1, field_fmt_3_3_12_12_info, field_fmt_3_3_12_12_set, field_fmt_3_3_12_12_get, NULL, 0},
    {1, field_fmt_4_4_12_12_info, field_fmt_4_4_12_12_set, field_fmt_4_4_12_12_get, NULL, 0},
    {1, field_fmt_5_5_12_12_info, field_fmt_5_5_12_12_set, field_fmt_5_5_12_12_get, NULL, 0},
    {1, field_fmt_6_6_12_12_info, field_fmt_6_6_12_12_set, field_fmt_6_6_12_12_get, NULL, 0},
    {1, field_fmt_7_7_12_12_info, field_fmt_7_7_12_12_set, field_fmt_7_7_12_12_get, NULL, 0},
    {1, field_fmt_8_8_12_12_info, field_fmt_8_8_12_12_set, field_fmt_8_8_12_12_get, NULL, 0},
    {1, field_fmt_9_9_12_12_info, field_fmt_9_9_12_12_set, field_fmt_9_9_12_12_get, NULL, 0},
    {1, field_fmt_10_10_12_12_info, field_fmt_10_10_12_12_set, field_fmt_10_10_12_12_get, NULL, 0},
    {1, field_fmt_11_11_12_12_info, field_fmt_11_11_12_12_set, field_fmt_11_11_12_12_get, NULL, 0},
    {1, field_fmt_12_12_12_12_info, field_fmt_12_12_12_12_set, field_fmt_12_12_12_12_get, NULL, 0},
    {1, field_fmt_13_13_12_12_info, field_fmt_13_13_12_12_set, field_fmt_13_13_12_12_get, NULL, 0},
    {1, field_fmt_14_14_12_12_info, field_fmt_14_14_12_12_set, field_fmt_14_14_12_12_get, NULL, 0},
    {1, field_fmt_15_15_12_12_info, field_fmt_15_15_12_12_set, field_fmt_15_15_12_12_get, NULL, 0},
    {1, field_fmt_16_16_12_12_info, field_fmt_16_16_12_12_set, field_fmt_16_16_12_12_get, NULL, 0},
    {1, field_fmt_17_17_12_12_info, field_fmt_17_17_12_12_set, field_fmt_17_17_12_12_get, NULL, 0},
    {1, field_fmt_18_18_12_12_info, field_fmt_18_18_12_12_set, field_fmt_18_18_12_12_get, NULL, 0},
    {1, field_fmt_19_19_12_12_info, field_fmt_19_19_12_12_set, field_fmt_19_19_12_12_get, NULL, 0},
    {1, field_fmt_20_20_12_12_info, field_fmt_20_20_12_12_set, field_fmt_20_20_12_12_get, NULL, 0},
    {1, field_fmt_21_21_12_12_info, field_fmt_21_21_12_12_set, field_fmt_21_21_12_12_get, NULL, 0},
    {1, field_fmt_22_22_12_12_info, field_fmt_22_22_12_12_set, field_fmt_22_22_12_12_get, NULL, 0},
    {1, field_fmt_23_23_12_12_info, field_fmt_23_23_12_12_set, field_fmt_23_23_12_12_get, NULL, 0},
    {1, field_fmt_24_24_12_12_info, field_fmt_24_24_12_12_set, field_fmt_24_24_12_12_get, NULL, 0},
    {1, field_fmt_25_25_12_12_info, field_fmt_25_25_12_12_set, field_fmt_25_25_12_12_get, NULL, 0},
    {1, field_fmt_26_26_12_12_info, field_fmt_26_26_12_12_set, field_fmt_26_26_12_12_get, NULL, 0},
    {1, field_fmt_27_27_12_12_info, field_fmt_27_27_12_12_set, field_fmt_27_27_12_12_get, NULL, 0},
    {1, field_fmt_28_28_12_12_info, field_fmt_28_28_12_12_set, field_fmt_28_28_12_12_get, NULL, 0},
    {1, field_fmt_29_29_12_12_info, field_fmt_29_29_12_12_set, field_fmt_29_29_12_12_get, NULL, 0},
    {1, field_fmt_30_30_12_12_info, field_fmt_30_30_12_12_set, field_fmt_30_30_12_12_get, NULL, 0},
    {1, field_fmt_31_31_12_12_info, field_fmt_31_31_12_12_set, field_fmt_31_31_12_12_get, NULL, 0},
    {1, field_fmt_32_32_11_11_info, field_fmt_32_32_11_11_set, field_fmt_32_32_11_11_get, NULL, 0},
    {1, field_fmt_33_33_11_11_info, field_fmt_33_33_11_11_set, field_fmt_33_33_11_11_get, NULL, 0},
    {1, field_fmt_34_34_11_11_info, field_fmt_34_34_11_11_set, field_fmt_34_34_11_11_get, NULL, 0},
    {1, field_fmt_35_35_11_11_info, field_fmt_35_35_11_11_set, field_fmt_35_35_11_11_get, NULL, 0},
    {1, field_fmt_36_36_11_11_info, field_fmt_36_36_11_11_set, field_fmt_36_36_11_11_get, NULL, 0},
    {1, field_fmt_37_37_11_11_info, field_fmt_37_37_11_11_set, field_fmt_37_37_11_11_get, NULL, 0},
    {1, field_fmt_38_38_11_11_info, field_fmt_38_38_11_11_set, field_fmt_38_38_11_11_get, NULL, 0},
    {1, field_fmt_39_39_11_11_info, field_fmt_39_39_11_11_set, field_fmt_39_39_11_11_get, NULL, 0},
    {1, field_fmt_40_40_11_11_info, field_fmt_40_40_11_11_set, field_fmt_40_40_11_11_get, NULL, 0},
    {1, field_fmt_41_41_11_11_info, field_fmt_41_41_11_11_set, field_fmt_41_41_11_11_get, NULL, 0},
    {1, field_fmt_42_42_11_11_info, field_fmt_42_42_11_11_set, field_fmt_42_42_11_11_get, NULL, 0},
    {1, field_fmt_43_43_11_11_info, field_fmt_43_43_11_11_set, field_fmt_43_43_11_11_get, NULL, 0},
    {1, field_fmt_44_44_11_11_info, field_fmt_44_44_11_11_set, field_fmt_44_44_11_11_get, NULL, 0},
    {1, field_fmt_45_45_11_11_info, field_fmt_45_45_11_11_set, field_fmt_45_45_11_11_get, NULL, 0},

};

static const shr_enum_map_t bcm78900_b0_rx_reason_names[] =
{
    BCM78900_B0_RX_REASON_NAME_MAP_INIT
};

bcmpkt_pmd_info_t bcm78900_b0_rx_reason_info_get(void)
{
    bcmpkt_pmd_info_t bcm78900_b0_rx_reason_info = {13, BCM78900_B0_RX_REASON_COUNT, bcm78900_b0_rx_reason_names, bcm78900_b0_rx_reason_fields};
    return bcm78900_b0_rx_reason_info;
}

static bcmpkt_pmd_field_t bcm78900_b0_ep_rx_reason_fields[BCM78900_B0_EP_RX_REASON_COUNT] = {
    {1, field_fmt_0_0_12_12_info, field_fmt_0_0_12_12_set, field_fmt_0_0_12_12_get, NULL, 0},

};

static const shr_enum_map_t bcm78900_b0_ep_rx_reason_names[] =
{
    BCM78900_B0_EP_RX_REASON_NAME_MAP_INIT
};

bcmpkt_pmd_info_t bcm78900_b0_ep_rx_reason_info_get(void)
{
    bcmpkt_pmd_info_t bcm78900_b0_ep_rx_reason_info = {13, BCM78900_B0_EP_RX_REASON_COUNT, bcm78900_b0_ep_rx_reason_names, bcm78900_b0_ep_rx_reason_fields};
    return bcm78900_b0_ep_rx_reason_info;
}

static const shr_enum_map_t bcm78900_b0_txpmd_cpu_tx_destination_type_names[] =
{
    BCM78900_B0_TXPMD_CPU_TX_DESTINATION_TYPE_NAME_MAP_INIT
};

static const shr_enum_map_t bcm78900_b0_txpmd_cpu_tx_dp_names[] =
{
    BCM78900_B0_TXPMD_CPU_TX_DP_NAME_MAP_INIT
};

static const shr_enum_map_t bcm78900_b0_txpmd_sobmh_from_cpu_destination_type_names[] =
{
    BCM78900_B0_TXPMD_SOBMH_FROM_CPU_DESTINATION_TYPE_NAME_MAP_INIT
};

static const shr_enum_map_t bcm78900_b0_txpmd_header_type_names[] =
{
    BCM78900_B0_TXPMD_HEADER_TYPE_NAME_MAP_INIT
};

static const shr_enum_map_t bcm78900_b0_txpmd_start_names[] =
{
    BCM78900_B0_TXPMD_START_NAME_MAP_INIT
};

static bcmpkt_pmd_field_t bcm78900_b0_txpmd_fields[BCM78900_B0_TXPMD_COUNT] = {
    {1, field_fmt_0_16_3_3_info, field_fmt_0_16_3_3_set, field_fmt_0_16_3_3_get, NULL, 2},
    {1, field_fmt_0_7_3_3_info, field_fmt_0_7_3_3_set, field_fmt_0_7_3_3_get, NULL, 2},
    {1, field_fmt_17_32_3_2_info, field_fmt_17_32_3_2_set, field_fmt_17_32_3_2_get, NULL, 2},
    {1, field_fmt_33_36_2_2_info, field_fmt_33_36_2_2_set, field_fmt_33_36_2_2_get, bcm78900_b0_txpmd_cpu_tx_destination_type_names, 2},
    {1, field_fmt_37_38_2_2_info, field_fmt_37_38_2_2_set, field_fmt_37_38_2_2_get, bcm78900_b0_txpmd_cpu_tx_dp_names, 2},
    {1, field_fmt_39_42_2_2_info, field_fmt_39_42_2_2_set, field_fmt_39_42_2_2_get, NULL, 2},
    {1, field_fmt_43_44_2_2_info, field_fmt_43_44_2_2_set, field_fmt_43_44_2_2_get, NULL, 2},
    {1, field_fmt_45_48_2_2_info, field_fmt_45_48_2_2_set, field_fmt_45_48_2_2_get, NULL, 2},
    {1, field_fmt_49_49_2_2_info, field_fmt_49_49_2_2_set, field_fmt_49_49_2_2_get, NULL, 2},
    {1, field_fmt_50_52_2_2_info, field_fmt_50_52_2_2_set, field_fmt_50_52_2_2_get, NULL, 2},
    {1, field_fmt_53_53_2_2_info, field_fmt_53_53_2_2_set, field_fmt_53_53_2_2_get, NULL, 2},
    {1, field_fmt_54_54_2_2_info, field_fmt_54_54_2_2_set, field_fmt_54_54_2_2_get, NULL, 2},
    {1, field_fmt_55_67_2_1_info, field_fmt_55_67_2_1_set, field_fmt_55_67_2_1_get, NULL, 2},
    {1, field_fmt_68_68_1_1_info, field_fmt_68_68_1_1_set, field_fmt_68_68_1_1_get, NULL, 2},
    {1, field_fmt_0_0_3_3_info, field_fmt_0_0_3_3_set, field_fmt_0_0_3_3_get, NULL, 1},
    {1, field_fmt_1_2_3_3_info, field_fmt_1_2_3_3_set, field_fmt_1_2_3_3_get, NULL, 1},
    {1, field_fmt_3_8_3_3_info, field_fmt_3_8_3_3_set, field_fmt_3_8_3_3_get, NULL, 1},
    {1, field_fmt_9_24_3_3_info, field_fmt_9_24_3_3_set, field_fmt_9_24_3_3_get, NULL, 1},
    {1, field_fmt_25_28_3_3_info, field_fmt_25_28_3_3_set, field_fmt_25_28_3_3_get, bcm78900_b0_txpmd_sobmh_from_cpu_destination_type_names, 1},
    {1, field_fmt_29_29_3_3_info, field_fmt_29_29_3_3_set, field_fmt_29_29_3_3_get, NULL, 1},
    {1, field_fmt_30_30_3_3_info, field_fmt_30_30_3_3_set, field_fmt_30_30_3_3_get, NULL, 1},
    {1, field_fmt_31_31_3_3_info, field_fmt_31_31_3_3_set, field_fmt_31_31_3_3_get, NULL, 1},
    {1, field_fmt_32_39_2_2_info, field_fmt_32_39_2_2_set, field_fmt_32_39_2_2_get, NULL, 1},
    {1, field_fmt_40_43_2_2_info, field_fmt_40_43_2_2_set, field_fmt_40_43_2_2_get, NULL, 1},
    {1, field_fmt_44_46_2_2_info, field_fmt_44_46_2_2_set, field_fmt_44_46_2_2_get, NULL, 1},
    {1, field_fmt_47_48_2_2_info, field_fmt_47_48_2_2_set, field_fmt_47_48_2_2_get, NULL, 1},
    {1, field_fmt_49_50_2_2_info, field_fmt_49_50_2_2_set, field_fmt_49_50_2_2_get, NULL, 1},
    {1, field_fmt_51_51_2_2_info, field_fmt_51_51_2_2_set, field_fmt_51_51_2_2_get, NULL, 1},
    {1, field_fmt_52_59_2_2_info, field_fmt_52_59_2_2_set, field_fmt_52_59_2_2_get, NULL, 1},
    {1, field_fmt_60_60_2_2_info, field_fmt_60_60_2_2_set, field_fmt_60_60_2_2_get, NULL, 1},
    {1, field_fmt_61_61_2_2_info, field_fmt_61_61_2_2_set, field_fmt_61_61_2_2_get, NULL, 1},
    {1, field_fmt_62_62_2_2_info, field_fmt_62_62_2_2_set, field_fmt_62_62_2_2_get, NULL, 1},
    {1, field_fmt_63_63_2_2_info, field_fmt_63_63_2_2_set, field_fmt_63_63_2_2_get, NULL, 1},
    {1, field_fmt_120_125_0_0_info, field_fmt_120_125_0_0_set, field_fmt_120_125_0_0_get, bcm78900_b0_txpmd_header_type_names, 0},
    {1, field_fmt_126_127_0_0_info, field_fmt_126_127_0_0_set, field_fmt_126_127_0_0_get, bcm78900_b0_txpmd_start_names, 0},

};

static const shr_enum_map_t bcm78900_b0_txpmd_names[] =
{
    BCM78900_B0_TXPMD_NAME_MAP_INIT
};

bcmpkt_pmd_info_t bcm78900_b0_txpmd_info_get(void)
{
    bcmpkt_pmd_info_t bcm78900_b0_txpmd_info = {4, BCM78900_B0_TXPMD_COUNT, bcm78900_b0_txpmd_names, bcm78900_b0_txpmd_fields};
    return bcm78900_b0_txpmd_info;
}

static const shr_enum_map_t bcm78900_b0_lbhdr_header_type_names[] =
{
    BCM78900_B0_LBHDR_HEADER_TYPE_NAME_MAP_INIT
};

static const shr_enum_map_t bcm78900_b0_lbhdr_start_names[] =
{
    BCM78900_B0_LBHDR_START_NAME_MAP_INIT
};

static bcmpkt_pmd_field_t bcm78900_b0_lbhdr_fields[BCM78900_B0_LBHDR_COUNT] = {
    {1, field_fmt_45_45_2_2_info, field_fmt_45_45_2_2_set, field_fmt_45_45_2_2_get, NULL, 0},
    {1, field_fmt_46_46_2_2_info, field_fmt_46_46_2_2_set, field_fmt_46_46_2_2_get, NULL, 0},
    {1, field_fmt_47_47_2_2_info, field_fmt_47_47_2_2_set, field_fmt_47_47_2_2_get, NULL, 0},
    {1, field_fmt_66_78_1_1_info, field_fmt_66_78_1_1_set, field_fmt_66_78_1_1_get, NULL, 0},
    {1, field_fmt_80_82_1_1_info, field_fmt_80_82_1_1_set, field_fmt_80_82_1_1_get, NULL, 0},
    {1, field_fmt_83_83_1_1_info, field_fmt_83_83_1_1_set, field_fmt_83_83_1_1_get, NULL, 0},
    {1, field_fmt_85_93_1_1_info, field_fmt_85_93_1_1_set, field_fmt_85_93_1_1_get, NULL, 0},
    {1, field_fmt_104_107_0_0_info, field_fmt_104_107_0_0_set, field_fmt_104_107_0_0_get, NULL, 0},
    {1, field_fmt_108_115_0_0_info, field_fmt_108_115_0_0_set, field_fmt_108_115_0_0_get, NULL, 0},
    {1, field_fmt_108_111_0_0_info, field_fmt_108_111_0_0_set, field_fmt_108_111_0_0_get, NULL, 0},
    {1, field_fmt_112_113_0_0_info, field_fmt_112_113_0_0_set, field_fmt_112_113_0_0_get, NULL, 0},
    {1, field_fmt_114_115_0_0_info, field_fmt_114_115_0_0_set, field_fmt_114_115_0_0_get, NULL, 0},
    {1, field_fmt_120_125_0_0_info, field_fmt_120_125_0_0_set, field_fmt_120_125_0_0_get, bcm78900_b0_lbhdr_header_type_names, 0},
    {1, field_fmt_126_127_0_0_info, field_fmt_126_127_0_0_set, field_fmt_126_127_0_0_get, bcm78900_b0_lbhdr_start_names, 0},

};

static const shr_enum_map_t bcm78900_b0_lbhdr_names[] =
{
    BCM78900_B0_LBHDR_NAME_MAP_INIT
};

bcmpkt_pmd_info_t bcm78900_b0_lbhdr_info_get(void)
{
    bcmpkt_pmd_info_t bcm78900_b0_lbhdr_info = {4, BCM78900_B0_LBHDR_COUNT, bcm78900_b0_lbhdr_names, bcm78900_b0_lbhdr_fields};
    return bcm78900_b0_lbhdr_info;
}
