#
# $Copyright: (c) 2024 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Linux Netlink channel for general packet I/O module.
#

include Kbuild

ifeq ($(KERNELRELEASE),)

MOD_NAME = genl-packet

include $(SDK)/make/lkm.mk

endif

.PHONY: distclean

distclean::
