# SPDX-License-Identifier: GPL-2.0
#
# Makefile for Marvell's OcteonTX2 BPHY RFOE netdev driver
#

obj-$(CONFIG_OCTEONTX2_BPHY_RFOE_NETDEV) += octeontx2_rfoe.o

octeontx2_rfoe-y := otx2_rfoe.o otx2_rfoe_ethtool.o
