# SPDX-License-Identifier: GPL-2.0
#
# Makefile for Marvell's OcteonTX2 BPHY RFOE netdev driver
#

obj-$(CONFIG_OCTEONTX2_BPHY_RFOE_NETDEV) += octeontx2_bphy_netdev.o

#EXTRA_CFLAGS += -DDEBUG

octeontx2_bphy_netdev-y := otx2_bphy_main.o otx2_rfoe.o otx2_rfoe_ethtool.o
